// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: panmail/v1/email_service.proto

package panmailv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendEmailRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	ProviderId string                 `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	From       string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To         []string               `protobuf:"bytes,3,rep,name=to,proto3" json:"to,omitempty"`
	Subject    string                 `protobuf:"bytes,4,opt,name=subject,proto3" json:"subject,omitempty"`
	// Deprecated: Marked as deprecated in panmail/v1/email_service.proto.
	Body string `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	// Deprecated: Marked as deprecated in panmail/v1/email_service.proto.
	IsHtml        bool             `protobuf:"varint,6,opt,name=is_html,json=isHtml,proto3" json:"is_html,omitempty"`
	BodyHtml      string           `protobuf:"bytes,9,opt,name=body_html,json=bodyHtml,proto3" json:"body_html,omitempty"`
	BodyText      string           `protobuf:"bytes,10,opt,name=body_text,json=bodyText,proto3" json:"body_text,omitempty"`
	TemplateId    string           `protobuf:"bytes,7,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	TemplateData  *structpb.Struct `protobuf:"bytes,8,opt,name=template_data,json=templateData,proto3" json:"template_data,omitempty"`
	Attachments   []*Attachment    `protobuf:"bytes,11,rep,name=attachments,proto3" json:"attachments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendEmailRequest) Reset() {
	*x = SendEmailRequest{}
	mi := &file_panmail_v1_email_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEmailRequest) ProtoMessage() {}

func (x *SendEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_panmail_v1_email_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEmailRequest.ProtoReflect.Descriptor instead.
func (*SendEmailRequest) Descriptor() ([]byte, []int) {
	return file_panmail_v1_email_service_proto_rawDescGZIP(), []int{0}
}

func (x *SendEmailRequest) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *SendEmailRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *SendEmailRequest) GetTo() []string {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *SendEmailRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

// Deprecated: Marked as deprecated in panmail/v1/email_service.proto.
func (x *SendEmailRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

// Deprecated: Marked as deprecated in panmail/v1/email_service.proto.
func (x *SendEmailRequest) GetIsHtml() bool {
	if x != nil {
		return x.IsHtml
	}
	return false
}

func (x *SendEmailRequest) GetBodyHtml() string {
	if x != nil {
		return x.BodyHtml
	}
	return ""
}

func (x *SendEmailRequest) GetBodyText() string {
	if x != nil {
		return x.BodyText
	}
	return ""
}

func (x *SendEmailRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *SendEmailRequest) GetTemplateData() *structpb.Struct {
	if x != nil {
		return x.TemplateData
	}
	return nil
}

func (x *SendEmailRequest) GetAttachments() []*Attachment {
	if x != nil {
		return x.Attachments
	}
	return nil
}

type SendEmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Status        EmailEventType         `protobuf:"varint,2,opt,name=status,proto3,enum=panmail.v1.EmailEventType" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendEmailResponse) Reset() {
	*x = SendEmailResponse{}
	mi := &file_panmail_v1_email_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEmailResponse) ProtoMessage() {}

func (x *SendEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_panmail_v1_email_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEmailResponse.ProtoReflect.Descriptor instead.
func (*SendEmailResponse) Descriptor() ([]byte, []int) {
	return file_panmail_v1_email_service_proto_rawDescGZIP(), []int{1}
}

func (x *SendEmailResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *SendEmailResponse) GetStatus() EmailEventType {
	if x != nil {
		return x.Status
	}
	return EmailEventType_EMAIL_EVENT_TYPE_UNSPECIFIED
}

func (x *SendEmailResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_panmail_v1_email_service_proto protoreflect.FileDescriptor

const file_panmail_v1_email_service_proto_rawDesc = "" +
	"\n" +
	"\x1epanmail/v1/email_service.proto\x12\n" +
	"panmail.v1\x1a\x16panmail/v1/event.proto\x1a\x17panmail/v1/common.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xf9\x02\n" +
	"\x10SendEmailRequest\x12\x1f\n" +
	"\vprovider_id\x18\x01 \x01(\tR\n" +
	"providerId\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x03 \x03(\tR\x02to\x12\x18\n" +
	"\asubject\x18\x04 \x01(\tR\asubject\x12\x16\n" +
	"\x04body\x18\x05 \x01(\tB\x02\x18\x01R\x04body\x12\x1b\n" +
	"\ais_html\x18\x06 \x01(\bB\x02\x18\x01R\x06isHtml\x12\x1b\n" +
	"\tbody_html\x18\t \x01(\tR\bbodyHtml\x12\x1b\n" +
	"\tbody_text\x18\n" +
	" \x01(\tR\bbodyText\x12\x1f\n" +
	"\vtemplate_id\x18\a \x01(\tR\n" +
	"templateId\x12<\n" +
	"\rtemplate_data\x18\b \x01(\v2\x17.google.protobuf.StructR\ftemplateData\x128\n" +
	"\vattachments\x18\v \x03(\v2\x16.panmail.v1.AttachmentR\vattachments\"|\n" +
	"\x11SendEmailResponse\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x122\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1a.panmail.v1.EmailEventTypeR\x06status\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error2X\n" +
	"\fEmailService\x12H\n" +
	"\tSendEmail\x12\x1c.panmail.v1.SendEmailRequest\x1a\x1d.panmail.v1.SendEmailResponseB\xa2\x01\n" +
	"\x0ecom.panmail.v1B\x11EmailServiceProtoP\x01Z4github.com/gsoultan/panmail/api/panmail/v1;panmailv1\xa2\x02\x03PXX\xaa\x02\n" +
	"Panmail.V1\xca\x02\n" +
	"Panmail\\V1\xe2\x02\x16Panmail\\V1\\GPBMetadata\xea\x02\vPanmail::V1b\x06proto3"

var (
	file_panmail_v1_email_service_proto_rawDescOnce sync.Once
	file_panmail_v1_email_service_proto_rawDescData []byte
)

func file_panmail_v1_email_service_proto_rawDescGZIP() []byte {
	file_panmail_v1_email_service_proto_rawDescOnce.Do(func() {
		file_panmail_v1_email_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_panmail_v1_email_service_proto_rawDesc), len(file_panmail_v1_email_service_proto_rawDesc)))
	})
	return file_panmail_v1_email_service_proto_rawDescData
}

var file_panmail_v1_email_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_panmail_v1_email_service_proto_goTypes = []any{
	(*SendEmailRequest)(nil),  // 0: panmail.v1.SendEmailRequest
	(*SendEmailResponse)(nil), // 1: panmail.v1.SendEmailResponse
	(*structpb.Struct)(nil),   // 2: google.protobuf.Struct
	(*Attachment)(nil),        // 3: panmail.v1.Attachment
	(EmailEventType)(0),       // 4: panmail.v1.EmailEventType
}
var file_panmail_v1_email_service_proto_depIdxs = []int32{
	2, // 0: panmail.v1.SendEmailRequest.template_data:type_name -> google.protobuf.Struct
	3, // 1: panmail.v1.SendEmailRequest.attachments:type_name -> panmail.v1.Attachment
	4, // 2: panmail.v1.SendEmailResponse.status:type_name -> panmail.v1.EmailEventType
	0, // 3: panmail.v1.EmailService.SendEmail:input_type -> panmail.v1.SendEmailRequest
	1, // 4: panmail.v1.EmailService.SendEmail:output_type -> panmail.v1.SendEmailResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_panmail_v1_email_service_proto_init() }
func file_panmail_v1_email_service_proto_init() {
	if File_panmail_v1_email_service_proto != nil {
		return
	}
	file_panmail_v1_event_proto_init()
	file_panmail_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_panmail_v1_email_service_proto_rawDesc), len(file_panmail_v1_email_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_panmail_v1_email_service_proto_goTypes,
		DependencyIndexes: file_panmail_v1_email_service_proto_depIdxs,
		MessageInfos:      file_panmail_v1_email_service_proto_msgTypes,
	}.Build()
	File_panmail_v1_email_service_proto = out.File
	file_panmail_v1_email_service_proto_goTypes = nil
	file_panmail_v1_email_service_proto_depIdxs = nil
}
