// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: panmail/v1/email_filter_service.proto

package panmailv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListFilterRulesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilterRulesRequest) Reset() {
	*x = ListFilterRulesRequest{}
	mi := &file_panmail_v1_email_filter_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilterRulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilterRulesRequest) ProtoMessage() {}

func (x *ListFilterRulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_panmail_v1_email_filter_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilterRulesRequest.ProtoReflect.Descriptor instead.
func (*ListFilterRulesRequest) Descriptor() ([]byte, []int) {
	return file_panmail_v1_email_filter_service_proto_rawDescGZIP(), []int{0}
}

type ListFilterRulesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rules         []*FilterRule          `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilterRulesResponse) Reset() {
	*x = ListFilterRulesResponse{}
	mi := &file_panmail_v1_email_filter_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilterRulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilterRulesResponse) ProtoMessage() {}

func (x *ListFilterRulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_panmail_v1_email_filter_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilterRulesResponse.ProtoReflect.Descriptor instead.
func (*ListFilterRulesResponse) Descriptor() ([]byte, []int) {
	return file_panmail_v1_email_filter_service_proto_rawDescGZIP(), []int{1}
}

func (x *ListFilterRulesResponse) GetRules() []*FilterRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

type CreateFilterRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rule          *FilterRule            `protobuf:"bytes,1,opt,name=rule,proto3" json:"rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFilterRuleRequest) Reset() {
	*x = CreateFilterRuleRequest{}
	mi := &file_panmail_v1_email_filter_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFilterRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFilterRuleRequest) ProtoMessage() {}

func (x *CreateFilterRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_panmail_v1_email_filter_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFilterRuleRequest.ProtoReflect.Descriptor instead.
func (*CreateFilterRuleRequest) Descriptor() ([]byte, []int) {
	return file_panmail_v1_email_filter_service_proto_rawDescGZIP(), []int{2}
}

func (x *CreateFilterRuleRequest) GetRule() *FilterRule {
	if x != nil {
		return x.Rule
	}
	return nil
}

type CreateFilterRuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rule          *FilterRule            `protobuf:"bytes,1,opt,name=rule,proto3" json:"rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFilterRuleResponse) Reset() {
	*x = CreateFilterRuleResponse{}
	mi := &file_panmail_v1_email_filter_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFilterRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFilterRuleResponse) ProtoMessage() {}

func (x *CreateFilterRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_panmail_v1_email_filter_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFilterRuleResponse.ProtoReflect.Descriptor instead.
func (*CreateFilterRuleResponse) Descriptor() ([]byte, []int) {
	return file_panmail_v1_email_filter_service_proto_rawDescGZIP(), []int{3}
}

func (x *CreateFilterRuleResponse) GetRule() *FilterRule {
	if x != nil {
		return x.Rule
	}
	return nil
}

type UpdateFilterRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rule          *FilterRule            `protobuf:"bytes,1,opt,name=rule,proto3" json:"rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFilterRuleRequest) Reset() {
	*x = UpdateFilterRuleRequest{}
	mi := &file_panmail_v1_email_filter_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFilterRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFilterRuleRequest) ProtoMessage() {}

func (x *UpdateFilterRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_panmail_v1_email_filter_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFilterRuleRequest.ProtoReflect.Descriptor instead.
func (*UpdateFilterRuleRequest) Descriptor() ([]byte, []int) {
	return file_panmail_v1_email_filter_service_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateFilterRuleRequest) GetRule() *FilterRule {
	if x != nil {
		return x.Rule
	}
	return nil
}

type UpdateFilterRuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rule          *FilterRule            `protobuf:"bytes,1,opt,name=rule,proto3" json:"rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFilterRuleResponse) Reset() {
	*x = UpdateFilterRuleResponse{}
	mi := &file_panmail_v1_email_filter_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFilterRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFilterRuleResponse) ProtoMessage() {}

func (x *UpdateFilterRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_panmail_v1_email_filter_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFilterRuleResponse.ProtoReflect.Descriptor instead.
func (*UpdateFilterRuleResponse) Descriptor() ([]byte, []int) {
	return file_panmail_v1_email_filter_service_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateFilterRuleResponse) GetRule() *FilterRule {
	if x != nil {
		return x.Rule
	}
	return nil
}

type DeleteFilterRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFilterRuleRequest) Reset() {
	*x = DeleteFilterRuleRequest{}
	mi := &file_panmail_v1_email_filter_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFilterRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFilterRuleRequest) ProtoMessage() {}

func (x *DeleteFilterRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_panmail_v1_email_filter_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFilterRuleRequest.ProtoReflect.Descriptor instead.
func (*DeleteFilterRuleRequest) Descriptor() ([]byte, []int) {
	return file_panmail_v1_email_filter_service_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteFilterRuleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteFilterRuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFilterRuleResponse) Reset() {
	*x = DeleteFilterRuleResponse{}
	mi := &file_panmail_v1_email_filter_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFilterRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFilterRuleResponse) ProtoMessage() {}

func (x *DeleteFilterRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_panmail_v1_email_filter_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFilterRuleResponse.ProtoReflect.Descriptor instead.
func (*DeleteFilterRuleResponse) Descriptor() ([]byte, []int) {
	return file_panmail_v1_email_filter_service_proto_rawDescGZIP(), []int{7}
}

type ListFilteredMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Direction     FilterDirection        `protobuf:"varint,1,opt,name=direction,proto3,enum=panmail.v1.FilterDirection" json:"direction,omitempty"`
	Status        FilterStatus           `protobuf:"varint,2,opt,name=status,proto3,enum=panmail.v1.FilterStatus" json:"status,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilteredMessagesRequest) Reset() {
	*x = ListFilteredMessagesRequest{}
	mi := &file_panmail_v1_email_filter_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilteredMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilteredMessagesRequest) ProtoMessage() {}

func (x *ListFilteredMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_panmail_v1_email_filter_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilteredMessagesRequest.ProtoReflect.Descriptor instead.
func (*ListFilteredMessagesRequest) Descriptor() ([]byte, []int) {
	return file_panmail_v1_email_filter_service_proto_rawDescGZIP(), []int{8}
}

func (x *ListFilteredMessagesRequest) GetDirection() FilterDirection {
	if x != nil {
		return x.Direction
	}
	return FilterDirection_FILTER_DIRECTION_UNSPECIFIED
}

func (x *ListFilteredMessagesRequest) GetStatus() FilterStatus {
	if x != nil {
		return x.Status
	}
	return FilterStatus_FILTER_STATUS_UNSPECIFIED
}

func (x *ListFilteredMessagesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListFilteredMessagesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListFilteredMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*FilteredMessage     `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilteredMessagesResponse) Reset() {
	*x = ListFilteredMessagesResponse{}
	mi := &file_panmail_v1_email_filter_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilteredMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilteredMessagesResponse) ProtoMessage() {}

func (x *ListFilteredMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_panmail_v1_email_filter_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilteredMessagesResponse.ProtoReflect.Descriptor instead.
func (*ListFilteredMessagesResponse) Descriptor() ([]byte, []int) {
	return file_panmail_v1_email_filter_service_proto_rawDescGZIP(), []int{9}
}

func (x *ListFilteredMessagesResponse) GetMessages() []*FilteredMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ListFilteredMessagesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type GetFilteredMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFilteredMessageRequest) Reset() {
	*x = GetFilteredMessageRequest{}
	mi := &file_panmail_v1_email_filter_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFilteredMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFilteredMessageRequest) ProtoMessage() {}

func (x *GetFilteredMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_panmail_v1_email_filter_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFilteredMessageRequest.ProtoReflect.Descriptor instead.
func (*GetFilteredMessageRequest) Descriptor() ([]byte, []int) {
	return file_panmail_v1_email_filter_service_proto_rawDescGZIP(), []int{10}
}

func (x *GetFilteredMessageRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetFilteredMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *FilteredMessage       `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFilteredMessageResponse) Reset() {
	*x = GetFilteredMessageResponse{}
	mi := &file_panmail_v1_email_filter_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFilteredMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFilteredMessageResponse) ProtoMessage() {}

func (x *GetFilteredMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_panmail_v1_email_filter_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFilteredMessageResponse.ProtoReflect.Descriptor instead.
func (*GetFilteredMessageResponse) Descriptor() ([]byte, []int) {
	return file_panmail_v1_email_filter_service_proto_rawDescGZIP(), []int{11}
}

func (x *GetFilteredMessageResponse) GetMessage() *FilteredMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

type ReleaseFilteredMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Note          string                 `protobuf:"bytes,2,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseFilteredMessageRequest) Reset() {
	*x = ReleaseFilteredMessageRequest{}
	mi := &file_panmail_v1_email_filter_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseFilteredMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseFilteredMessageRequest) ProtoMessage() {}

func (x *ReleaseFilteredMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_panmail_v1_email_filter_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseFilteredMessageRequest.ProtoReflect.Descriptor instead.
func (*ReleaseFilteredMessageRequest) Descriptor() ([]byte, []int) {
	return file_panmail_v1_email_filter_service_proto_rawDescGZIP(), []int{12}
}

func (x *ReleaseFilteredMessageRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ReleaseFilteredMessageRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type ReleaseFilteredMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *FilteredMessage       `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseFilteredMessageResponse) Reset() {
	*x = ReleaseFilteredMessageResponse{}
	mi := &file_panmail_v1_email_filter_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseFilteredMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseFilteredMessageResponse) ProtoMessage() {}

func (x *ReleaseFilteredMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_panmail_v1_email_filter_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseFilteredMessageResponse.ProtoReflect.Descriptor instead.
func (*ReleaseFilteredMessageResponse) Descriptor() ([]byte, []int) {
	return file_panmail_v1_email_filter_service_proto_rawDescGZIP(), []int{13}
}

func (x *ReleaseFilteredMessageResponse) GetMessage() *FilteredMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

type RejectFilteredMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Note          string                 `protobuf:"bytes,2,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectFilteredMessageRequest) Reset() {
	*x = RejectFilteredMessageRequest{}
	mi := &file_panmail_v1_email_filter_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectFilteredMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectFilteredMessageRequest) ProtoMessage() {}

func (x *RejectFilteredMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_panmail_v1_email_filter_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectFilteredMessageRequest.ProtoReflect.Descriptor instead.
func (*RejectFilteredMessageRequest) Descriptor() ([]byte, []int) {
	return file_panmail_v1_email_filter_service_proto_rawDescGZIP(), []int{14}
}

func (x *RejectFilteredMessageRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RejectFilteredMessageRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type RejectFilteredMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *FilteredMessage       `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectFilteredMessageResponse) Reset() {
	*x = RejectFilteredMessageResponse{}
	mi := &file_panmail_v1_email_filter_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectFilteredMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectFilteredMessageResponse) ProtoMessage() {}

func (x *RejectFilteredMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_panmail_v1_email_filter_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectFilteredMessageResponse.ProtoReflect.Descriptor instead.
func (*RejectFilteredMessageResponse) Descriptor() ([]byte, []int) {
	return file_panmail_v1_email_filter_service_proto_rawDescGZIP(), []int{15}
}

func (x *RejectFilteredMessageResponse) GetMessage() *FilteredMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

var File_panmail_v1_email_filter_service_proto protoreflect.FileDescriptor

const file_panmail_v1_email_filter_service_proto_rawDesc = "" +
	"\n" +
	"%panmail/v1/email_filter_service.proto\x12\n" +
	"panmail.v1\x1a\x1dpanmail/v1/email_filter.proto\"\x18\n" +
	"\x16ListFilterRulesRequest\"G\n" +
	"\x17ListFilterRulesResponse\x12,\n" +
	"\x05rules\x18\x01 \x03(\v2\x16.panmail.v1.FilterRuleR\x05rules\"E\n" +
	"\x17CreateFilterRuleRequest\x12*\n" +
	"\x04rule\x18\x01 \x01(\v2\x16.panmail.v1.FilterRuleR\x04rule\"F\n" +
	"\x18CreateFilterRuleResponse\x12*\n" +
	"\x04rule\x18\x01 \x01(\v2\x16.panmail.v1.FilterRuleR\x04rule\"E\n" +
	"\x17UpdateFilterRuleRequest\x12*\n" +
	"\x04rule\x18\x01 \x01(\v2\x16.panmail.v1.FilterRuleR\x04rule\"F\n" +
	"\x18UpdateFilterRuleResponse\x12*\n" +
	"\x04rule\x18\x01 \x01(\v2\x16.panmail.v1.FilterRuleR\x04rule\")\n" +
	"\x17DeleteFilterRuleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1a\n" +
	"\x18DeleteFilterRuleResponse\"\xc6\x01\n" +
	"\x1bListFilteredMessagesRequest\x129\n" +
	"\tdirection\x18\x01 \x01(\x0e2\x1b.panmail.v1.FilterDirectionR\tdirection\x120\n" +
	"\x06status\x18\x02 \x01(\x0e2\x18.panmail.v1.FilterStatusR\x06status\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tR\tpageToken\"\x7f\n" +
	"\x1cListFilteredMessagesResponse\x127\n" +
	"\bmessages\x18\x01 \x03(\v2\x1b.panmail.v1.FilteredMessageR\bmessages\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"+\n" +
	"\x19GetFilteredMessageRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"S\n" +
	"\x1aGetFilteredMessageResponse\x125\n" +
	"\amessage\x18\x01 \x01(\v2\x1b.panmail.v1.FilteredMessageR\amessage\"C\n" +
	"\x1dReleaseFilteredMessageRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04note\x18\x02 \x01(\tR\x04note\"W\n" +
	"\x1eReleaseFilteredMessageResponse\x125\n" +
	"\amessage\x18\x01 \x01(\v2\x1b.panmail.v1.FilteredMessageR\amessage\"B\n" +
	"\x1cRejectFilteredMessageRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04note\x18\x02 \x01(\tR\x04note\"V\n" +
	"\x1dRejectFilteredMessageResponse\x125\n" +
	"\amessage\x18\x01 \x01(\v2\x1b.panmail.v1.FilteredMessageR\amessage2\xbc\x06\n" +
	"\x12EmailFilterService\x12Z\n" +
	"\x0fListFilterRules\x12\".panmail.v1.ListFilterRulesRequest\x1a#.panmail.v1.ListFilterRulesResponse\x12]\n" +
	"\x10CreateFilterRule\x12#.panmail.v1.CreateFilterRuleRequest\x1a$.panmail.v1.CreateFilterRuleResponse\x12]\n" +
	"\x10UpdateFilterRule\x12#.panmail.v1.UpdateFilterRuleRequest\x1a$.panmail.v1.UpdateFilterRuleResponse\x12]\n" +
	"\x10DeleteFilterRule\x12#.panmail.v1.DeleteFilterRuleRequest\x1a$.panmail.v1.DeleteFilterRuleResponse\x12i\n" +
	"\x14ListFilteredMessages\x12'.panmail.v1.ListFilteredMessagesRequest\x1a(.panmail.v1.ListFilteredMessagesResponse\x12c\n" +
	"\x12GetFilteredMessage\x12%.panmail.v1.GetFilteredMessageRequest\x1a&.panmail.v1.GetFilteredMessageResponse\x12o\n" +
	"\x16ReleaseFilteredMessage\x12).panmail.v1.ReleaseFilteredMessageRequest\x1a*.panmail.v1.ReleaseFilteredMessageResponse\x12l\n" +
	"\x15RejectFilteredMessage\x12(.panmail.v1.RejectFilteredMessageRequest\x1a).panmail.v1.RejectFilteredMessageResponseB\xa8\x01\n" +
	"\x0ecom.panmail.v1B\x17EmailFilterServiceProtoP\x01Z4github.com/gsoultan/panmail/api/panmail/v1;panmailv1\xa2\x02\x03PXX\xaa\x02\n" +
	"Panmail.V1\xca\x02\n" +
	"Panmail\\V1\xe2\x02\x16Panmail\\V1\\GPBMetadata\xea\x02\vPanmail::V1b\x06proto3"

var (
	file_panmail_v1_email_filter_service_proto_rawDescOnce sync.Once
	file_panmail_v1_email_filter_service_proto_rawDescData []byte
)

func file_panmail_v1_email_filter_service_proto_rawDescGZIP() []byte {
	file_panmail_v1_email_filter_service_proto_rawDescOnce.Do(func() {
		file_panmail_v1_email_filter_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_panmail_v1_email_filter_service_proto_rawDesc), len(file_panmail_v1_email_filter_service_proto_rawDesc)))
	})
	return file_panmail_v1_email_filter_service_proto_rawDescData
}

var file_panmail_v1_email_filter_service_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_panmail_v1_email_filter_service_proto_goTypes = []any{
	(*ListFilterRulesRequest)(nil),         // 0: panmail.v1.ListFilterRulesRequest
	(*ListFilterRulesResponse)(nil),        // 1: panmail.v1.ListFilterRulesResponse
	(*CreateFilterRuleRequest)(nil),        // 2: panmail.v1.CreateFilterRuleRequest
	(*CreateFilterRuleResponse)(nil),       // 3: panmail.v1.CreateFilterRuleResponse
	(*UpdateFilterRuleRequest)(nil),        // 4: panmail.v1.UpdateFilterRuleRequest
	(*UpdateFilterRuleResponse)(nil),       // 5: panmail.v1.UpdateFilterRuleResponse
	(*DeleteFilterRuleRequest)(nil),        // 6: panmail.v1.DeleteFilterRuleRequest
	(*DeleteFilterRuleResponse)(nil),       // 7: panmail.v1.DeleteFilterRuleResponse
	(*ListFilteredMessagesRequest)(nil),    // 8: panmail.v1.ListFilteredMessagesRequest
	(*ListFilteredMessagesResponse)(nil),   // 9: panmail.v1.ListFilteredMessagesResponse
	(*GetFilteredMessageRequest)(nil),      // 10: panmail.v1.GetFilteredMessageRequest
	(*GetFilteredMessageResponse)(nil),     // 11: panmail.v1.GetFilteredMessageResponse
	(*ReleaseFilteredMessageRequest)(nil),  // 12: panmail.v1.ReleaseFilteredMessageRequest
	(*ReleaseFilteredMessageResponse)(nil), // 13: panmail.v1.ReleaseFilteredMessageResponse
	(*RejectFilteredMessageRequest)(nil),   // 14: panmail.v1.RejectFilteredMessageRequest
	(*RejectFilteredMessageResponse)(nil),  // 15: panmail.v1.RejectFilteredMessageResponse
	(*FilterRule)(nil),                     // 16: panmail.v1.FilterRule
	(FilterDirection)(0),                   // 17: panmail.v1.FilterDirection
	(FilterStatus)(0),                      // 18: panmail.v1.FilterStatus
	(*FilteredMessage)(nil),                // 19: panmail.v1.FilteredMessage
}
var file_panmail_v1_email_filter_service_proto_depIdxs = []int32{
	16, // 0: panmail.v1.ListFilterRulesResponse.rules:type_name -> panmail.v1.FilterRule
	16, // 1: panmail.v1.CreateFilterRuleRequest.rule:type_name -> panmail.v1.FilterRule
	16, // 2: panmail.v1.CreateFilterRuleResponse.rule:type_name -> panmail.v1.FilterRule
	16, // 3: panmail.v1.UpdateFilterRuleRequest.rule:type_name -> panmail.v1.FilterRule
	16, // 4: panmail.v1.UpdateFilterRuleResponse.rule:type_name -> panmail.v1.FilterRule
	17, // 5: panmail.v1.ListFilteredMessagesRequest.direction:type_name -> panmail.v1.FilterDirection
	18, // 6: panmail.v1.ListFilteredMessagesRequest.status:type_name -> panmail.v1.FilterStatus
	19, // 7: panmail.v1.ListFilteredMessagesResponse.messages:type_name -> panmail.v1.FilteredMessage
	19, // 8: panmail.v1.GetFilteredMessageResponse.message:type_name -> panmail.v1.FilteredMessage
	19, // 9: panmail.v1.ReleaseFilteredMessageResponse.message:type_name -> panmail.v1.FilteredMessage
	19, // 10: panmail.v1.RejectFilteredMessageResponse.message:type_name -> panmail.v1.FilteredMessage
	0,  // 11: panmail.v1.EmailFilterService.ListFilterRules:input_type -> panmail.v1.ListFilterRulesRequest
	2,  // 12: panmail.v1.EmailFilterService.CreateFilterRule:input_type -> panmail.v1.CreateFilterRuleRequest
	4,  // 13: panmail.v1.EmailFilterService.UpdateFilterRule:input_type -> panmail.v1.UpdateFilterRuleRequest
	6,  // 14: panmail.v1.EmailFilterService.DeleteFilterRule:input_type -> panmail.v1.DeleteFilterRuleRequest
	8,  // 15: panmail.v1.EmailFilterService.ListFilteredMessages:input_type -> panmail.v1.ListFilteredMessagesRequest
	10, // 16: panmail.v1.EmailFilterService.GetFilteredMessage:input_type -> panmail.v1.GetFilteredMessageRequest
	12, // 17: panmail.v1.EmailFilterService.ReleaseFilteredMessage:input_type -> panmail.v1.ReleaseFilteredMessageRequest
	14, // 18: panmail.v1.EmailFilterService.RejectFilteredMessage:input_type -> panmail.v1.RejectFilteredMessageRequest
	1,  // 19: panmail.v1.EmailFilterService.ListFilterRules:output_type -> panmail.v1.ListFilterRulesResponse
	3,  // 20: panmail.v1.EmailFilterService.CreateFilterRule:output_type -> panmail.v1.CreateFilterRuleResponse
	5,  // 21: panmail.v1.EmailFilterService.UpdateFilterRule:output_type -> panmail.v1.UpdateFilterRuleResponse
	7,  // 22: panmail.v1.EmailFilterService.DeleteFilterRule:output_type -> panmail.v1.DeleteFilterRuleResponse
	9,  // 23: panmail.v1.EmailFilterService.ListFilteredMessages:output_type -> panmail.v1.ListFilteredMessagesResponse
	11, // 24: panmail.v1.EmailFilterService.GetFilteredMessage:output_type -> panmail.v1.GetFilteredMessageResponse
	13, // 25: panmail.v1.EmailFilterService.ReleaseFilteredMessage:output_type -> panmail.v1.ReleaseFilteredMessageResponse
	15, // 26: panmail.v1.EmailFilterService.RejectFilteredMessage:output_type -> panmail.v1.RejectFilteredMessageResponse
	19, // [19:27] is the sub-list for method output_type
	11, // [11:19] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_panmail_v1_email_filter_service_proto_init() }
func file_panmail_v1_email_filter_service_proto_init() {
	if File_panmail_v1_email_filter_service_proto != nil {
		return
	}
	file_panmail_v1_email_filter_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_panmail_v1_email_filter_service_proto_rawDesc), len(file_panmail_v1_email_filter_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_panmail_v1_email_filter_service_proto_goTypes,
		DependencyIndexes: file_panmail_v1_email_filter_service_proto_depIdxs,
		MessageInfos:      file_panmail_v1_email_filter_service_proto_msgTypes,
	}.Build()
	File_panmail_v1_email_filter_service_proto = out.File
	file_panmail_v1_email_filter_service_proto_goTypes = nil
	file_panmail_v1_email_filter_service_proto_depIdxs = nil
}
