// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: panmail/v1/email_provider.proto

package panmailv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmailProvider struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type  ProviderType           `protobuf:"varint,3,opt,name=type,proto3,enum=panmail.v1.ProviderType" json:"type,omitempty"`
	// Types that are valid to be assigned to Config:
	//
	//	*EmailProvider_Smtp
	//	*EmailProvider_Imap
	//	*EmailProvider_Pop3
	Config         isEmailProvider_Config `protobuf_oneof:"config"`
	CreateTime     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	TenantId       string                 `protobuf:"bytes,13,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	AllowedDomains []string               `protobuf:"bytes,14,rep,name=allowed_domains,json=allowedDomains,proto3" json:"allowed_domains,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EmailProvider) Reset() {
	*x = EmailProvider{}
	mi := &file_panmail_v1_email_provider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailProvider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailProvider) ProtoMessage() {}

func (x *EmailProvider) ProtoReflect() protoreflect.Message {
	mi := &file_panmail_v1_email_provider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailProvider.ProtoReflect.Descriptor instead.
func (*EmailProvider) Descriptor() ([]byte, []int) {
	return file_panmail_v1_email_provider_proto_rawDescGZIP(), []int{0}
}

func (x *EmailProvider) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EmailProvider) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EmailProvider) GetType() ProviderType {
	if x != nil {
		return x.Type
	}
	return ProviderType_PROVIDER_TYPE_UNSPECIFIED
}

func (x *EmailProvider) GetConfig() isEmailProvider_Config {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *EmailProvider) GetSmtp() *SmtpConfig {
	if x != nil {
		if x, ok := x.Config.(*EmailProvider_Smtp); ok {
			return x.Smtp
		}
	}
	return nil
}

func (x *EmailProvider) GetImap() *ImapConfig {
	if x != nil {
		if x, ok := x.Config.(*EmailProvider_Imap); ok {
			return x.Imap
		}
	}
	return nil
}

func (x *EmailProvider) GetPop3() *Pop3Config {
	if x != nil {
		if x, ok := x.Config.(*EmailProvider_Pop3); ok {
			return x.Pop3
		}
	}
	return nil
}

func (x *EmailProvider) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *EmailProvider) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

func (x *EmailProvider) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *EmailProvider) GetAllowedDomains() []string {
	if x != nil {
		return x.AllowedDomains
	}
	return nil
}

type isEmailProvider_Config interface {
	isEmailProvider_Config()
}

type EmailProvider_Smtp struct {
	Smtp *SmtpConfig `protobuf:"bytes,4,opt,name=smtp,proto3,oneof"`
}

type EmailProvider_Imap struct {
	Imap *ImapConfig `protobuf:"bytes,9,opt,name=imap,proto3,oneof"`
}

type EmailProvider_Pop3 struct {
	Pop3 *Pop3Config `protobuf:"bytes,10,opt,name=pop3,proto3,oneof"`
}

func (*EmailProvider_Smtp) isEmailProvider_Config() {}

func (*EmailProvider_Imap) isEmailProvider_Config() {}

func (*EmailProvider_Pop3) isEmailProvider_Config() {}

type SmtpConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	SkipVerify    bool                   `protobuf:"varint,5,opt,name=skip_verify,json=skipVerify,proto3" json:"skip_verify,omitempty"`
	UseSsl        bool                   `protobuf:"varint,6,opt,name=use_ssl,json=useSsl,proto3" json:"use_ssl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SmtpConfig) Reset() {
	*x = SmtpConfig{}
	mi := &file_panmail_v1_email_provider_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SmtpConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SmtpConfig) ProtoMessage() {}

func (x *SmtpConfig) ProtoReflect() protoreflect.Message {
	mi := &file_panmail_v1_email_provider_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SmtpConfig.ProtoReflect.Descriptor instead.
func (*SmtpConfig) Descriptor() ([]byte, []int) {
	return file_panmail_v1_email_provider_proto_rawDescGZIP(), []int{1}
}

func (x *SmtpConfig) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *SmtpConfig) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *SmtpConfig) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SmtpConfig) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *SmtpConfig) GetSkipVerify() bool {
	if x != nil {
		return x.SkipVerify
	}
	return false
}

func (x *SmtpConfig) GetUseSsl() bool {
	if x != nil {
		return x.UseSsl
	}
	return false
}

type ImapConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	SkipVerify    bool                   `protobuf:"varint,5,opt,name=skip_verify,json=skipVerify,proto3" json:"skip_verify,omitempty"`
	UseSsl        bool                   `protobuf:"varint,6,opt,name=use_ssl,json=useSsl,proto3" json:"use_ssl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImapConfig) Reset() {
	*x = ImapConfig{}
	mi := &file_panmail_v1_email_provider_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImapConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImapConfig) ProtoMessage() {}

func (x *ImapConfig) ProtoReflect() protoreflect.Message {
	mi := &file_panmail_v1_email_provider_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImapConfig.ProtoReflect.Descriptor instead.
func (*ImapConfig) Descriptor() ([]byte, []int) {
	return file_panmail_v1_email_provider_proto_rawDescGZIP(), []int{2}
}

func (x *ImapConfig) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ImapConfig) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ImapConfig) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ImapConfig) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ImapConfig) GetSkipVerify() bool {
	if x != nil {
		return x.SkipVerify
	}
	return false
}

func (x *ImapConfig) GetUseSsl() bool {
	if x != nil {
		return x.UseSsl
	}
	return false
}

type Pop3Config struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	SkipVerify    bool                   `protobuf:"varint,5,opt,name=skip_verify,json=skipVerify,proto3" json:"skip_verify,omitempty"`
	UseSsl        bool                   `protobuf:"varint,6,opt,name=use_ssl,json=useSsl,proto3" json:"use_ssl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pop3Config) Reset() {
	*x = Pop3Config{}
	mi := &file_panmail_v1_email_provider_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pop3Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pop3Config) ProtoMessage() {}

func (x *Pop3Config) ProtoReflect() protoreflect.Message {
	mi := &file_panmail_v1_email_provider_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pop3Config.ProtoReflect.Descriptor instead.
func (*Pop3Config) Descriptor() ([]byte, []int) {
	return file_panmail_v1_email_provider_proto_rawDescGZIP(), []int{3}
}

func (x *Pop3Config) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Pop3Config) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Pop3Config) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Pop3Config) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Pop3Config) GetSkipVerify() bool {
	if x != nil {
		return x.SkipVerify
	}
	return false
}

func (x *Pop3Config) GetUseSsl() bool {
	if x != nil {
		return x.UseSsl
	}
	return false
}

var File_panmail_v1_email_provider_proto protoreflect.FileDescriptor

const file_panmail_v1_email_provider_proto_rawDesc = "" +
	"\n" +
	"\x1fpanmail/v1/email_provider.proto\x12\n" +
	"panmail.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1epanmail/v1/provider_type.proto\"\xb5\x03\n" +
	"\rEmailProvider\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12,\n" +
	"\x04type\x18\x03 \x01(\x0e2\x18.panmail.v1.ProviderTypeR\x04type\x12,\n" +
	"\x04smtp\x18\x04 \x01(\v2\x16.panmail.v1.SmtpConfigH\x00R\x04smtp\x12,\n" +
	"\x04imap\x18\t \x01(\v2\x16.panmail.v1.ImapConfigH\x00R\x04imap\x12,\n" +
	"\x04pop3\x18\n" +
	" \x01(\v2\x16.panmail.v1.Pop3ConfigH\x00R\x04pop3\x12;\n" +
	"\vcreate_time\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12;\n" +
	"\vupdate_time\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\x12\x1b\n" +
	"\ttenant_id\x18\r \x01(\tR\btenantId\x12'\n" +
	"\x0fallowed_domains\x18\x0e \x03(\tR\x0eallowedDomainsB\b\n" +
	"\x06config\"\xa6\x01\n" +
	"\n" +
	"SmtpConfig\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12\x1f\n" +
	"\vskip_verify\x18\x05 \x01(\bR\n" +
	"skipVerify\x12\x17\n" +
	"\ause_ssl\x18\x06 \x01(\bR\x06useSsl\"\xa6\x01\n" +
	"\n" +
	"ImapConfig\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12\x1f\n" +
	"\vskip_verify\x18\x05 \x01(\bR\n" +
	"skipVerify\x12\x17\n" +
	"\ause_ssl\x18\x06 \x01(\bR\x06useSsl\"\xa6\x01\n" +
	"\n" +
	"Pop3Config\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12\x1f\n" +
	"\vskip_verify\x18\x05 \x01(\bR\n" +
	"skipVerify\x12\x17\n" +
	"\ause_ssl\x18\x06 \x01(\bR\x06useSslB\xa3\x01\n" +
	"\x0ecom.panmail.v1B\x12EmailProviderProtoP\x01Z4github.com/gsoultan/panmail/api/panmail/v1;panmailv1\xa2\x02\x03PXX\xaa\x02\n" +
	"Panmail.V1\xca\x02\n" +
	"Panmail\\V1\xe2\x02\x16Panmail\\V1\\GPBMetadata\xea\x02\vPanmail::V1b\x06proto3"

var (
	file_panmail_v1_email_provider_proto_rawDescOnce sync.Once
	file_panmail_v1_email_provider_proto_rawDescData []byte
)

func file_panmail_v1_email_provider_proto_rawDescGZIP() []byte {
	file_panmail_v1_email_provider_proto_rawDescOnce.Do(func() {
		file_panmail_v1_email_provider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_panmail_v1_email_provider_proto_rawDesc), len(file_panmail_v1_email_provider_proto_rawDesc)))
	})
	return file_panmail_v1_email_provider_proto_rawDescData
}

var file_panmail_v1_email_provider_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_panmail_v1_email_provider_proto_goTypes = []any{
	(*EmailProvider)(nil),         // 0: panmail.v1.EmailProvider
	(*SmtpConfig)(nil),            // 1: panmail.v1.SmtpConfig
	(*ImapConfig)(nil),            // 2: panmail.v1.ImapConfig
	(*Pop3Config)(nil),            // 3: panmail.v1.Pop3Config
	(ProviderType)(0),             // 4: panmail.v1.ProviderType
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_panmail_v1_email_provider_proto_depIdxs = []int32{
	4, // 0: panmail.v1.EmailProvider.type:type_name -> panmail.v1.ProviderType
	1, // 1: panmail.v1.EmailProvider.smtp:type_name -> panmail.v1.SmtpConfig
	2, // 2: panmail.v1.EmailProvider.imap:type_name -> panmail.v1.ImapConfig
	3, // 3: panmail.v1.EmailProvider.pop3:type_name -> panmail.v1.Pop3Config
	5, // 4: panmail.v1.EmailProvider.create_time:type_name -> google.protobuf.Timestamp
	5, // 5: panmail.v1.EmailProvider.update_time:type_name -> google.protobuf.Timestamp
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_panmail_v1_email_provider_proto_init() }
func file_panmail_v1_email_provider_proto_init() {
	if File_panmail_v1_email_provider_proto != nil {
		return
	}
	file_panmail_v1_provider_type_proto_init()
	file_panmail_v1_email_provider_proto_msgTypes[0].OneofWrappers = []any{
		(*EmailProvider_Smtp)(nil),
		(*EmailProvider_Imap)(nil),
		(*EmailProvider_Pop3)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_panmail_v1_email_provider_proto_rawDesc), len(file_panmail_v1_email_provider_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_panmail_v1_email_provider_proto_goTypes,
		DependencyIndexes: file_panmail_v1_email_provider_proto_depIdxs,
		MessageInfos:      file_panmail_v1_email_provider_proto_msgTypes,
	}.Build()
	File_panmail_v1_email_provider_proto = out.File
	file_panmail_v1_email_provider_proto_goTypes = nil
	file_panmail_v1_email_provider_proto_depIdxs = nil
}
