// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: panmail/v1/inbound_service.proto

package panmailv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListInboundEmailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInboundEmailsRequest) Reset() {
	*x = ListInboundEmailsRequest{}
	mi := &file_panmail_v1_inbound_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInboundEmailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInboundEmailsRequest) ProtoMessage() {}

func (x *ListInboundEmailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_panmail_v1_inbound_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInboundEmailsRequest.ProtoReflect.Descriptor instead.
func (*ListInboundEmailsRequest) Descriptor() ([]byte, []int) {
	return file_panmail_v1_inbound_service_proto_rawDescGZIP(), []int{0}
}

func (x *ListInboundEmailsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListInboundEmailsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListInboundEmailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Emails        []*InboundEmail        `protobuf:"bytes,1,rep,name=emails,proto3" json:"emails,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInboundEmailsResponse) Reset() {
	*x = ListInboundEmailsResponse{}
	mi := &file_panmail_v1_inbound_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInboundEmailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInboundEmailsResponse) ProtoMessage() {}

func (x *ListInboundEmailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_panmail_v1_inbound_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInboundEmailsResponse.ProtoReflect.Descriptor instead.
func (*ListInboundEmailsResponse) Descriptor() ([]byte, []int) {
	return file_panmail_v1_inbound_service_proto_rawDescGZIP(), []int{1}
}

func (x *ListInboundEmailsResponse) GetEmails() []*InboundEmail {
	if x != nil {
		return x.Emails
	}
	return nil
}

func (x *ListInboundEmailsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type GetInboundEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInboundEmailRequest) Reset() {
	*x = GetInboundEmailRequest{}
	mi := &file_panmail_v1_inbound_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInboundEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInboundEmailRequest) ProtoMessage() {}

func (x *GetInboundEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_panmail_v1_inbound_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInboundEmailRequest.ProtoReflect.Descriptor instead.
func (*GetInboundEmailRequest) Descriptor() ([]byte, []int) {
	return file_panmail_v1_inbound_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetInboundEmailRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetInboundEmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         *InboundEmail          `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInboundEmailResponse) Reset() {
	*x = GetInboundEmailResponse{}
	mi := &file_panmail_v1_inbound_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInboundEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInboundEmailResponse) ProtoMessage() {}

func (x *GetInboundEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_panmail_v1_inbound_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInboundEmailResponse.ProtoReflect.Descriptor instead.
func (*GetInboundEmailResponse) Descriptor() ([]byte, []int) {
	return file_panmail_v1_inbound_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetInboundEmailResponse) GetEmail() *InboundEmail {
	if x != nil {
		return x.Email
	}
	return nil
}

var File_panmail_v1_inbound_service_proto protoreflect.FileDescriptor

const file_panmail_v1_inbound_service_proto_rawDesc = "" +
	"\n" +
	" panmail/v1/inbound_service.proto\x12\n" +
	"panmail.v1\x1a\x18panmail/v1/inbound.proto\"V\n" +
	"\x18ListInboundEmailsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"u\n" +
	"\x19ListInboundEmailsResponse\x120\n" +
	"\x06emails\x18\x01 \x03(\v2\x18.panmail.v1.InboundEmailR\x06emails\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"(\n" +
	"\x16GetInboundEmailRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"I\n" +
	"\x17GetInboundEmailResponse\x12.\n" +
	"\x05email\x18\x01 \x01(\v2\x18.panmail.v1.InboundEmailR\x05email2\xce\x01\n" +
	"\x0eInboundService\x12`\n" +
	"\x11ListInboundEmails\x12$.panmail.v1.ListInboundEmailsRequest\x1a%.panmail.v1.ListInboundEmailsResponse\x12Z\n" +
	"\x0fGetInboundEmail\x12\".panmail.v1.GetInboundEmailRequest\x1a#.panmail.v1.GetInboundEmailResponseB\xa4\x01\n" +
	"\x0ecom.panmail.v1B\x13InboundServiceProtoP\x01Z4github.com/gsoultan/panmail/api/panmail/v1;panmailv1\xa2\x02\x03PXX\xaa\x02\n" +
	"Panmail.V1\xca\x02\n" +
	"Panmail\\V1\xe2\x02\x16Panmail\\V1\\GPBMetadata\xea\x02\vPanmail::V1b\x06proto3"

var (
	file_panmail_v1_inbound_service_proto_rawDescOnce sync.Once
	file_panmail_v1_inbound_service_proto_rawDescData []byte
)

func file_panmail_v1_inbound_service_proto_rawDescGZIP() []byte {
	file_panmail_v1_inbound_service_proto_rawDescOnce.Do(func() {
		file_panmail_v1_inbound_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_panmail_v1_inbound_service_proto_rawDesc), len(file_panmail_v1_inbound_service_proto_rawDesc)))
	})
	return file_panmail_v1_inbound_service_proto_rawDescData
}

var file_panmail_v1_inbound_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_panmail_v1_inbound_service_proto_goTypes = []any{
	(*ListInboundEmailsRequest)(nil),  // 0: panmail.v1.ListInboundEmailsRequest
	(*ListInboundEmailsResponse)(nil), // 1: panmail.v1.ListInboundEmailsResponse
	(*GetInboundEmailRequest)(nil),    // 2: panmail.v1.GetInboundEmailRequest
	(*GetInboundEmailResponse)(nil),   // 3: panmail.v1.GetInboundEmailResponse
	(*InboundEmail)(nil),              // 4: panmail.v1.InboundEmail
}
var file_panmail_v1_inbound_service_proto_depIdxs = []int32{
	4, // 0: panmail.v1.ListInboundEmailsResponse.emails:type_name -> panmail.v1.InboundEmail
	4, // 1: panmail.v1.GetInboundEmailResponse.email:type_name -> panmail.v1.InboundEmail
	0, // 2: panmail.v1.InboundService.ListInboundEmails:input_type -> panmail.v1.ListInboundEmailsRequest
	2, // 3: panmail.v1.InboundService.GetInboundEmail:input_type -> panmail.v1.GetInboundEmailRequest
	1, // 4: panmail.v1.InboundService.ListInboundEmails:output_type -> panmail.v1.ListInboundEmailsResponse
	3, // 5: panmail.v1.InboundService.GetInboundEmail:output_type -> panmail.v1.GetInboundEmailResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_panmail_v1_inbound_service_proto_init() }
func file_panmail_v1_inbound_service_proto_init() {
	if File_panmail_v1_inbound_service_proto != nil {
		return
	}
	file_panmail_v1_inbound_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_panmail_v1_inbound_service_proto_rawDesc), len(file_panmail_v1_inbound_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_panmail_v1_inbound_service_proto_goTypes,
		DependencyIndexes: file_panmail_v1_inbound_service_proto_depIdxs,
		MessageInfos:      file_panmail_v1_inbound_service_proto_msgTypes,
	}.Build()
	File_panmail_v1_inbound_service_proto = out.File
	file_panmail_v1_inbound_service_proto_goTypes = nil
	file_panmail_v1_inbound_service_proto_depIdxs = nil
}
