// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: panmail/v1/system_settings.proto

package panmailv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SmtpBindScope is where the submission listener accepts connections, as a
// closed set rather than a host string.
//
// An address typed into a form is unvalidatable input that decides how far a
// port is reachable, so the wire carries the decision instead of the address:
// there are exactly two answers worth giving, and neither can be malformed.
type SmtpBindScope int32

const (
	SmtpBindScope_SMTP_BIND_SCOPE_UNSPECIFIED SmtpBindScope = 0
	// 127.0.0.1 — reachable only from this host. The only scope on which
	// cleartext AUTH is allowed, because nothing can be on the path.
	SmtpBindScope_SMTP_BIND_SCOPE_LOOPBACK SmtpBindScope = 1
	// 0.0.0.0 — every interface. Requires TLS: see allow_insecure_auth.
	SmtpBindScope_SMTP_BIND_SCOPE_ALL_INTERFACES SmtpBindScope = 2
)

// Enum value maps for SmtpBindScope.
var (
	SmtpBindScope_name = map[int32]string{
		0: "SMTP_BIND_SCOPE_UNSPECIFIED",
		1: "SMTP_BIND_SCOPE_LOOPBACK",
		2: "SMTP_BIND_SCOPE_ALL_INTERFACES",
	}
	SmtpBindScope_value = map[string]int32{
		"SMTP_BIND_SCOPE_UNSPECIFIED":    0,
		"SMTP_BIND_SCOPE_LOOPBACK":       1,
		"SMTP_BIND_SCOPE_ALL_INTERFACES": 2,
	}
)

func (x SmtpBindScope) Enum() *SmtpBindScope {
	p := new(SmtpBindScope)
	*p = x
	return p
}

func (x SmtpBindScope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SmtpBindScope) Descriptor() protoreflect.EnumDescriptor {
	return file_panmail_v1_system_settings_proto_enumTypes[0].Descriptor()
}

func (SmtpBindScope) Type() protoreflect.EnumType {
	return &file_panmail_v1_system_settings_proto_enumTypes[0]
}

func (x SmtpBindScope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SmtpBindScope.Descriptor instead.
func (SmtpBindScope) EnumDescriptor() ([]byte, []int) {
	return file_panmail_v1_system_settings_proto_rawDescGZIP(), []int{0}
}

// ContentRedaction is how hard the gateway looks for secrets in a message body
// before showing it back.
//
// UNSPECIFIED is distinct from OFF on purpose, and it is the same distinction
// the two nullable retention columns exist for: "nobody has chosen" has to be
// tellable from "somebody chose none", or an operator who deliberately turned
// redaction off gets it switched back on by the next default change.
type ContentRedaction int32

const (
	ContentRedaction_CONTENT_REDACTION_UNSPECIFIED ContentRedaction = 0
	// Show the body as stored. A deliberate choice, and the only value that
	// shows a password in the dashboard.
	ContentRedaction_CONTENT_REDACTION_OFF ContentRedaction = 1
	// The default. Masks the value after a password-like label — password, pwd,
	// passcode, passphrase — and, with no label needed, credentials whose shape
	// identifies them: PEM private key blocks, JWTs, and issued keys that carry
	// their own prefix (AWS, GitHub, Stripe, Slack, Google, SendGrid).
	//
	// The shapes are on at the default level because they are issued rather than
	// chosen, so there is no false positive to weigh against leaking one. The
	// label patterns stay narrow, so a message that merely discusses passwords
	// survives intact.
	ContentRedaction_CONTENT_REDACTION_PASSWORDS ContentRedaction = 2
	// Adds one-time codes: OTP, PIN, verification and security codes. Worth as
	// much as a password for as long as they are valid, which is usually longer
	// than the message takes to reach the dashboard.
	ContentRedaction_CONTENT_REDACTION_CODES ContentRedaction = 3
	// Adds bearer-token and API-key labels, and payment card numbers validated
	// with the Luhn checksum. The widest setting and the most likely to mask
	// something that was not a secret — a card number is a plausible run of
	// digits rather than an issued shape, which is why it waits for this level
	// instead of firing at the default.
	ContentRedaction_CONTENT_REDACTION_SECRETS ContentRedaction = 4
)

// Enum value maps for ContentRedaction.
var (
	ContentRedaction_name = map[int32]string{
		0: "CONTENT_REDACTION_UNSPECIFIED",
		1: "CONTENT_REDACTION_OFF",
		2: "CONTENT_REDACTION_PASSWORDS",
		3: "CONTENT_REDACTION_CODES",
		4: "CONTENT_REDACTION_SECRETS",
	}
	ContentRedaction_value = map[string]int32{
		"CONTENT_REDACTION_UNSPECIFIED": 0,
		"CONTENT_REDACTION_OFF":         1,
		"CONTENT_REDACTION_PASSWORDS":   2,
		"CONTENT_REDACTION_CODES":       3,
		"CONTENT_REDACTION_SECRETS":     4,
	}
)

func (x ContentRedaction) Enum() *ContentRedaction {
	p := new(ContentRedaction)
	*p = x
	return p
}

func (x ContentRedaction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContentRedaction) Descriptor() protoreflect.EnumDescriptor {
	return file_panmail_v1_system_settings_proto_enumTypes[1].Descriptor()
}

func (ContentRedaction) Type() protoreflect.EnumType {
	return &file_panmail_v1_system_settings_proto_enumTypes[1]
}

func (x ContentRedaction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContentRedaction.Descriptor instead.
func (ContentRedaction) EnumDescriptor() ([]byte, []int) {
	return file_panmail_v1_system_settings_proto_rawDescGZIP(), []int{1}
}

type GetSettingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSettingsRequest) Reset() {
	*x = GetSettingsRequest{}
	mi := &file_panmail_v1_system_settings_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSettingsRequest) ProtoMessage() {}

func (x *GetSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_panmail_v1_system_settings_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSettingsRequest.ProtoReflect.Descriptor instead.
func (*GetSettingsRequest) Descriptor() ([]byte, []int) {
	return file_panmail_v1_system_settings_proto_rawDescGZIP(), []int{0}
}

type GetSettingsResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Settings *SystemSettings        `protobuf:"bytes,1,opt,name=settings,proto3" json:"settings,omitempty"`
	// How this process is accepting SMTP submissions. Read-only: it reports
	// process state, not configuration, and UpdateSettings does not accept it.
	SmtpSubmission *SmtpSubmission `protobuf:"bytes,2,opt,name=smtp_submission,json=smtpSubmission,proto3" json:"smtp_submission,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetSettingsResponse) Reset() {
	*x = GetSettingsResponse{}
	mi := &file_panmail_v1_system_settings_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSettingsResponse) ProtoMessage() {}

func (x *GetSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_panmail_v1_system_settings_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSettingsResponse.ProtoReflect.Descriptor instead.
func (*GetSettingsResponse) Descriptor() ([]byte, []int) {
	return file_panmail_v1_system_settings_proto_rawDescGZIP(), []int{1}
}

func (x *GetSettingsResponse) GetSettings() *SystemSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *GetSettingsResponse) GetSmtpSubmission() *SmtpSubmission {
	if x != nil {
		return x.SmtpSubmission
	}
	return nil
}

type UpdateSettingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Settings      *SystemSettings        `protobuf:"bytes,1,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSettingsRequest) Reset() {
	*x = UpdateSettingsRequest{}
	mi := &file_panmail_v1_system_settings_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSettingsRequest) ProtoMessage() {}

func (x *UpdateSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_panmail_v1_system_settings_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSettingsRequest.ProtoReflect.Descriptor instead.
func (*UpdateSettingsRequest) Descriptor() ([]byte, []int) {
	return file_panmail_v1_system_settings_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateSettingsRequest) GetSettings() *SystemSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

type UpdateSettingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Settings      *SystemSettings        `protobuf:"bytes,1,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSettingsResponse) Reset() {
	*x = UpdateSettingsResponse{}
	mi := &file_panmail_v1_system_settings_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSettingsResponse) ProtoMessage() {}

func (x *UpdateSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_panmail_v1_system_settings_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSettingsResponse.ProtoReflect.Descriptor instead.
func (*UpdateSettingsResponse) Descriptor() ([]byte, []int) {
	return file_panmail_v1_system_settings_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateSettingsResponse) GetSettings() *SystemSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

// TlsCertificateInfo describes the stored keypair without disclosing it.
//
// Everything here is derived from the certificate, which is public by
// construction. The private key has no field in any response message, so there
// is no code path that can read one back out of the gateway.
type TlsCertificateInfo struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Subject string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	// The names this certificate is valid for, so an administrator can see
	// whether it matches the host their applications will dial.
	DnsNames  []string `protobuf:"bytes,2,rep,name=dns_names,json=dnsNames,proto3" json:"dns_names,omitempty"`
	Issuer    string   `protobuf:"bytes,3,opt,name=issuer,proto3" json:"issuer,omitempty"`
	NotBefore string   `protobuf:"bytes,4,opt,name=not_before,json=notBefore,proto3" json:"not_before,omitempty"`
	NotAfter  string   `protobuf:"bytes,5,opt,name=not_after,json=notAfter,proto3" json:"not_after,omitempty"`
	// Lowercase hex SHA-256 of the DER, the same value openssl prints. It is how
	// an operator confirms the gateway holds the certificate they meant to
	// install without the gateway having to show it.
	FingerprintSha256 string `protobuf:"bytes,6,opt,name=fingerprint_sha256,json=fingerprintSha256,proto3" json:"fingerprint_sha256,omitempty"`
	// True when not_after has passed. Stored certificates are not deleted when
	// they expire — the listener keeps serving the one it has, and saying so is
	// more useful than silently refusing to start.
	Expired       bool `protobuf:"varint,7,opt,name=expired,proto3" json:"expired,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TlsCertificateInfo) Reset() {
	*x = TlsCertificateInfo{}
	mi := &file_panmail_v1_system_settings_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TlsCertificateInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TlsCertificateInfo) ProtoMessage() {}

func (x *TlsCertificateInfo) ProtoReflect() protoreflect.Message {
	mi := &file_panmail_v1_system_settings_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TlsCertificateInfo.ProtoReflect.Descriptor instead.
func (*TlsCertificateInfo) Descriptor() ([]byte, []int) {
	return file_panmail_v1_system_settings_proto_rawDescGZIP(), []int{4}
}

func (x *TlsCertificateInfo) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *TlsCertificateInfo) GetDnsNames() []string {
	if x != nil {
		return x.DnsNames
	}
	return nil
}

func (x *TlsCertificateInfo) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *TlsCertificateInfo) GetNotBefore() string {
	if x != nil {
		return x.NotBefore
	}
	return ""
}

func (x *TlsCertificateInfo) GetNotAfter() string {
	if x != nil {
		return x.NotAfter
	}
	return ""
}

func (x *TlsCertificateInfo) GetFingerprintSha256() string {
	if x != nil {
		return x.FingerprintSha256
	}
	return ""
}

func (x *TlsCertificateInfo) GetExpired() bool {
	if x != nil {
		return x.Expired
	}
	return false
}

// SmtpSubmission reports the SMTP submission listener, so the dashboard can
// show an integrator real connection details instead of guessing at them.
//
// It is deliberately not part of SystemSettings. SystemSettings is readable by
// any authenticated caller, and this message is adjacent to key material;
// keeping them apart means a widening of that read can never reach the
// listener's configuration by accident.
type SmtpSubmission struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether submission is turned on. This is the setting, not proof of a live
	// socket: a listener that was enabled but could not bind reports enabled with
	// last_error set, because a form needs to show the administrator the state
	// they asked for alongside the reason it did not take.
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// The hostname clients should connect to, empty when the listener binds
	// every interface. A wildcard bind gives no hostname worth reporting, and
	// inventing one would send integrators somewhere that does not answer; the
	// dashboard falls back to the host in base_url and says what it did.
	Host string `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port int32  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	// Whether the listener offers STARTTLS.
	Starttls bool `protobuf:"varint,4,opt,name=starttls,proto3" json:"starttls,omitempty"`
	// Whether AUTH is accepted on an unencrypted connection. True means an API
	// key can cross the network in the clear, which is a deployment decision
	// worth showing rather than burying in a log line at startup.
	InsecureAuthAllowed bool `protobuf:"varint,5,opt,name=insecure_auth_allowed,json=insecureAuthAllowed,proto3" json:"insecure_auth_allowed,omitempty"`
	// True when this process was started with --smtp-addr. Flags win over the
	// stored configuration, so an existing deployment keeps behaving exactly as
	// it did, and the dashboard renders read-only rather than offering an edit
	// that would be ignored.
	ManagedByFlags bool `protobuf:"varint,6,opt,name=managed_by_flags,json=managedByFlags,proto3" json:"managed_by_flags,omitempty"`
	// Whether UpdateSmtpSubmission would be accepted. False also when no
	// encryption key is configured, because a TLS private key must never be
	// stored in the clear.
	Editable bool `protobuf:"varint,7,opt,name=editable,proto3" json:"editable,omitempty"`
	// Why editable is false, in words meant for an administrator. Empty when
	// editable is true.
	NotEditableReason string        `protobuf:"bytes,8,opt,name=not_editable_reason,json=notEditableReason,proto3" json:"not_editable_reason,omitempty"`
	BindScope         SmtpBindScope `protobuf:"varint,9,opt,name=bind_scope,json=bindScope,proto3,enum=panmail.v1.SmtpBindScope" json:"bind_scope,omitempty"`
	// The stored keypair, absent when none is stored.
	Certificate *TlsCertificateInfo `protobuf:"bytes,10,opt,name=certificate,proto3" json:"certificate,omitempty"`
	// Why the listener is not running despite being enabled — a port already in
	// use, or a bind refused. Empty when the desired and actual states agree.
	//
	// This exists because enabling now happens at runtime: at startup a listener
	// that would not bind was fatal, so the two could not disagree. A toggle in a
	// form cannot take the process down, so the failure has to be reportable.
	LastError     string `protobuf:"bytes,11,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SmtpSubmission) Reset() {
	*x = SmtpSubmission{}
	mi := &file_panmail_v1_system_settings_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SmtpSubmission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SmtpSubmission) ProtoMessage() {}

func (x *SmtpSubmission) ProtoReflect() protoreflect.Message {
	mi := &file_panmail_v1_system_settings_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SmtpSubmission.ProtoReflect.Descriptor instead.
func (*SmtpSubmission) Descriptor() ([]byte, []int) {
	return file_panmail_v1_system_settings_proto_rawDescGZIP(), []int{5}
}

func (x *SmtpSubmission) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *SmtpSubmission) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *SmtpSubmission) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *SmtpSubmission) GetStarttls() bool {
	if x != nil {
		return x.Starttls
	}
	return false
}

func (x *SmtpSubmission) GetInsecureAuthAllowed() bool {
	if x != nil {
		return x.InsecureAuthAllowed
	}
	return false
}

func (x *SmtpSubmission) GetManagedByFlags() bool {
	if x != nil {
		return x.ManagedByFlags
	}
	return false
}

func (x *SmtpSubmission) GetEditable() bool {
	if x != nil {
		return x.Editable
	}
	return false
}

func (x *SmtpSubmission) GetNotEditableReason() string {
	if x != nil {
		return x.NotEditableReason
	}
	return ""
}

func (x *SmtpSubmission) GetBindScope() SmtpBindScope {
	if x != nil {
		return x.BindScope
	}
	return SmtpBindScope_SMTP_BIND_SCOPE_UNSPECIFIED
}

func (x *SmtpSubmission) GetCertificate() *TlsCertificateInfo {
	if x != nil {
		return x.Certificate
	}
	return nil
}

func (x *SmtpSubmission) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

// SmtpSubmissionConfig is the desired state of the listener.
//
// The TLS fields are write-only: they are accepted here and never returned by
// any read. Omitting both leaves whatever is already stored in place, so an
// administrator can change the port without re-pasting a private key.
type SmtpSubmissionConfig struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Enabled   bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	BindScope SmtpBindScope          `protobuf:"varint,2,opt,name=bind_scope,json=bindScope,proto3,enum=panmail.v1.SmtpBindScope" json:"bind_scope,omitempty"`
	// The listen port. Submission ports are 587 (STARTTLS) and 2525; 25 is
	// refused, because it is the port a mail exchanger answers on and this
	// gateway is not one — binding it invites relay expectations it will not
	// meet.
	Port int32 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	// PEM, including any intermediates. Both TLS fields must be sent together.
	TlsCertificatePem string `protobuf:"bytes,4,opt,name=tls_certificate_pem,json=tlsCertificatePem,proto3" json:"tls_certificate_pem,omitempty"`
	// PEM. Encrypted with the gateway's data key before it is stored, and never
	// read back.
	TlsPrivateKeyPem string `protobuf:"bytes,5,opt,name=tls_private_key_pem,json=tlsPrivateKeyPem,proto3" json:"tls_private_key_pem,omitempty"`
	// Permit AUTH over an unencrypted connection. Honoured only when bind_scope
	// is LOOPBACK; on any other scope the request is refused rather than
	// downgraded, because the SMTP password is an API key and this field decides
	// whether it crosses a network in the clear.
	AllowInsecureAuth bool `protobuf:"varint,6,opt,name=allow_insecure_auth,json=allowInsecureAuth,proto3" json:"allow_insecure_auth,omitempty"`
	// Discard the stored keypair. Separate from sending empty PEM fields, which
	// means "leave it alone" — the two are opposite instructions and an empty
	// string cannot express both.
	ClearTls      bool `protobuf:"varint,7,opt,name=clear_tls,json=clearTls,proto3" json:"clear_tls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SmtpSubmissionConfig) Reset() {
	*x = SmtpSubmissionConfig{}
	mi := &file_panmail_v1_system_settings_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SmtpSubmissionConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SmtpSubmissionConfig) ProtoMessage() {}

func (x *SmtpSubmissionConfig) ProtoReflect() protoreflect.Message {
	mi := &file_panmail_v1_system_settings_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SmtpSubmissionConfig.ProtoReflect.Descriptor instead.
func (*SmtpSubmissionConfig) Descriptor() ([]byte, []int) {
	return file_panmail_v1_system_settings_proto_rawDescGZIP(), []int{6}
}

func (x *SmtpSubmissionConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *SmtpSubmissionConfig) GetBindScope() SmtpBindScope {
	if x != nil {
		return x.BindScope
	}
	return SmtpBindScope_SMTP_BIND_SCOPE_UNSPECIFIED
}

func (x *SmtpSubmissionConfig) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *SmtpSubmissionConfig) GetTlsCertificatePem() string {
	if x != nil {
		return x.TlsCertificatePem
	}
	return ""
}

func (x *SmtpSubmissionConfig) GetTlsPrivateKeyPem() string {
	if x != nil {
		return x.TlsPrivateKeyPem
	}
	return ""
}

func (x *SmtpSubmissionConfig) GetAllowInsecureAuth() bool {
	if x != nil {
		return x.AllowInsecureAuth
	}
	return false
}

func (x *SmtpSubmissionConfig) GetClearTls() bool {
	if x != nil {
		return x.ClearTls
	}
	return false
}

type UpdateSmtpSubmissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *SmtpSubmissionConfig  `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSmtpSubmissionRequest) Reset() {
	*x = UpdateSmtpSubmissionRequest{}
	mi := &file_panmail_v1_system_settings_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSmtpSubmissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSmtpSubmissionRequest) ProtoMessage() {}

func (x *UpdateSmtpSubmissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_panmail_v1_system_settings_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSmtpSubmissionRequest.ProtoReflect.Descriptor instead.
func (*UpdateSmtpSubmissionRequest) Descriptor() ([]byte, []int) {
	return file_panmail_v1_system_settings_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateSmtpSubmissionRequest) GetConfig() *SmtpSubmissionConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type UpdateSmtpSubmissionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The listener as it now stands, read back from the supervisor rather than
	// echoed from the request, so a change that was stored but could not be
	// bound reports last_error instead of a success the caller cannot see.
	SmtpSubmission *SmtpSubmission `protobuf:"bytes,1,opt,name=smtp_submission,json=smtpSubmission,proto3" json:"smtp_submission,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateSmtpSubmissionResponse) Reset() {
	*x = UpdateSmtpSubmissionResponse{}
	mi := &file_panmail_v1_system_settings_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSmtpSubmissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSmtpSubmissionResponse) ProtoMessage() {}

func (x *UpdateSmtpSubmissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_panmail_v1_system_settings_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSmtpSubmissionResponse.ProtoReflect.Descriptor instead.
func (*UpdateSmtpSubmissionResponse) Descriptor() ([]byte, []int) {
	return file_panmail_v1_system_settings_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateSmtpSubmissionResponse) GetSmtpSubmission() *SmtpSubmission {
	if x != nil {
		return x.SmtpSubmission
	}
	return nil
}

// SystemSettings holds the global, admin-editable configuration.
//
// Every *_retention_days field is a whole number of days, and zero always
// means "keep forever" — a retention nobody has configured must never delete
// anything. The UI says so on each field; do not add a field whose zero value
// means something else.
// **Every scalar here is `optional`, and that is load bearing.** An update
// applies only the fields it carries; one that omits a field leaves it alone.
//
// It used to be full-replace, which meant a caller changing base_url reset all
// seven retention policies to zero — and zero means keep forever, so retention
// silently stopped without an error, a log line, or anything to notice before a
// disk filled. Presence is what tells "keep forever" from "I did not mention
// it", and those are opposite instructions that a plain proto3 scalar renders
// identically.
//
// retry_pattern is the exception, because a repeated field has no presence: an
// empty list means "leave it alone" rather than "clear it". Send the values to
// change it. Nothing is lost — an empty stored pattern already reads back as
// the built-in default, so the default is expressible by sending it.
type SystemSettings struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	BaseUrl          *string                `protobuf:"bytes,1,opt,name=base_url,json=baseUrl,proto3,oneof" json:"base_url,omitempty"`
	LogRetentionDays *int32                 `protobuf:"varint,2,opt,name=log_retention_days,json=logRetentionDays,proto3,oneof" json:"log_retention_days,omitempty"`
	RetryPattern     []string               `protobuf:"bytes,3,rep,name=retry_pattern,json=retryPattern,proto3" json:"retry_pattern,omitempty"`
	// Message bodies and attachments, deleted outright rather than archived:
	// an archive of the content is the content, so archiving it would defeat
	// the retention it is meant to enforce.
	MessageRetentionDays *int32 `protobuf:"varint,4,opt,name=message_retention_days,json=messageRetentionDays,proto3,oneof" json:"message_retention_days,omitempty"`
	// Permanently failed outbox rows. Only FAILED qualifies — pending,
	// deferred and claimed rows are live work.
	OutboxRetentionDays *int32 `protobuf:"varint,5,opt,name=outbox_retention_days,json=outboxRetentionDays,proto3,oneof" json:"outbox_retention_days,omitempty"`
	// Delivered and permanently failed webhook notifications.
	WebhookRetentionDays *int32 `protobuf:"varint,6,opt,name=webhook_retention_days,json=webhookRetentionDays,proto3,oneof" json:"webhook_retention_days,omitempty"`
	// Application logs from the Pebble log store.
	AppLogRetentionDays *int32 `protobuf:"varint,7,opt,name=app_log_retention_days,json=appLogRetentionDays,proto3,oneof" json:"app_log_retention_days,omitempty"`
	// Received mail. Deleting inbound mail destroys the only copy panmail
	// holds, so this defaults to keeping it forever.
	InboundRetentionDays *int32 `protobuf:"varint,8,opt,name=inbound_retention_days,json=inboundRetentionDays,proto3,oneof" json:"inbound_retention_days,omitempty"`
	// The JSONL archives written when delivery events expire. This is the
	// escape hatch for log_retention_days, so it also defaults to forever.
	ArchiveRetentionDays *int32 `protobuf:"varint,9,opt,name=archive_retention_days,json=archiveRetentionDays,proto3,oneof" json:"archive_retention_days,omitempty"`
	// How long a message a filter rule held waits for a reviewer.
	//
	// Applies to messages held from now on, not to ones already waiting. Their
	// deadline was stamped when they were held and sent to webhook subscribers
	// in the mail.held event; moving it afterwards would break a date this
	// gateway already promised.
	QuarantineRetentionDays *int32 `protobuf:"varint,10,opt,name=quarantine_retention_days,json=quarantineRetentionDays,proto3,oneof" json:"quarantine_retention_days,omitempty"`
	// How much of a stored message body the delivery-details view is allowed to
	// show. Transactional mail carries the things it carries — a password reset
	// sends a password — and anyone who can open the dashboard can read it back
	// months later.
	//
	// Redaction happens in the gateway, not the browser: the body is served over
	// the API, so masking it in the UI would leave the secret in the response for
	// anyone who opens the network tab. Stored mail is never rewritten; only what
	// leaves through the API is masked.
	ContentRedaction ContentRedaction `protobuf:"varint,11,opt,name=content_redaction,json=contentRedaction,proto3,enum=panmail.v1.ContentRedaction" json:"content_redaction,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SystemSettings) Reset() {
	*x = SystemSettings{}
	mi := &file_panmail_v1_system_settings_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemSettings) ProtoMessage() {}

func (x *SystemSettings) ProtoReflect() protoreflect.Message {
	mi := &file_panmail_v1_system_settings_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemSettings.ProtoReflect.Descriptor instead.
func (*SystemSettings) Descriptor() ([]byte, []int) {
	return file_panmail_v1_system_settings_proto_rawDescGZIP(), []int{9}
}

func (x *SystemSettings) GetBaseUrl() string {
	if x != nil && x.BaseUrl != nil {
		return *x.BaseUrl
	}
	return ""
}

func (x *SystemSettings) GetLogRetentionDays() int32 {
	if x != nil && x.LogRetentionDays != nil {
		return *x.LogRetentionDays
	}
	return 0
}

func (x *SystemSettings) GetRetryPattern() []string {
	if x != nil {
		return x.RetryPattern
	}
	return nil
}

func (x *SystemSettings) GetMessageRetentionDays() int32 {
	if x != nil && x.MessageRetentionDays != nil {
		return *x.MessageRetentionDays
	}
	return 0
}

func (x *SystemSettings) GetOutboxRetentionDays() int32 {
	if x != nil && x.OutboxRetentionDays != nil {
		return *x.OutboxRetentionDays
	}
	return 0
}

func (x *SystemSettings) GetWebhookRetentionDays() int32 {
	if x != nil && x.WebhookRetentionDays != nil {
		return *x.WebhookRetentionDays
	}
	return 0
}

func (x *SystemSettings) GetAppLogRetentionDays() int32 {
	if x != nil && x.AppLogRetentionDays != nil {
		return *x.AppLogRetentionDays
	}
	return 0
}

func (x *SystemSettings) GetInboundRetentionDays() int32 {
	if x != nil && x.InboundRetentionDays != nil {
		return *x.InboundRetentionDays
	}
	return 0
}

func (x *SystemSettings) GetArchiveRetentionDays() int32 {
	if x != nil && x.ArchiveRetentionDays != nil {
		return *x.ArchiveRetentionDays
	}
	return 0
}

func (x *SystemSettings) GetQuarantineRetentionDays() int32 {
	if x != nil && x.QuarantineRetentionDays != nil {
		return *x.QuarantineRetentionDays
	}
	return 0
}

func (x *SystemSettings) GetContentRedaction() ContentRedaction {
	if x != nil {
		return x.ContentRedaction
	}
	return ContentRedaction_CONTENT_REDACTION_UNSPECIFIED
}

var File_panmail_v1_system_settings_proto protoreflect.FileDescriptor

const file_panmail_v1_system_settings_proto_rawDesc = "" +
	"\n" +
	" panmail/v1/system_settings.proto\x12\n" +
	"panmail.v1\"\x14\n" +
	"\x12GetSettingsRequest\"\x92\x01\n" +
	"\x13GetSettingsResponse\x126\n" +
	"\bsettings\x18\x01 \x01(\v2\x1a.panmail.v1.SystemSettingsR\bsettings\x12C\n" +
	"\x0fsmtp_submission\x18\x02 \x01(\v2\x1a.panmail.v1.SmtpSubmissionR\x0esmtpSubmission\"O\n" +
	"\x15UpdateSettingsRequest\x126\n" +
	"\bsettings\x18\x01 \x01(\v2\x1a.panmail.v1.SystemSettingsR\bsettings\"P\n" +
	"\x16UpdateSettingsResponse\x126\n" +
	"\bsettings\x18\x01 \x01(\v2\x1a.panmail.v1.SystemSettingsR\bsettings\"\xe8\x01\n" +
	"\x12TlsCertificateInfo\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x1b\n" +
	"\tdns_names\x18\x02 \x03(\tR\bdnsNames\x12\x16\n" +
	"\x06issuer\x18\x03 \x01(\tR\x06issuer\x12\x1d\n" +
	"\n" +
	"not_before\x18\x04 \x01(\tR\tnotBefore\x12\x1b\n" +
	"\tnot_after\x18\x05 \x01(\tR\bnotAfter\x12-\n" +
	"\x12fingerprint_sha256\x18\x06 \x01(\tR\x11fingerprintSha256\x12\x18\n" +
	"\aexpired\x18\a \x01(\bR\aexpired\"\xb3\x03\n" +
	"\x0eSmtpSubmission\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12\x1a\n" +
	"\bstarttls\x18\x04 \x01(\bR\bstarttls\x122\n" +
	"\x15insecure_auth_allowed\x18\x05 \x01(\bR\x13insecureAuthAllowed\x12(\n" +
	"\x10managed_by_flags\x18\x06 \x01(\bR\x0emanagedByFlags\x12\x1a\n" +
	"\beditable\x18\a \x01(\bR\beditable\x12.\n" +
	"\x13not_editable_reason\x18\b \x01(\tR\x11notEditableReason\x128\n" +
	"\n" +
	"bind_scope\x18\t \x01(\x0e2\x19.panmail.v1.SmtpBindScopeR\tbindScope\x12@\n" +
	"\vcertificate\x18\n" +
	" \x01(\v2\x1e.panmail.v1.TlsCertificateInfoR\vcertificate\x12\x1d\n" +
	"\n" +
	"last_error\x18\v \x01(\tR\tlastError\"\xaa\x02\n" +
	"\x14SmtpSubmissionConfig\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x128\n" +
	"\n" +
	"bind_scope\x18\x02 \x01(\x0e2\x19.panmail.v1.SmtpBindScopeR\tbindScope\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12.\n" +
	"\x13tls_certificate_pem\x18\x04 \x01(\tR\x11tlsCertificatePem\x12-\n" +
	"\x13tls_private_key_pem\x18\x05 \x01(\tR\x10tlsPrivateKeyPem\x12.\n" +
	"\x13allow_insecure_auth\x18\x06 \x01(\bR\x11allowInsecureAuth\x12\x1b\n" +
	"\tclear_tls\x18\a \x01(\bR\bclearTls\"W\n" +
	"\x1bUpdateSmtpSubmissionRequest\x128\n" +
	"\x06config\x18\x01 \x01(\v2 .panmail.v1.SmtpSubmissionConfigR\x06config\"c\n" +
	"\x1cUpdateSmtpSubmissionResponse\x12C\n" +
	"\x0fsmtp_submission\x18\x01 \x01(\v2\x1a.panmail.v1.SmtpSubmissionR\x0esmtpSubmission\"\xd6\x06\n" +
	"\x0eSystemSettings\x12\x1e\n" +
	"\bbase_url\x18\x01 \x01(\tH\x00R\abaseUrl\x88\x01\x01\x121\n" +
	"\x12log_retention_days\x18\x02 \x01(\x05H\x01R\x10logRetentionDays\x88\x01\x01\x12#\n" +
	"\rretry_pattern\x18\x03 \x03(\tR\fretryPattern\x129\n" +
	"\x16message_retention_days\x18\x04 \x01(\x05H\x02R\x14messageRetentionDays\x88\x01\x01\x127\n" +
	"\x15outbox_retention_days\x18\x05 \x01(\x05H\x03R\x13outboxRetentionDays\x88\x01\x01\x129\n" +
	"\x16webhook_retention_days\x18\x06 \x01(\x05H\x04R\x14webhookRetentionDays\x88\x01\x01\x128\n" +
	"\x16app_log_retention_days\x18\a \x01(\x05H\x05R\x13appLogRetentionDays\x88\x01\x01\x129\n" +
	"\x16inbound_retention_days\x18\b \x01(\x05H\x06R\x14inboundRetentionDays\x88\x01\x01\x129\n" +
	"\x16archive_retention_days\x18\t \x01(\x05H\aR\x14archiveRetentionDays\x88\x01\x01\x12?\n" +
	"\x19quarantine_retention_days\x18\n" +
	" \x01(\x05H\bR\x17quarantineRetentionDays\x88\x01\x01\x12I\n" +
	"\x11content_redaction\x18\v \x01(\x0e2\x1c.panmail.v1.ContentRedactionR\x10contentRedactionB\v\n" +
	"\t_base_urlB\x15\n" +
	"\x13_log_retention_daysB\x19\n" +
	"\x17_message_retention_daysB\x18\n" +
	"\x16_outbox_retention_daysB\x19\n" +
	"\x17_webhook_retention_daysB\x19\n" +
	"\x17_app_log_retention_daysB\x19\n" +
	"\x17_inbound_retention_daysB\x19\n" +
	"\x17_archive_retention_daysB\x1c\n" +
	"\x1a_quarantine_retention_days*r\n" +
	"\rSmtpBindScope\x12\x1f\n" +
	"\x1bSMTP_BIND_SCOPE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18SMTP_BIND_SCOPE_LOOPBACK\x10\x01\x12\"\n" +
	"\x1eSMTP_BIND_SCOPE_ALL_INTERFACES\x10\x02*\xad\x01\n" +
	"\x10ContentRedaction\x12!\n" +
	"\x1dCONTENT_REDACTION_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15CONTENT_REDACTION_OFF\x10\x01\x12\x1f\n" +
	"\x1bCONTENT_REDACTION_PASSWORDS\x10\x02\x12\x1b\n" +
	"\x17CONTENT_REDACTION_CODES\x10\x03\x12\x1d\n" +
	"\x19CONTENT_REDACTION_SECRETS\x10\x042\xab\x02\n" +
	"\x15SystemSettingsService\x12N\n" +
	"\vGetSettings\x12\x1e.panmail.v1.GetSettingsRequest\x1a\x1f.panmail.v1.GetSettingsResponse\x12W\n" +
	"\x0eUpdateSettings\x12!.panmail.v1.UpdateSettingsRequest\x1a\".panmail.v1.UpdateSettingsResponse\x12i\n" +
	"\x14UpdateSmtpSubmission\x12'.panmail.v1.UpdateSmtpSubmissionRequest\x1a(.panmail.v1.UpdateSmtpSubmissionResponseB\xa4\x01\n" +
	"\x0ecom.panmail.v1B\x13SystemSettingsProtoP\x01Z4github.com/gsoultan/panmail/api/panmail/v1;panmailv1\xa2\x02\x03PXX\xaa\x02\n" +
	"Panmail.V1\xca\x02\n" +
	"Panmail\\V1\xe2\x02\x16Panmail\\V1\\GPBMetadata\xea\x02\vPanmail::V1b\x06proto3"

var (
	file_panmail_v1_system_settings_proto_rawDescOnce sync.Once
	file_panmail_v1_system_settings_proto_rawDescData []byte
)

func file_panmail_v1_system_settings_proto_rawDescGZIP() []byte {
	file_panmail_v1_system_settings_proto_rawDescOnce.Do(func() {
		file_panmail_v1_system_settings_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_panmail_v1_system_settings_proto_rawDesc), len(file_panmail_v1_system_settings_proto_rawDesc)))
	})
	return file_panmail_v1_system_settings_proto_rawDescData
}

var file_panmail_v1_system_settings_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_panmail_v1_system_settings_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_panmail_v1_system_settings_proto_goTypes = []any{
	(SmtpBindScope)(0),                   // 0: panmail.v1.SmtpBindScope
	(ContentRedaction)(0),                // 1: panmail.v1.ContentRedaction
	(*GetSettingsRequest)(nil),           // 2: panmail.v1.GetSettingsRequest
	(*GetSettingsResponse)(nil),          // 3: panmail.v1.GetSettingsResponse
	(*UpdateSettingsRequest)(nil),        // 4: panmail.v1.UpdateSettingsRequest
	(*UpdateSettingsResponse)(nil),       // 5: panmail.v1.UpdateSettingsResponse
	(*TlsCertificateInfo)(nil),           // 6: panmail.v1.TlsCertificateInfo
	(*SmtpSubmission)(nil),               // 7: panmail.v1.SmtpSubmission
	(*SmtpSubmissionConfig)(nil),         // 8: panmail.v1.SmtpSubmissionConfig
	(*UpdateSmtpSubmissionRequest)(nil),  // 9: panmail.v1.UpdateSmtpSubmissionRequest
	(*UpdateSmtpSubmissionResponse)(nil), // 10: panmail.v1.UpdateSmtpSubmissionResponse
	(*SystemSettings)(nil),               // 11: panmail.v1.SystemSettings
}
var file_panmail_v1_system_settings_proto_depIdxs = []int32{
	11, // 0: panmail.v1.GetSettingsResponse.settings:type_name -> panmail.v1.SystemSettings
	7,  // 1: panmail.v1.GetSettingsResponse.smtp_submission:type_name -> panmail.v1.SmtpSubmission
	11, // 2: panmail.v1.UpdateSettingsRequest.settings:type_name -> panmail.v1.SystemSettings
	11, // 3: panmail.v1.UpdateSettingsResponse.settings:type_name -> panmail.v1.SystemSettings
	0,  // 4: panmail.v1.SmtpSubmission.bind_scope:type_name -> panmail.v1.SmtpBindScope
	6,  // 5: panmail.v1.SmtpSubmission.certificate:type_name -> panmail.v1.TlsCertificateInfo
	0,  // 6: panmail.v1.SmtpSubmissionConfig.bind_scope:type_name -> panmail.v1.SmtpBindScope
	8,  // 7: panmail.v1.UpdateSmtpSubmissionRequest.config:type_name -> panmail.v1.SmtpSubmissionConfig
	7,  // 8: panmail.v1.UpdateSmtpSubmissionResponse.smtp_submission:type_name -> panmail.v1.SmtpSubmission
	1,  // 9: panmail.v1.SystemSettings.content_redaction:type_name -> panmail.v1.ContentRedaction
	2,  // 10: panmail.v1.SystemSettingsService.GetSettings:input_type -> panmail.v1.GetSettingsRequest
	4,  // 11: panmail.v1.SystemSettingsService.UpdateSettings:input_type -> panmail.v1.UpdateSettingsRequest
	9,  // 12: panmail.v1.SystemSettingsService.UpdateSmtpSubmission:input_type -> panmail.v1.UpdateSmtpSubmissionRequest
	3,  // 13: panmail.v1.SystemSettingsService.GetSettings:output_type -> panmail.v1.GetSettingsResponse
	5,  // 14: panmail.v1.SystemSettingsService.UpdateSettings:output_type -> panmail.v1.UpdateSettingsResponse
	10, // 15: panmail.v1.SystemSettingsService.UpdateSmtpSubmission:output_type -> panmail.v1.UpdateSmtpSubmissionResponse
	13, // [13:16] is the sub-list for method output_type
	10, // [10:13] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_panmail_v1_system_settings_proto_init() }
func file_panmail_v1_system_settings_proto_init() {
	if File_panmail_v1_system_settings_proto != nil {
		return
	}
	file_panmail_v1_system_settings_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_panmail_v1_system_settings_proto_rawDesc), len(file_panmail_v1_system_settings_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_panmail_v1_system_settings_proto_goTypes,
		DependencyIndexes: file_panmail_v1_system_settings_proto_depIdxs,
		EnumInfos:         file_panmail_v1_system_settings_proto_enumTypes,
		MessageInfos:      file_panmail_v1_system_settings_proto_msgTypes,
	}.Build()
	File_panmail_v1_system_settings_proto = out.File
	file_panmail_v1_system_settings_proto_goTypes = nil
	file_panmail_v1_system_settings_proto_depIdxs = nil
}
