// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: panmail/v1/system_settings.proto

package panmailv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSettingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSettingsRequest) Reset() {
	*x = GetSettingsRequest{}
	mi := &file_panmail_v1_system_settings_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSettingsRequest) ProtoMessage() {}

func (x *GetSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_panmail_v1_system_settings_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSettingsRequest.ProtoReflect.Descriptor instead.
func (*GetSettingsRequest) Descriptor() ([]byte, []int) {
	return file_panmail_v1_system_settings_proto_rawDescGZIP(), []int{0}
}

type GetSettingsResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Settings *SystemSettings        `protobuf:"bytes,1,opt,name=settings,proto3" json:"settings,omitempty"`
	// How this process is accepting SMTP submissions. Read-only: it reports
	// process state, not configuration, and UpdateSettings does not accept it.
	SmtpSubmission *SmtpSubmission `protobuf:"bytes,2,opt,name=smtp_submission,json=smtpSubmission,proto3" json:"smtp_submission,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetSettingsResponse) Reset() {
	*x = GetSettingsResponse{}
	mi := &file_panmail_v1_system_settings_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSettingsResponse) ProtoMessage() {}

func (x *GetSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_panmail_v1_system_settings_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSettingsResponse.ProtoReflect.Descriptor instead.
func (*GetSettingsResponse) Descriptor() ([]byte, []int) {
	return file_panmail_v1_system_settings_proto_rawDescGZIP(), []int{1}
}

func (x *GetSettingsResponse) GetSettings() *SystemSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *GetSettingsResponse) GetSmtpSubmission() *SmtpSubmission {
	if x != nil {
		return x.SmtpSubmission
	}
	return nil
}

type UpdateSettingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Settings      *SystemSettings        `protobuf:"bytes,1,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSettingsRequest) Reset() {
	*x = UpdateSettingsRequest{}
	mi := &file_panmail_v1_system_settings_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSettingsRequest) ProtoMessage() {}

func (x *UpdateSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_panmail_v1_system_settings_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSettingsRequest.ProtoReflect.Descriptor instead.
func (*UpdateSettingsRequest) Descriptor() ([]byte, []int) {
	return file_panmail_v1_system_settings_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateSettingsRequest) GetSettings() *SystemSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

type UpdateSettingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Settings      *SystemSettings        `protobuf:"bytes,1,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSettingsResponse) Reset() {
	*x = UpdateSettingsResponse{}
	mi := &file_panmail_v1_system_settings_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSettingsResponse) ProtoMessage() {}

func (x *UpdateSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_panmail_v1_system_settings_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSettingsResponse.ProtoReflect.Descriptor instead.
func (*UpdateSettingsResponse) Descriptor() ([]byte, []int) {
	return file_panmail_v1_system_settings_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateSettingsResponse) GetSettings() *SystemSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

// SmtpSubmission reports the SMTP submission listener, so the dashboard can
// show an integrator real connection details instead of guessing at them.
//
// It is deliberately not part of SystemSettings. The listener is configured by
// process flags and cannot be changed by an administrator at runtime, and a
// field that appears in an editable form but silently ignores edits is worse
// than one that is absent.
type SmtpSubmission struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether this process is listening for submissions at all.
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// The hostname clients should connect to, empty when the listener binds
	// every interface. A wildcard bind gives no hostname worth reporting, and
	// inventing one would send integrators somewhere that does not answer; the
	// dashboard falls back to the host in base_url and says what it did.
	Host string `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port int32  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	// Whether the listener offers STARTTLS.
	Starttls bool `protobuf:"varint,4,opt,name=starttls,proto3" json:"starttls,omitempty"`
	// Whether AUTH is accepted on an unencrypted connection. True means an API
	// key can cross the network in the clear, which is a deployment decision
	// worth showing rather than burying in a log line at startup.
	InsecureAuthAllowed bool `protobuf:"varint,5,opt,name=insecure_auth_allowed,json=insecureAuthAllowed,proto3" json:"insecure_auth_allowed,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SmtpSubmission) Reset() {
	*x = SmtpSubmission{}
	mi := &file_panmail_v1_system_settings_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SmtpSubmission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SmtpSubmission) ProtoMessage() {}

func (x *SmtpSubmission) ProtoReflect() protoreflect.Message {
	mi := &file_panmail_v1_system_settings_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SmtpSubmission.ProtoReflect.Descriptor instead.
func (*SmtpSubmission) Descriptor() ([]byte, []int) {
	return file_panmail_v1_system_settings_proto_rawDescGZIP(), []int{4}
}

func (x *SmtpSubmission) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *SmtpSubmission) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *SmtpSubmission) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *SmtpSubmission) GetStarttls() bool {
	if x != nil {
		return x.Starttls
	}
	return false
}

func (x *SmtpSubmission) GetInsecureAuthAllowed() bool {
	if x != nil {
		return x.InsecureAuthAllowed
	}
	return false
}

// SystemSettings holds the global, admin-editable configuration.
//
// Every *_retention_days field is a whole number of days, and zero always
// means "keep forever" — a retention nobody has configured must never delete
// anything. The UI says so on each field; do not add a field whose zero value
// means something else.
type SystemSettings struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	BaseUrl          string                 `protobuf:"bytes,1,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	LogRetentionDays int32                  `protobuf:"varint,2,opt,name=log_retention_days,json=logRetentionDays,proto3" json:"log_retention_days,omitempty"`
	RetryPattern     []string               `protobuf:"bytes,3,rep,name=retry_pattern,json=retryPattern,proto3" json:"retry_pattern,omitempty"`
	// Message bodies and attachments, deleted outright rather than archived:
	// an archive of the content is the content, so archiving it would defeat
	// the retention it is meant to enforce.
	MessageRetentionDays int32 `protobuf:"varint,4,opt,name=message_retention_days,json=messageRetentionDays,proto3" json:"message_retention_days,omitempty"`
	// Permanently failed outbox rows. Only FAILED qualifies — pending,
	// deferred and claimed rows are live work.
	OutboxRetentionDays int32 `protobuf:"varint,5,opt,name=outbox_retention_days,json=outboxRetentionDays,proto3" json:"outbox_retention_days,omitempty"`
	// Delivered and permanently failed webhook notifications.
	WebhookRetentionDays int32 `protobuf:"varint,6,opt,name=webhook_retention_days,json=webhookRetentionDays,proto3" json:"webhook_retention_days,omitempty"`
	// Application logs from the Pebble log store.
	AppLogRetentionDays int32 `protobuf:"varint,7,opt,name=app_log_retention_days,json=appLogRetentionDays,proto3" json:"app_log_retention_days,omitempty"`
	// Received mail. Deleting inbound mail destroys the only copy panmail
	// holds, so this defaults to keeping it forever.
	InboundRetentionDays int32 `protobuf:"varint,8,opt,name=inbound_retention_days,json=inboundRetentionDays,proto3" json:"inbound_retention_days,omitempty"`
	// The JSONL archives written when delivery events expire. This is the
	// escape hatch for log_retention_days, so it also defaults to forever.
	ArchiveRetentionDays int32 `protobuf:"varint,9,opt,name=archive_retention_days,json=archiveRetentionDays,proto3" json:"archive_retention_days,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *SystemSettings) Reset() {
	*x = SystemSettings{}
	mi := &file_panmail_v1_system_settings_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemSettings) ProtoMessage() {}

func (x *SystemSettings) ProtoReflect() protoreflect.Message {
	mi := &file_panmail_v1_system_settings_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemSettings.ProtoReflect.Descriptor instead.
func (*SystemSettings) Descriptor() ([]byte, []int) {
	return file_panmail_v1_system_settings_proto_rawDescGZIP(), []int{5}
}

func (x *SystemSettings) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *SystemSettings) GetLogRetentionDays() int32 {
	if x != nil {
		return x.LogRetentionDays
	}
	return 0
}

func (x *SystemSettings) GetRetryPattern() []string {
	if x != nil {
		return x.RetryPattern
	}
	return nil
}

func (x *SystemSettings) GetMessageRetentionDays() int32 {
	if x != nil {
		return x.MessageRetentionDays
	}
	return 0
}

func (x *SystemSettings) GetOutboxRetentionDays() int32 {
	if x != nil {
		return x.OutboxRetentionDays
	}
	return 0
}

func (x *SystemSettings) GetWebhookRetentionDays() int32 {
	if x != nil {
		return x.WebhookRetentionDays
	}
	return 0
}

func (x *SystemSettings) GetAppLogRetentionDays() int32 {
	if x != nil {
		return x.AppLogRetentionDays
	}
	return 0
}

func (x *SystemSettings) GetInboundRetentionDays() int32 {
	if x != nil {
		return x.InboundRetentionDays
	}
	return 0
}

func (x *SystemSettings) GetArchiveRetentionDays() int32 {
	if x != nil {
		return x.ArchiveRetentionDays
	}
	return 0
}

var File_panmail_v1_system_settings_proto protoreflect.FileDescriptor

const file_panmail_v1_system_settings_proto_rawDesc = "" +
	"\n" +
	" panmail/v1/system_settings.proto\x12\n" +
	"panmail.v1\"\x14\n" +
	"\x12GetSettingsRequest\"\x92\x01\n" +
	"\x13GetSettingsResponse\x126\n" +
	"\bsettings\x18\x01 \x01(\v2\x1a.panmail.v1.SystemSettingsR\bsettings\x12C\n" +
	"\x0fsmtp_submission\x18\x02 \x01(\v2\x1a.panmail.v1.SmtpSubmissionR\x0esmtpSubmission\"O\n" +
	"\x15UpdateSettingsRequest\x126\n" +
	"\bsettings\x18\x01 \x01(\v2\x1a.panmail.v1.SystemSettingsR\bsettings\"P\n" +
	"\x16UpdateSettingsResponse\x126\n" +
	"\bsettings\x18\x01 \x01(\v2\x1a.panmail.v1.SystemSettingsR\bsettings\"\xa2\x01\n" +
	"\x0eSmtpSubmission\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12\x1a\n" +
	"\bstarttls\x18\x04 \x01(\bR\bstarttls\x122\n" +
	"\x15insecure_auth_allowed\x18\x05 \x01(\bR\x13insecureAuthAllowed\"\xbf\x03\n" +
	"\x0eSystemSettings\x12\x19\n" +
	"\bbase_url\x18\x01 \x01(\tR\abaseUrl\x12,\n" +
	"\x12log_retention_days\x18\x02 \x01(\x05R\x10logRetentionDays\x12#\n" +
	"\rretry_pattern\x18\x03 \x03(\tR\fretryPattern\x124\n" +
	"\x16message_retention_days\x18\x04 \x01(\x05R\x14messageRetentionDays\x122\n" +
	"\x15outbox_retention_days\x18\x05 \x01(\x05R\x13outboxRetentionDays\x124\n" +
	"\x16webhook_retention_days\x18\x06 \x01(\x05R\x14webhookRetentionDays\x123\n" +
	"\x16app_log_retention_days\x18\a \x01(\x05R\x13appLogRetentionDays\x124\n" +
	"\x16inbound_retention_days\x18\b \x01(\x05R\x14inboundRetentionDays\x124\n" +
	"\x16archive_retention_days\x18\t \x01(\x05R\x14archiveRetentionDays2\xc0\x01\n" +
	"\x15SystemSettingsService\x12N\n" +
	"\vGetSettings\x12\x1e.panmail.v1.GetSettingsRequest\x1a\x1f.panmail.v1.GetSettingsResponse\x12W\n" +
	"\x0eUpdateSettings\x12!.panmail.v1.UpdateSettingsRequest\x1a\".panmail.v1.UpdateSettingsResponseB\xa4\x01\n" +
	"\x0ecom.panmail.v1B\x13SystemSettingsProtoP\x01Z4github.com/gsoultan/panmail/api/panmail/v1;panmailv1\xa2\x02\x03PXX\xaa\x02\n" +
	"Panmail.V1\xca\x02\n" +
	"Panmail\\V1\xe2\x02\x16Panmail\\V1\\GPBMetadata\xea\x02\vPanmail::V1b\x06proto3"

var (
	file_panmail_v1_system_settings_proto_rawDescOnce sync.Once
	file_panmail_v1_system_settings_proto_rawDescData []byte
)

func file_panmail_v1_system_settings_proto_rawDescGZIP() []byte {
	file_panmail_v1_system_settings_proto_rawDescOnce.Do(func() {
		file_panmail_v1_system_settings_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_panmail_v1_system_settings_proto_rawDesc), len(file_panmail_v1_system_settings_proto_rawDesc)))
	})
	return file_panmail_v1_system_settings_proto_rawDescData
}

var file_panmail_v1_system_settings_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_panmail_v1_system_settings_proto_goTypes = []any{
	(*GetSettingsRequest)(nil),     // 0: panmail.v1.GetSettingsRequest
	(*GetSettingsResponse)(nil),    // 1: panmail.v1.GetSettingsResponse
	(*UpdateSettingsRequest)(nil),  // 2: panmail.v1.UpdateSettingsRequest
	(*UpdateSettingsResponse)(nil), // 3: panmail.v1.UpdateSettingsResponse
	(*SmtpSubmission)(nil),         // 4: panmail.v1.SmtpSubmission
	(*SystemSettings)(nil),         // 5: panmail.v1.SystemSettings
}
var file_panmail_v1_system_settings_proto_depIdxs = []int32{
	5, // 0: panmail.v1.GetSettingsResponse.settings:type_name -> panmail.v1.SystemSettings
	4, // 1: panmail.v1.GetSettingsResponse.smtp_submission:type_name -> panmail.v1.SmtpSubmission
	5, // 2: panmail.v1.UpdateSettingsRequest.settings:type_name -> panmail.v1.SystemSettings
	5, // 3: panmail.v1.UpdateSettingsResponse.settings:type_name -> panmail.v1.SystemSettings
	0, // 4: panmail.v1.SystemSettingsService.GetSettings:input_type -> panmail.v1.GetSettingsRequest
	2, // 5: panmail.v1.SystemSettingsService.UpdateSettings:input_type -> panmail.v1.UpdateSettingsRequest
	1, // 6: panmail.v1.SystemSettingsService.GetSettings:output_type -> panmail.v1.GetSettingsResponse
	3, // 7: panmail.v1.SystemSettingsService.UpdateSettings:output_type -> panmail.v1.UpdateSettingsResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_panmail_v1_system_settings_proto_init() }
func file_panmail_v1_system_settings_proto_init() {
	if File_panmail_v1_system_settings_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_panmail_v1_system_settings_proto_rawDesc), len(file_panmail_v1_system_settings_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_panmail_v1_system_settings_proto_goTypes,
		DependencyIndexes: file_panmail_v1_system_settings_proto_depIdxs,
		MessageInfos:      file_panmail_v1_system_settings_proto_msgTypes,
	}.Build()
	File_panmail_v1_system_settings_proto = out.File
	file_panmail_v1_system_settings_proto_goTypes = nil
	file_panmail_v1_system_settings_proto_depIdxs = nil
}
