// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: panmail/v1/template_service.proto

package panmailv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	BodyHtml      string                 `protobuf:"bytes,3,opt,name=body_html,json=bodyHtml,proto3" json:"body_html,omitempty"`
	BodyText      string                 `protobuf:"bytes,4,opt,name=body_text,json=bodyText,proto3" json:"body_text,omitempty"`
	Design        string                 `protobuf:"bytes,5,opt,name=design,proto3" json:"design,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTemplateRequest) Reset() {
	*x = CreateTemplateRequest{}
	mi := &file_panmail_v1_template_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTemplateRequest) ProtoMessage() {}

func (x *CreateTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_panmail_v1_template_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTemplateRequest.ProtoReflect.Descriptor instead.
func (*CreateTemplateRequest) Descriptor() ([]byte, []int) {
	return file_panmail_v1_template_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTemplateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTemplateRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *CreateTemplateRequest) GetBodyHtml() string {
	if x != nil {
		return x.BodyHtml
	}
	return ""
}

func (x *CreateTemplateRequest) GetBodyText() string {
	if x != nil {
		return x.BodyText
	}
	return ""
}

func (x *CreateTemplateRequest) GetDesign() string {
	if x != nil {
		return x.Design
	}
	return ""
}

type CreateTemplateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Template      *Template              `protobuf:"bytes,1,opt,name=template,proto3" json:"template,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTemplateResponse) Reset() {
	*x = CreateTemplateResponse{}
	mi := &file_panmail_v1_template_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTemplateResponse) ProtoMessage() {}

func (x *CreateTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_panmail_v1_template_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTemplateResponse.ProtoReflect.Descriptor instead.
func (*CreateTemplateResponse) Descriptor() ([]byte, []int) {
	return file_panmail_v1_template_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTemplateResponse) GetTemplate() *Template {
	if x != nil {
		return x.Template
	}
	return nil
}

type GetTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTemplateRequest) Reset() {
	*x = GetTemplateRequest{}
	mi := &file_panmail_v1_template_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTemplateRequest) ProtoMessage() {}

func (x *GetTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_panmail_v1_template_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTemplateRequest.ProtoReflect.Descriptor instead.
func (*GetTemplateRequest) Descriptor() ([]byte, []int) {
	return file_panmail_v1_template_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetTemplateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetTemplateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Template      *Template              `protobuf:"bytes,1,opt,name=template,proto3" json:"template,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTemplateResponse) Reset() {
	*x = GetTemplateResponse{}
	mi := &file_panmail_v1_template_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTemplateResponse) ProtoMessage() {}

func (x *GetTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_panmail_v1_template_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTemplateResponse.ProtoReflect.Descriptor instead.
func (*GetTemplateResponse) Descriptor() ([]byte, []int) {
	return file_panmail_v1_template_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetTemplateResponse) GetTemplate() *Template {
	if x != nil {
		return x.Template
	}
	return nil
}

type ListTemplatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTemplatesRequest) Reset() {
	*x = ListTemplatesRequest{}
	mi := &file_panmail_v1_template_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTemplatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTemplatesRequest) ProtoMessage() {}

func (x *ListTemplatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_panmail_v1_template_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTemplatesRequest.ProtoReflect.Descriptor instead.
func (*ListTemplatesRequest) Descriptor() ([]byte, []int) {
	return file_panmail_v1_template_service_proto_rawDescGZIP(), []int{4}
}

func (x *ListTemplatesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListTemplatesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListTemplatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Templates     []*Template            `protobuf:"bytes,1,rep,name=templates,proto3" json:"templates,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTemplatesResponse) Reset() {
	*x = ListTemplatesResponse{}
	mi := &file_panmail_v1_template_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTemplatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTemplatesResponse) ProtoMessage() {}

func (x *ListTemplatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_panmail_v1_template_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTemplatesResponse.ProtoReflect.Descriptor instead.
func (*ListTemplatesResponse) Descriptor() ([]byte, []int) {
	return file_panmail_v1_template_service_proto_rawDescGZIP(), []int{5}
}

func (x *ListTemplatesResponse) GetTemplates() []*Template {
	if x != nil {
		return x.Templates
	}
	return nil
}

func (x *ListTemplatesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type UpdateTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Subject       string                 `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	BodyHtml      string                 `protobuf:"bytes,4,opt,name=body_html,json=bodyHtml,proto3" json:"body_html,omitempty"`
	BodyText      string                 `protobuf:"bytes,5,opt,name=body_text,json=bodyText,proto3" json:"body_text,omitempty"`
	Design        string                 `protobuf:"bytes,6,opt,name=design,proto3" json:"design,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTemplateRequest) Reset() {
	*x = UpdateTemplateRequest{}
	mi := &file_panmail_v1_template_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTemplateRequest) ProtoMessage() {}

func (x *UpdateTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_panmail_v1_template_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTemplateRequest.ProtoReflect.Descriptor instead.
func (*UpdateTemplateRequest) Descriptor() ([]byte, []int) {
	return file_panmail_v1_template_service_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateTemplateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateTemplateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateTemplateRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *UpdateTemplateRequest) GetBodyHtml() string {
	if x != nil {
		return x.BodyHtml
	}
	return ""
}

func (x *UpdateTemplateRequest) GetBodyText() string {
	if x != nil {
		return x.BodyText
	}
	return ""
}

func (x *UpdateTemplateRequest) GetDesign() string {
	if x != nil {
		return x.Design
	}
	return ""
}

type UpdateTemplateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Template      *Template              `protobuf:"bytes,1,opt,name=template,proto3" json:"template,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTemplateResponse) Reset() {
	*x = UpdateTemplateResponse{}
	mi := &file_panmail_v1_template_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTemplateResponse) ProtoMessage() {}

func (x *UpdateTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_panmail_v1_template_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTemplateResponse.ProtoReflect.Descriptor instead.
func (*UpdateTemplateResponse) Descriptor() ([]byte, []int) {
	return file_panmail_v1_template_service_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateTemplateResponse) GetTemplate() *Template {
	if x != nil {
		return x.Template
	}
	return nil
}

type DeleteTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTemplateRequest) Reset() {
	*x = DeleteTemplateRequest{}
	mi := &file_panmail_v1_template_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTemplateRequest) ProtoMessage() {}

func (x *DeleteTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_panmail_v1_template_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTemplateRequest.ProtoReflect.Descriptor instead.
func (*DeleteTemplateRequest) Descriptor() ([]byte, []int) {
	return file_panmail_v1_template_service_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteTemplateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteTemplateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTemplateResponse) Reset() {
	*x = DeleteTemplateResponse{}
	mi := &file_panmail_v1_template_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTemplateResponse) ProtoMessage() {}

func (x *DeleteTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_panmail_v1_template_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTemplateResponse.ProtoReflect.Descriptor instead.
func (*DeleteTemplateResponse) Descriptor() ([]byte, []int) {
	return file_panmail_v1_template_service_proto_rawDescGZIP(), []int{9}
}

var File_panmail_v1_template_service_proto protoreflect.FileDescriptor

const file_panmail_v1_template_service_proto_rawDesc = "" +
	"\n" +
	"!panmail/v1/template_service.proto\x12\n" +
	"panmail.v1\x1a\x19panmail/v1/template.proto\"\x97\x01\n" +
	"\x15CreateTemplateRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x1b\n" +
	"\tbody_html\x18\x03 \x01(\tR\bbodyHtml\x12\x1b\n" +
	"\tbody_text\x18\x04 \x01(\tR\bbodyText\x12\x16\n" +
	"\x06design\x18\x05 \x01(\tR\x06design\"J\n" +
	"\x16CreateTemplateResponse\x120\n" +
	"\btemplate\x18\x01 \x01(\v2\x14.panmail.v1.TemplateR\btemplate\"$\n" +
	"\x12GetTemplateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"G\n" +
	"\x13GetTemplateResponse\x120\n" +
	"\btemplate\x18\x01 \x01(\v2\x14.panmail.v1.TemplateR\btemplate\"R\n" +
	"\x14ListTemplatesRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"s\n" +
	"\x15ListTemplatesResponse\x122\n" +
	"\ttemplates\x18\x01 \x03(\v2\x14.panmail.v1.TemplateR\ttemplates\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\xa7\x01\n" +
	"\x15UpdateTemplateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\asubject\x18\x03 \x01(\tR\asubject\x12\x1b\n" +
	"\tbody_html\x18\x04 \x01(\tR\bbodyHtml\x12\x1b\n" +
	"\tbody_text\x18\x05 \x01(\tR\bbodyText\x12\x16\n" +
	"\x06design\x18\x06 \x01(\tR\x06design\"J\n" +
	"\x16UpdateTemplateResponse\x120\n" +
	"\btemplate\x18\x01 \x01(\v2\x14.panmail.v1.TemplateR\btemplate\"'\n" +
	"\x15DeleteTemplateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x18\n" +
	"\x16DeleteTemplateResponse2\xc2\x03\n" +
	"\x0fTemplateService\x12W\n" +
	"\x0eCreateTemplate\x12!.panmail.v1.CreateTemplateRequest\x1a\".panmail.v1.CreateTemplateResponse\x12N\n" +
	"\vGetTemplate\x12\x1e.panmail.v1.GetTemplateRequest\x1a\x1f.panmail.v1.GetTemplateResponse\x12T\n" +
	"\rListTemplates\x12 .panmail.v1.ListTemplatesRequest\x1a!.panmail.v1.ListTemplatesResponse\x12W\n" +
	"\x0eUpdateTemplate\x12!.panmail.v1.UpdateTemplateRequest\x1a\".panmail.v1.UpdateTemplateResponse\x12W\n" +
	"\x0eDeleteTemplate\x12!.panmail.v1.DeleteTemplateRequest\x1a\".panmail.v1.DeleteTemplateResponseB\xa5\x01\n" +
	"\x0ecom.panmail.v1B\x14TemplateServiceProtoP\x01Z4github.com/gsoultan/panmail/api/panmail/v1;panmailv1\xa2\x02\x03PXX\xaa\x02\n" +
	"Panmail.V1\xca\x02\n" +
	"Panmail\\V1\xe2\x02\x16Panmail\\V1\\GPBMetadata\xea\x02\vPanmail::V1b\x06proto3"

var (
	file_panmail_v1_template_service_proto_rawDescOnce sync.Once
	file_panmail_v1_template_service_proto_rawDescData []byte
)

func file_panmail_v1_template_service_proto_rawDescGZIP() []byte {
	file_panmail_v1_template_service_proto_rawDescOnce.Do(func() {
		file_panmail_v1_template_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_panmail_v1_template_service_proto_rawDesc), len(file_panmail_v1_template_service_proto_rawDesc)))
	})
	return file_panmail_v1_template_service_proto_rawDescData
}

var file_panmail_v1_template_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_panmail_v1_template_service_proto_goTypes = []any{
	(*CreateTemplateRequest)(nil),  // 0: panmail.v1.CreateTemplateRequest
	(*CreateTemplateResponse)(nil), // 1: panmail.v1.CreateTemplateResponse
	(*GetTemplateRequest)(nil),     // 2: panmail.v1.GetTemplateRequest
	(*GetTemplateResponse)(nil),    // 3: panmail.v1.GetTemplateResponse
	(*ListTemplatesRequest)(nil),   // 4: panmail.v1.ListTemplatesRequest
	(*ListTemplatesResponse)(nil),  // 5: panmail.v1.ListTemplatesResponse
	(*UpdateTemplateRequest)(nil),  // 6: panmail.v1.UpdateTemplateRequest
	(*UpdateTemplateResponse)(nil), // 7: panmail.v1.UpdateTemplateResponse
	(*DeleteTemplateRequest)(nil),  // 8: panmail.v1.DeleteTemplateRequest
	(*DeleteTemplateResponse)(nil), // 9: panmail.v1.DeleteTemplateResponse
	(*Template)(nil),               // 10: panmail.v1.Template
}
var file_panmail_v1_template_service_proto_depIdxs = []int32{
	10, // 0: panmail.v1.CreateTemplateResponse.template:type_name -> panmail.v1.Template
	10, // 1: panmail.v1.GetTemplateResponse.template:type_name -> panmail.v1.Template
	10, // 2: panmail.v1.ListTemplatesResponse.templates:type_name -> panmail.v1.Template
	10, // 3: panmail.v1.UpdateTemplateResponse.template:type_name -> panmail.v1.Template
	0,  // 4: panmail.v1.TemplateService.CreateTemplate:input_type -> panmail.v1.CreateTemplateRequest
	2,  // 5: panmail.v1.TemplateService.GetTemplate:input_type -> panmail.v1.GetTemplateRequest
	4,  // 6: panmail.v1.TemplateService.ListTemplates:input_type -> panmail.v1.ListTemplatesRequest
	6,  // 7: panmail.v1.TemplateService.UpdateTemplate:input_type -> panmail.v1.UpdateTemplateRequest
	8,  // 8: panmail.v1.TemplateService.DeleteTemplate:input_type -> panmail.v1.DeleteTemplateRequest
	1,  // 9: panmail.v1.TemplateService.CreateTemplate:output_type -> panmail.v1.CreateTemplateResponse
	3,  // 10: panmail.v1.TemplateService.GetTemplate:output_type -> panmail.v1.GetTemplateResponse
	5,  // 11: panmail.v1.TemplateService.ListTemplates:output_type -> panmail.v1.ListTemplatesResponse
	7,  // 12: panmail.v1.TemplateService.UpdateTemplate:output_type -> panmail.v1.UpdateTemplateResponse
	9,  // 13: panmail.v1.TemplateService.DeleteTemplate:output_type -> panmail.v1.DeleteTemplateResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_panmail_v1_template_service_proto_init() }
func file_panmail_v1_template_service_proto_init() {
	if File_panmail_v1_template_service_proto != nil {
		return
	}
	file_panmail_v1_template_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_panmail_v1_template_service_proto_rawDesc), len(file_panmail_v1_template_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_panmail_v1_template_service_proto_goTypes,
		DependencyIndexes: file_panmail_v1_template_service_proto_depIdxs,
		MessageInfos:      file_panmail_v1_template_service_proto_msgTypes,
	}.Build()
	File_panmail_v1_template_service_proto = out.File
	file_panmail_v1_template_service_proto_goTypes = nil
	file_panmail_v1_template_service_proto_depIdxs = nil
}
