// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: panmail/v1/webhook_service.proto

package panmailv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateWebhookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Events        []WebhookTriggerEvent  `protobuf:"varint,3,rep,packed,name=events,proto3,enum=panmail.v1.WebhookTriggerEvent" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWebhookRequest) Reset() {
	*x = CreateWebhookRequest{}
	mi := &file_panmail_v1_webhook_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWebhookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWebhookRequest) ProtoMessage() {}

func (x *CreateWebhookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_panmail_v1_webhook_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWebhookRequest.ProtoReflect.Descriptor instead.
func (*CreateWebhookRequest) Descriptor() ([]byte, []int) {
	return file_panmail_v1_webhook_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateWebhookRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateWebhookRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CreateWebhookRequest) GetEvents() []WebhookTriggerEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type CreateWebhookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Webhook       *Webhook               `protobuf:"bytes,1,opt,name=webhook,proto3" json:"webhook,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWebhookResponse) Reset() {
	*x = CreateWebhookResponse{}
	mi := &file_panmail_v1_webhook_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWebhookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWebhookResponse) ProtoMessage() {}

func (x *CreateWebhookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_panmail_v1_webhook_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWebhookResponse.ProtoReflect.Descriptor instead.
func (*CreateWebhookResponse) Descriptor() ([]byte, []int) {
	return file_panmail_v1_webhook_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateWebhookResponse) GetWebhook() *Webhook {
	if x != nil {
		return x.Webhook
	}
	return nil
}

type ListWebhooksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWebhooksRequest) Reset() {
	*x = ListWebhooksRequest{}
	mi := &file_panmail_v1_webhook_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWebhooksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWebhooksRequest) ProtoMessage() {}

func (x *ListWebhooksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_panmail_v1_webhook_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWebhooksRequest.ProtoReflect.Descriptor instead.
func (*ListWebhooksRequest) Descriptor() ([]byte, []int) {
	return file_panmail_v1_webhook_service_proto_rawDescGZIP(), []int{2}
}

func (x *ListWebhooksRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListWebhooksRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListWebhooksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Webhooks      []*Webhook             `protobuf:"bytes,1,rep,name=webhooks,proto3" json:"webhooks,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWebhooksResponse) Reset() {
	*x = ListWebhooksResponse{}
	mi := &file_panmail_v1_webhook_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWebhooksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWebhooksResponse) ProtoMessage() {}

func (x *ListWebhooksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_panmail_v1_webhook_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWebhooksResponse.ProtoReflect.Descriptor instead.
func (*ListWebhooksResponse) Descriptor() ([]byte, []int) {
	return file_panmail_v1_webhook_service_proto_rawDescGZIP(), []int{3}
}

func (x *ListWebhooksResponse) GetWebhooks() []*Webhook {
	if x != nil {
		return x.Webhooks
	}
	return nil
}

func (x *ListWebhooksResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type DeleteWebhookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWebhookRequest) Reset() {
	*x = DeleteWebhookRequest{}
	mi := &file_panmail_v1_webhook_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWebhookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWebhookRequest) ProtoMessage() {}

func (x *DeleteWebhookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_panmail_v1_webhook_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWebhookRequest.ProtoReflect.Descriptor instead.
func (*DeleteWebhookRequest) Descriptor() ([]byte, []int) {
	return file_panmail_v1_webhook_service_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteWebhookRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteWebhookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWebhookResponse) Reset() {
	*x = DeleteWebhookResponse{}
	mi := &file_panmail_v1_webhook_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWebhookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWebhookResponse) ProtoMessage() {}

func (x *DeleteWebhookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_panmail_v1_webhook_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWebhookResponse.ProtoReflect.Descriptor instead.
func (*DeleteWebhookResponse) Descriptor() ([]byte, []int) {
	return file_panmail_v1_webhook_service_proto_rawDescGZIP(), []int{5}
}

type UpdateWebhookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Events        []WebhookTriggerEvent  `protobuf:"varint,4,rep,packed,name=events,proto3,enum=panmail.v1.WebhookTriggerEvent" json:"events,omitempty"`
	Active        bool                   `protobuf:"varint,5,opt,name=active,proto3" json:"active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWebhookRequest) Reset() {
	*x = UpdateWebhookRequest{}
	mi := &file_panmail_v1_webhook_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWebhookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWebhookRequest) ProtoMessage() {}

func (x *UpdateWebhookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_panmail_v1_webhook_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWebhookRequest.ProtoReflect.Descriptor instead.
func (*UpdateWebhookRequest) Descriptor() ([]byte, []int) {
	return file_panmail_v1_webhook_service_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateWebhookRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateWebhookRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateWebhookRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *UpdateWebhookRequest) GetEvents() []WebhookTriggerEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *UpdateWebhookRequest) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

type UpdateWebhookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Webhook       *Webhook               `protobuf:"bytes,1,opt,name=webhook,proto3" json:"webhook,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWebhookResponse) Reset() {
	*x = UpdateWebhookResponse{}
	mi := &file_panmail_v1_webhook_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWebhookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWebhookResponse) ProtoMessage() {}

func (x *UpdateWebhookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_panmail_v1_webhook_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWebhookResponse.ProtoReflect.Descriptor instead.
func (*UpdateWebhookResponse) Descriptor() ([]byte, []int) {
	return file_panmail_v1_webhook_service_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateWebhookResponse) GetWebhook() *Webhook {
	if x != nil {
		return x.Webhook
	}
	return nil
}

var File_panmail_v1_webhook_service_proto protoreflect.FileDescriptor

const file_panmail_v1_webhook_service_proto_rawDesc = "" +
	"\n" +
	" panmail/v1/webhook_service.proto\x12\n" +
	"panmail.v1\x1a\x18panmail/v1/webhook.proto\"u\n" +
	"\x14CreateWebhookRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x127\n" +
	"\x06events\x18\x03 \x03(\x0e2\x1f.panmail.v1.WebhookTriggerEventR\x06events\"F\n" +
	"\x15CreateWebhookResponse\x12-\n" +
	"\awebhook\x18\x01 \x01(\v2\x13.panmail.v1.WebhookR\awebhook\"Q\n" +
	"\x13ListWebhooksRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"o\n" +
	"\x14ListWebhooksResponse\x12/\n" +
	"\bwebhooks\x18\x01 \x03(\v2\x13.panmail.v1.WebhookR\bwebhooks\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"&\n" +
	"\x14DeleteWebhookRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x17\n" +
	"\x15DeleteWebhookResponse\"\x9d\x01\n" +
	"\x14UpdateWebhookRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x127\n" +
	"\x06events\x18\x04 \x03(\x0e2\x1f.panmail.v1.WebhookTriggerEventR\x06events\x12\x16\n" +
	"\x06active\x18\x05 \x01(\bR\x06active\"F\n" +
	"\x15UpdateWebhookResponse\x12-\n" +
	"\awebhook\x18\x01 \x01(\v2\x13.panmail.v1.WebhookR\awebhook2\xe5\x02\n" +
	"\x0eWebhookService\x12T\n" +
	"\rCreateWebhook\x12 .panmail.v1.CreateWebhookRequest\x1a!.panmail.v1.CreateWebhookResponse\x12Q\n" +
	"\fListWebhooks\x12\x1f.panmail.v1.ListWebhooksRequest\x1a .panmail.v1.ListWebhooksResponse\x12T\n" +
	"\rDeleteWebhook\x12 .panmail.v1.DeleteWebhookRequest\x1a!.panmail.v1.DeleteWebhookResponse\x12T\n" +
	"\rUpdateWebhook\x12 .panmail.v1.UpdateWebhookRequest\x1a!.panmail.v1.UpdateWebhookResponseB\xa4\x01\n" +
	"\x0ecom.panmail.v1B\x13WebhookServiceProtoP\x01Z4github.com/gsoultan/panmail/api/panmail/v1;panmailv1\xa2\x02\x03PXX\xaa\x02\n" +
	"Panmail.V1\xca\x02\n" +
	"Panmail\\V1\xe2\x02\x16Panmail\\V1\\GPBMetadata\xea\x02\vPanmail::V1b\x06proto3"

var (
	file_panmail_v1_webhook_service_proto_rawDescOnce sync.Once
	file_panmail_v1_webhook_service_proto_rawDescData []byte
)

func file_panmail_v1_webhook_service_proto_rawDescGZIP() []byte {
	file_panmail_v1_webhook_service_proto_rawDescOnce.Do(func() {
		file_panmail_v1_webhook_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_panmail_v1_webhook_service_proto_rawDesc), len(file_panmail_v1_webhook_service_proto_rawDesc)))
	})
	return file_panmail_v1_webhook_service_proto_rawDescData
}

var file_panmail_v1_webhook_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_panmail_v1_webhook_service_proto_goTypes = []any{
	(*CreateWebhookRequest)(nil),  // 0: panmail.v1.CreateWebhookRequest
	(*CreateWebhookResponse)(nil), // 1: panmail.v1.CreateWebhookResponse
	(*ListWebhooksRequest)(nil),   // 2: panmail.v1.ListWebhooksRequest
	(*ListWebhooksResponse)(nil),  // 3: panmail.v1.ListWebhooksResponse
	(*DeleteWebhookRequest)(nil),  // 4: panmail.v1.DeleteWebhookRequest
	(*DeleteWebhookResponse)(nil), // 5: panmail.v1.DeleteWebhookResponse
	(*UpdateWebhookRequest)(nil),  // 6: panmail.v1.UpdateWebhookRequest
	(*UpdateWebhookResponse)(nil), // 7: panmail.v1.UpdateWebhookResponse
	(WebhookTriggerEvent)(0),      // 8: panmail.v1.WebhookTriggerEvent
	(*Webhook)(nil),               // 9: panmail.v1.Webhook
}
var file_panmail_v1_webhook_service_proto_depIdxs = []int32{
	8, // 0: panmail.v1.CreateWebhookRequest.events:type_name -> panmail.v1.WebhookTriggerEvent
	9, // 1: panmail.v1.CreateWebhookResponse.webhook:type_name -> panmail.v1.Webhook
	9, // 2: panmail.v1.ListWebhooksResponse.webhooks:type_name -> panmail.v1.Webhook
	8, // 3: panmail.v1.UpdateWebhookRequest.events:type_name -> panmail.v1.WebhookTriggerEvent
	9, // 4: panmail.v1.UpdateWebhookResponse.webhook:type_name -> panmail.v1.Webhook
	0, // 5: panmail.v1.WebhookService.CreateWebhook:input_type -> panmail.v1.CreateWebhookRequest
	2, // 6: panmail.v1.WebhookService.ListWebhooks:input_type -> panmail.v1.ListWebhooksRequest
	4, // 7: panmail.v1.WebhookService.DeleteWebhook:input_type -> panmail.v1.DeleteWebhookRequest
	6, // 8: panmail.v1.WebhookService.UpdateWebhook:input_type -> panmail.v1.UpdateWebhookRequest
	1, // 9: panmail.v1.WebhookService.CreateWebhook:output_type -> panmail.v1.CreateWebhookResponse
	3, // 10: panmail.v1.WebhookService.ListWebhooks:output_type -> panmail.v1.ListWebhooksResponse
	5, // 11: panmail.v1.WebhookService.DeleteWebhook:output_type -> panmail.v1.DeleteWebhookResponse
	7, // 12: panmail.v1.WebhookService.UpdateWebhook:output_type -> panmail.v1.UpdateWebhookResponse
	9, // [9:13] is the sub-list for method output_type
	5, // [5:9] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_panmail_v1_webhook_service_proto_init() }
func file_panmail_v1_webhook_service_proto_init() {
	if File_panmail_v1_webhook_service_proto != nil {
		return
	}
	file_panmail_v1_webhook_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_panmail_v1_webhook_service_proto_rawDesc), len(file_panmail_v1_webhook_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_panmail_v1_webhook_service_proto_goTypes,
		DependencyIndexes: file_panmail_v1_webhook_service_proto_depIdxs,
		MessageInfos:      file_panmail_v1_webhook_service_proto_msgTypes,
	}.Build()
	File_panmail_v1_webhook_service_proto = out.File
	file_panmail_v1_webhook_service_proto_goTypes = nil
	file_panmail_v1_webhook_service_proto_depIdxs = nil
}
