// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: panmail/v1/webhook.proto

package panmailv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WebhookTriggerEvent int32

const (
	WebhookTriggerEvent_WEBHOOK_TRIGGER_EVENT_UNSPECIFIED    WebhookTriggerEvent = 0
	WebhookTriggerEvent_WEBHOOK_TRIGGER_EVENT_MAIL_SENT      WebhookTriggerEvent = 1
	WebhookTriggerEvent_WEBHOOK_TRIGGER_EVENT_MAIL_DELIVERED WebhookTriggerEvent = 2
	WebhookTriggerEvent_WEBHOOK_TRIGGER_EVENT_MAIL_OPENED    WebhookTriggerEvent = 3
	WebhookTriggerEvent_WEBHOOK_TRIGGER_EVENT_MAIL_CLICKED   WebhookTriggerEvent = 4
	WebhookTriggerEvent_WEBHOOK_TRIGGER_EVENT_MAIL_BOUNCED   WebhookTriggerEvent = 5
	WebhookTriggerEvent_WEBHOOK_TRIGGER_EVENT_MAIL_REJECTED  WebhookTriggerEvent = 6
	WebhookTriggerEvent_WEBHOOK_TRIGGER_EVENT_MAIL_INBOUND   WebhookTriggerEvent = 7
)

// Enum value maps for WebhookTriggerEvent.
var (
	WebhookTriggerEvent_name = map[int32]string{
		0: "WEBHOOK_TRIGGER_EVENT_UNSPECIFIED",
		1: "WEBHOOK_TRIGGER_EVENT_MAIL_SENT",
		2: "WEBHOOK_TRIGGER_EVENT_MAIL_DELIVERED",
		3: "WEBHOOK_TRIGGER_EVENT_MAIL_OPENED",
		4: "WEBHOOK_TRIGGER_EVENT_MAIL_CLICKED",
		5: "WEBHOOK_TRIGGER_EVENT_MAIL_BOUNCED",
		6: "WEBHOOK_TRIGGER_EVENT_MAIL_REJECTED",
		7: "WEBHOOK_TRIGGER_EVENT_MAIL_INBOUND",
	}
	WebhookTriggerEvent_value = map[string]int32{
		"WEBHOOK_TRIGGER_EVENT_UNSPECIFIED":    0,
		"WEBHOOK_TRIGGER_EVENT_MAIL_SENT":      1,
		"WEBHOOK_TRIGGER_EVENT_MAIL_DELIVERED": 2,
		"WEBHOOK_TRIGGER_EVENT_MAIL_OPENED":    3,
		"WEBHOOK_TRIGGER_EVENT_MAIL_CLICKED":   4,
		"WEBHOOK_TRIGGER_EVENT_MAIL_BOUNCED":   5,
		"WEBHOOK_TRIGGER_EVENT_MAIL_REJECTED":  6,
		"WEBHOOK_TRIGGER_EVENT_MAIL_INBOUND":   7,
	}
)

func (x WebhookTriggerEvent) Enum() *WebhookTriggerEvent {
	p := new(WebhookTriggerEvent)
	*p = x
	return p
}

func (x WebhookTriggerEvent) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WebhookTriggerEvent) Descriptor() protoreflect.EnumDescriptor {
	return file_panmail_v1_webhook_proto_enumTypes[0].Descriptor()
}

func (WebhookTriggerEvent) Type() protoreflect.EnumType {
	return &file_panmail_v1_webhook_proto_enumTypes[0]
}

func (x WebhookTriggerEvent) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WebhookTriggerEvent.Descriptor instead.
func (WebhookTriggerEvent) EnumDescriptor() ([]byte, []int) {
	return file_panmail_v1_webhook_proto_rawDescGZIP(), []int{0}
}

type Webhook struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Url           string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	Events        []WebhookTriggerEvent  `protobuf:"varint,5,rep,packed,name=events,proto3,enum=panmail.v1.WebhookTriggerEvent" json:"events,omitempty"`
	Active        bool                   `protobuf:"varint,6,opt,name=active,proto3" json:"active,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Webhook) Reset() {
	*x = Webhook{}
	mi := &file_panmail_v1_webhook_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Webhook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Webhook) ProtoMessage() {}

func (x *Webhook) ProtoReflect() protoreflect.Message {
	mi := &file_panmail_v1_webhook_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Webhook.ProtoReflect.Descriptor instead.
func (*Webhook) Descriptor() ([]byte, []int) {
	return file_panmail_v1_webhook_proto_rawDescGZIP(), []int{0}
}

func (x *Webhook) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Webhook) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Webhook) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Webhook) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Webhook) GetEvents() []WebhookTriggerEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *Webhook) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *Webhook) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_panmail_v1_webhook_proto protoreflect.FileDescriptor

const file_panmail_v1_webhook_proto_rawDesc = "" +
	"\n" +
	"\x18panmail/v1/webhook.proto\x12\n" +
	"panmail.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe8\x01\n" +
	"\aWebhook\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\x127\n" +
	"\x06events\x18\x05 \x03(\x0e2\x1f.panmail.v1.WebhookTriggerEventR\x06events\x12\x16\n" +
	"\x06active\x18\x06 \x01(\bR\x06active\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt*\xd3\x02\n" +
	"\x13WebhookTriggerEvent\x12%\n" +
	"!WEBHOOK_TRIGGER_EVENT_UNSPECIFIED\x10\x00\x12#\n" +
	"\x1fWEBHOOK_TRIGGER_EVENT_MAIL_SENT\x10\x01\x12(\n" +
	"$WEBHOOK_TRIGGER_EVENT_MAIL_DELIVERED\x10\x02\x12%\n" +
	"!WEBHOOK_TRIGGER_EVENT_MAIL_OPENED\x10\x03\x12&\n" +
	"\"WEBHOOK_TRIGGER_EVENT_MAIL_CLICKED\x10\x04\x12&\n" +
	"\"WEBHOOK_TRIGGER_EVENT_MAIL_BOUNCED\x10\x05\x12'\n" +
	"#WEBHOOK_TRIGGER_EVENT_MAIL_REJECTED\x10\x06\x12&\n" +
	"\"WEBHOOK_TRIGGER_EVENT_MAIL_INBOUND\x10\aB\x9d\x01\n" +
	"\x0ecom.panmail.v1B\fWebhookProtoP\x01Z4github.com/gsoultan/panmail/api/panmail/v1;panmailv1\xa2\x02\x03PXX\xaa\x02\n" +
	"Panmail.V1\xca\x02\n" +
	"Panmail\\V1\xe2\x02\x16Panmail\\V1\\GPBMetadata\xea\x02\vPanmail::V1b\x06proto3"

var (
	file_panmail_v1_webhook_proto_rawDescOnce sync.Once
	file_panmail_v1_webhook_proto_rawDescData []byte
)

func file_panmail_v1_webhook_proto_rawDescGZIP() []byte {
	file_panmail_v1_webhook_proto_rawDescOnce.Do(func() {
		file_panmail_v1_webhook_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_panmail_v1_webhook_proto_rawDesc), len(file_panmail_v1_webhook_proto_rawDesc)))
	})
	return file_panmail_v1_webhook_proto_rawDescData
}

var file_panmail_v1_webhook_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_panmail_v1_webhook_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_panmail_v1_webhook_proto_goTypes = []any{
	(WebhookTriggerEvent)(0),      // 0: panmail.v1.WebhookTriggerEvent
	(*Webhook)(nil),               // 1: panmail.v1.Webhook
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_panmail_v1_webhook_proto_depIdxs = []int32{
	0, // 0: panmail.v1.Webhook.events:type_name -> panmail.v1.WebhookTriggerEvent
	2, // 1: panmail.v1.Webhook.created_at:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_panmail_v1_webhook_proto_init() }
func file_panmail_v1_webhook_proto_init() {
	if File_panmail_v1_webhook_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_panmail_v1_webhook_proto_rawDesc), len(file_panmail_v1_webhook_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_panmail_v1_webhook_proto_goTypes,
		DependencyIndexes: file_panmail_v1_webhook_proto_depIdxs,
		EnumInfos:         file_panmail_v1_webhook_proto_enumTypes,
		MessageInfos:      file_panmail_v1_webhook_proto_msgTypes,
	}.Build()
	File_panmail_v1_webhook_proto = out.File
	file_panmail_v1_webhook_proto_goTypes = nil
	file_panmail_v1_webhook_proto_depIdxs = nil
}
