// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: panmail/v1/email_filter_service.proto

package panmailv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/gsoultan/panmail/api/panmail/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// EmailFilterServiceName is the fully-qualified name of the EmailFilterService service.
	EmailFilterServiceName = "panmail.v1.EmailFilterService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// EmailFilterServiceListFilterRulesProcedure is the fully-qualified name of the
	// EmailFilterService's ListFilterRules RPC.
	EmailFilterServiceListFilterRulesProcedure = "/panmail.v1.EmailFilterService/ListFilterRules"
	// EmailFilterServiceCreateFilterRuleProcedure is the fully-qualified name of the
	// EmailFilterService's CreateFilterRule RPC.
	EmailFilterServiceCreateFilterRuleProcedure = "/panmail.v1.EmailFilterService/CreateFilterRule"
	// EmailFilterServiceUpdateFilterRuleProcedure is the fully-qualified name of the
	// EmailFilterService's UpdateFilterRule RPC.
	EmailFilterServiceUpdateFilterRuleProcedure = "/panmail.v1.EmailFilterService/UpdateFilterRule"
	// EmailFilterServiceDeleteFilterRuleProcedure is the fully-qualified name of the
	// EmailFilterService's DeleteFilterRule RPC.
	EmailFilterServiceDeleteFilterRuleProcedure = "/panmail.v1.EmailFilterService/DeleteFilterRule"
	// EmailFilterServiceListFilteredMessagesProcedure is the fully-qualified name of the
	// EmailFilterService's ListFilteredMessages RPC.
	EmailFilterServiceListFilteredMessagesProcedure = "/panmail.v1.EmailFilterService/ListFilteredMessages"
	// EmailFilterServiceGetFilteredMessageProcedure is the fully-qualified name of the
	// EmailFilterService's GetFilteredMessage RPC.
	EmailFilterServiceGetFilteredMessageProcedure = "/panmail.v1.EmailFilterService/GetFilteredMessage"
	// EmailFilterServiceReleaseFilteredMessageProcedure is the fully-qualified name of the
	// EmailFilterService's ReleaseFilteredMessage RPC.
	EmailFilterServiceReleaseFilteredMessageProcedure = "/panmail.v1.EmailFilterService/ReleaseFilteredMessage"
	// EmailFilterServiceRejectFilteredMessageProcedure is the fully-qualified name of the
	// EmailFilterService's RejectFilteredMessage RPC.
	EmailFilterServiceRejectFilteredMessageProcedure = "/panmail.v1.EmailFilterService/RejectFilteredMessage"
)

// EmailFilterServiceClient is a client for the panmail.v1.EmailFilterService service.
type EmailFilterServiceClient interface {
	ListFilterRules(context.Context, *connect.Request[v1.ListFilterRulesRequest]) (*connect.Response[v1.ListFilterRulesResponse], error)
	CreateFilterRule(context.Context, *connect.Request[v1.CreateFilterRuleRequest]) (*connect.Response[v1.CreateFilterRuleResponse], error)
	UpdateFilterRule(context.Context, *connect.Request[v1.UpdateFilterRuleRequest]) (*connect.Response[v1.UpdateFilterRuleResponse], error)
	DeleteFilterRule(context.Context, *connect.Request[v1.DeleteFilterRuleRequest]) (*connect.Response[v1.DeleteFilterRuleResponse], error)
	ListFilteredMessages(context.Context, *connect.Request[v1.ListFilteredMessagesRequest]) (*connect.Response[v1.ListFilteredMessagesResponse], error)
	GetFilteredMessage(context.Context, *connect.Request[v1.GetFilteredMessageRequest]) (*connect.Response[v1.GetFilteredMessageResponse], error)
	ReleaseFilteredMessage(context.Context, *connect.Request[v1.ReleaseFilteredMessageRequest]) (*connect.Response[v1.ReleaseFilteredMessageResponse], error)
	RejectFilteredMessage(context.Context, *connect.Request[v1.RejectFilteredMessageRequest]) (*connect.Response[v1.RejectFilteredMessageResponse], error)
}

// NewEmailFilterServiceClient constructs a client for the panmail.v1.EmailFilterService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewEmailFilterServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) EmailFilterServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	emailFilterServiceMethods := v1.File_panmail_v1_email_filter_service_proto.Services().ByName("EmailFilterService").Methods()
	return &emailFilterServiceClient{
		listFilterRules: connect.NewClient[v1.ListFilterRulesRequest, v1.ListFilterRulesResponse](
			httpClient,
			baseURL+EmailFilterServiceListFilterRulesProcedure,
			connect.WithSchema(emailFilterServiceMethods.ByName("ListFilterRules")),
			connect.WithClientOptions(opts...),
		),
		createFilterRule: connect.NewClient[v1.CreateFilterRuleRequest, v1.CreateFilterRuleResponse](
			httpClient,
			baseURL+EmailFilterServiceCreateFilterRuleProcedure,
			connect.WithSchema(emailFilterServiceMethods.ByName("CreateFilterRule")),
			connect.WithClientOptions(opts...),
		),
		updateFilterRule: connect.NewClient[v1.UpdateFilterRuleRequest, v1.UpdateFilterRuleResponse](
			httpClient,
			baseURL+EmailFilterServiceUpdateFilterRuleProcedure,
			connect.WithSchema(emailFilterServiceMethods.ByName("UpdateFilterRule")),
			connect.WithClientOptions(opts...),
		),
		deleteFilterRule: connect.NewClient[v1.DeleteFilterRuleRequest, v1.DeleteFilterRuleResponse](
			httpClient,
			baseURL+EmailFilterServiceDeleteFilterRuleProcedure,
			connect.WithSchema(emailFilterServiceMethods.ByName("DeleteFilterRule")),
			connect.WithClientOptions(opts...),
		),
		listFilteredMessages: connect.NewClient[v1.ListFilteredMessagesRequest, v1.ListFilteredMessagesResponse](
			httpClient,
			baseURL+EmailFilterServiceListFilteredMessagesProcedure,
			connect.WithSchema(emailFilterServiceMethods.ByName("ListFilteredMessages")),
			connect.WithClientOptions(opts...),
		),
		getFilteredMessage: connect.NewClient[v1.GetFilteredMessageRequest, v1.GetFilteredMessageResponse](
			httpClient,
			baseURL+EmailFilterServiceGetFilteredMessageProcedure,
			connect.WithSchema(emailFilterServiceMethods.ByName("GetFilteredMessage")),
			connect.WithClientOptions(opts...),
		),
		releaseFilteredMessage: connect.NewClient[v1.ReleaseFilteredMessageRequest, v1.ReleaseFilteredMessageResponse](
			httpClient,
			baseURL+EmailFilterServiceReleaseFilteredMessageProcedure,
			connect.WithSchema(emailFilterServiceMethods.ByName("ReleaseFilteredMessage")),
			connect.WithClientOptions(opts...),
		),
		rejectFilteredMessage: connect.NewClient[v1.RejectFilteredMessageRequest, v1.RejectFilteredMessageResponse](
			httpClient,
			baseURL+EmailFilterServiceRejectFilteredMessageProcedure,
			connect.WithSchema(emailFilterServiceMethods.ByName("RejectFilteredMessage")),
			connect.WithClientOptions(opts...),
		),
	}
}

// emailFilterServiceClient implements EmailFilterServiceClient.
type emailFilterServiceClient struct {
	listFilterRules        *connect.Client[v1.ListFilterRulesRequest, v1.ListFilterRulesResponse]
	createFilterRule       *connect.Client[v1.CreateFilterRuleRequest, v1.CreateFilterRuleResponse]
	updateFilterRule       *connect.Client[v1.UpdateFilterRuleRequest, v1.UpdateFilterRuleResponse]
	deleteFilterRule       *connect.Client[v1.DeleteFilterRuleRequest, v1.DeleteFilterRuleResponse]
	listFilteredMessages   *connect.Client[v1.ListFilteredMessagesRequest, v1.ListFilteredMessagesResponse]
	getFilteredMessage     *connect.Client[v1.GetFilteredMessageRequest, v1.GetFilteredMessageResponse]
	releaseFilteredMessage *connect.Client[v1.ReleaseFilteredMessageRequest, v1.ReleaseFilteredMessageResponse]
	rejectFilteredMessage  *connect.Client[v1.RejectFilteredMessageRequest, v1.RejectFilteredMessageResponse]
}

// ListFilterRules calls panmail.v1.EmailFilterService.ListFilterRules.
func (c *emailFilterServiceClient) ListFilterRules(ctx context.Context, req *connect.Request[v1.ListFilterRulesRequest]) (*connect.Response[v1.ListFilterRulesResponse], error) {
	return c.listFilterRules.CallUnary(ctx, req)
}

// CreateFilterRule calls panmail.v1.EmailFilterService.CreateFilterRule.
func (c *emailFilterServiceClient) CreateFilterRule(ctx context.Context, req *connect.Request[v1.CreateFilterRuleRequest]) (*connect.Response[v1.CreateFilterRuleResponse], error) {
	return c.createFilterRule.CallUnary(ctx, req)
}

// UpdateFilterRule calls panmail.v1.EmailFilterService.UpdateFilterRule.
func (c *emailFilterServiceClient) UpdateFilterRule(ctx context.Context, req *connect.Request[v1.UpdateFilterRuleRequest]) (*connect.Response[v1.UpdateFilterRuleResponse], error) {
	return c.updateFilterRule.CallUnary(ctx, req)
}

// DeleteFilterRule calls panmail.v1.EmailFilterService.DeleteFilterRule.
func (c *emailFilterServiceClient) DeleteFilterRule(ctx context.Context, req *connect.Request[v1.DeleteFilterRuleRequest]) (*connect.Response[v1.DeleteFilterRuleResponse], error) {
	return c.deleteFilterRule.CallUnary(ctx, req)
}

// ListFilteredMessages calls panmail.v1.EmailFilterService.ListFilteredMessages.
func (c *emailFilterServiceClient) ListFilteredMessages(ctx context.Context, req *connect.Request[v1.ListFilteredMessagesRequest]) (*connect.Response[v1.ListFilteredMessagesResponse], error) {
	return c.listFilteredMessages.CallUnary(ctx, req)
}

// GetFilteredMessage calls panmail.v1.EmailFilterService.GetFilteredMessage.
func (c *emailFilterServiceClient) GetFilteredMessage(ctx context.Context, req *connect.Request[v1.GetFilteredMessageRequest]) (*connect.Response[v1.GetFilteredMessageResponse], error) {
	return c.getFilteredMessage.CallUnary(ctx, req)
}

// ReleaseFilteredMessage calls panmail.v1.EmailFilterService.ReleaseFilteredMessage.
func (c *emailFilterServiceClient) ReleaseFilteredMessage(ctx context.Context, req *connect.Request[v1.ReleaseFilteredMessageRequest]) (*connect.Response[v1.ReleaseFilteredMessageResponse], error) {
	return c.releaseFilteredMessage.CallUnary(ctx, req)
}

// RejectFilteredMessage calls panmail.v1.EmailFilterService.RejectFilteredMessage.
func (c *emailFilterServiceClient) RejectFilteredMessage(ctx context.Context, req *connect.Request[v1.RejectFilteredMessageRequest]) (*connect.Response[v1.RejectFilteredMessageResponse], error) {
	return c.rejectFilteredMessage.CallUnary(ctx, req)
}

// EmailFilterServiceHandler is an implementation of the panmail.v1.EmailFilterService service.
type EmailFilterServiceHandler interface {
	ListFilterRules(context.Context, *connect.Request[v1.ListFilterRulesRequest]) (*connect.Response[v1.ListFilterRulesResponse], error)
	CreateFilterRule(context.Context, *connect.Request[v1.CreateFilterRuleRequest]) (*connect.Response[v1.CreateFilterRuleResponse], error)
	UpdateFilterRule(context.Context, *connect.Request[v1.UpdateFilterRuleRequest]) (*connect.Response[v1.UpdateFilterRuleResponse], error)
	DeleteFilterRule(context.Context, *connect.Request[v1.DeleteFilterRuleRequest]) (*connect.Response[v1.DeleteFilterRuleResponse], error)
	ListFilteredMessages(context.Context, *connect.Request[v1.ListFilteredMessagesRequest]) (*connect.Response[v1.ListFilteredMessagesResponse], error)
	GetFilteredMessage(context.Context, *connect.Request[v1.GetFilteredMessageRequest]) (*connect.Response[v1.GetFilteredMessageResponse], error)
	ReleaseFilteredMessage(context.Context, *connect.Request[v1.ReleaseFilteredMessageRequest]) (*connect.Response[v1.ReleaseFilteredMessageResponse], error)
	RejectFilteredMessage(context.Context, *connect.Request[v1.RejectFilteredMessageRequest]) (*connect.Response[v1.RejectFilteredMessageResponse], error)
}

// NewEmailFilterServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewEmailFilterServiceHandler(svc EmailFilterServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	emailFilterServiceMethods := v1.File_panmail_v1_email_filter_service_proto.Services().ByName("EmailFilterService").Methods()
	emailFilterServiceListFilterRulesHandler := connect.NewUnaryHandler(
		EmailFilterServiceListFilterRulesProcedure,
		svc.ListFilterRules,
		connect.WithSchema(emailFilterServiceMethods.ByName("ListFilterRules")),
		connect.WithHandlerOptions(opts...),
	)
	emailFilterServiceCreateFilterRuleHandler := connect.NewUnaryHandler(
		EmailFilterServiceCreateFilterRuleProcedure,
		svc.CreateFilterRule,
		connect.WithSchema(emailFilterServiceMethods.ByName("CreateFilterRule")),
		connect.WithHandlerOptions(opts...),
	)
	emailFilterServiceUpdateFilterRuleHandler := connect.NewUnaryHandler(
		EmailFilterServiceUpdateFilterRuleProcedure,
		svc.UpdateFilterRule,
		connect.WithSchema(emailFilterServiceMethods.ByName("UpdateFilterRule")),
		connect.WithHandlerOptions(opts...),
	)
	emailFilterServiceDeleteFilterRuleHandler := connect.NewUnaryHandler(
		EmailFilterServiceDeleteFilterRuleProcedure,
		svc.DeleteFilterRule,
		connect.WithSchema(emailFilterServiceMethods.ByName("DeleteFilterRule")),
		connect.WithHandlerOptions(opts...),
	)
	emailFilterServiceListFilteredMessagesHandler := connect.NewUnaryHandler(
		EmailFilterServiceListFilteredMessagesProcedure,
		svc.ListFilteredMessages,
		connect.WithSchema(emailFilterServiceMethods.ByName("ListFilteredMessages")),
		connect.WithHandlerOptions(opts...),
	)
	emailFilterServiceGetFilteredMessageHandler := connect.NewUnaryHandler(
		EmailFilterServiceGetFilteredMessageProcedure,
		svc.GetFilteredMessage,
		connect.WithSchema(emailFilterServiceMethods.ByName("GetFilteredMessage")),
		connect.WithHandlerOptions(opts...),
	)
	emailFilterServiceReleaseFilteredMessageHandler := connect.NewUnaryHandler(
		EmailFilterServiceReleaseFilteredMessageProcedure,
		svc.ReleaseFilteredMessage,
		connect.WithSchema(emailFilterServiceMethods.ByName("ReleaseFilteredMessage")),
		connect.WithHandlerOptions(opts...),
	)
	emailFilterServiceRejectFilteredMessageHandler := connect.NewUnaryHandler(
		EmailFilterServiceRejectFilteredMessageProcedure,
		svc.RejectFilteredMessage,
		connect.WithSchema(emailFilterServiceMethods.ByName("RejectFilteredMessage")),
		connect.WithHandlerOptions(opts...),
	)
	return "/panmail.v1.EmailFilterService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case EmailFilterServiceListFilterRulesProcedure:
			emailFilterServiceListFilterRulesHandler.ServeHTTP(w, r)
		case EmailFilterServiceCreateFilterRuleProcedure:
			emailFilterServiceCreateFilterRuleHandler.ServeHTTP(w, r)
		case EmailFilterServiceUpdateFilterRuleProcedure:
			emailFilterServiceUpdateFilterRuleHandler.ServeHTTP(w, r)
		case EmailFilterServiceDeleteFilterRuleProcedure:
			emailFilterServiceDeleteFilterRuleHandler.ServeHTTP(w, r)
		case EmailFilterServiceListFilteredMessagesProcedure:
			emailFilterServiceListFilteredMessagesHandler.ServeHTTP(w, r)
		case EmailFilterServiceGetFilteredMessageProcedure:
			emailFilterServiceGetFilteredMessageHandler.ServeHTTP(w, r)
		case EmailFilterServiceReleaseFilteredMessageProcedure:
			emailFilterServiceReleaseFilteredMessageHandler.ServeHTTP(w, r)
		case EmailFilterServiceRejectFilteredMessageProcedure:
			emailFilterServiceRejectFilteredMessageHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedEmailFilterServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedEmailFilterServiceHandler struct{}

func (UnimplementedEmailFilterServiceHandler) ListFilterRules(context.Context, *connect.Request[v1.ListFilterRulesRequest]) (*connect.Response[v1.ListFilterRulesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("panmail.v1.EmailFilterService.ListFilterRules is not implemented"))
}

func (UnimplementedEmailFilterServiceHandler) CreateFilterRule(context.Context, *connect.Request[v1.CreateFilterRuleRequest]) (*connect.Response[v1.CreateFilterRuleResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("panmail.v1.EmailFilterService.CreateFilterRule is not implemented"))
}

func (UnimplementedEmailFilterServiceHandler) UpdateFilterRule(context.Context, *connect.Request[v1.UpdateFilterRuleRequest]) (*connect.Response[v1.UpdateFilterRuleResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("panmail.v1.EmailFilterService.UpdateFilterRule is not implemented"))
}

func (UnimplementedEmailFilterServiceHandler) DeleteFilterRule(context.Context, *connect.Request[v1.DeleteFilterRuleRequest]) (*connect.Response[v1.DeleteFilterRuleResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("panmail.v1.EmailFilterService.DeleteFilterRule is not implemented"))
}

func (UnimplementedEmailFilterServiceHandler) ListFilteredMessages(context.Context, *connect.Request[v1.ListFilteredMessagesRequest]) (*connect.Response[v1.ListFilteredMessagesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("panmail.v1.EmailFilterService.ListFilteredMessages is not implemented"))
}

func (UnimplementedEmailFilterServiceHandler) GetFilteredMessage(context.Context, *connect.Request[v1.GetFilteredMessageRequest]) (*connect.Response[v1.GetFilteredMessageResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("panmail.v1.EmailFilterService.GetFilteredMessage is not implemented"))
}

func (UnimplementedEmailFilterServiceHandler) ReleaseFilteredMessage(context.Context, *connect.Request[v1.ReleaseFilteredMessageRequest]) (*connect.Response[v1.ReleaseFilteredMessageResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("panmail.v1.EmailFilterService.ReleaseFilteredMessage is not implemented"))
}

func (UnimplementedEmailFilterServiceHandler) RejectFilteredMessage(context.Context, *connect.Request[v1.RejectFilteredMessageRequest]) (*connect.Response[v1.RejectFilteredMessageResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("panmail.v1.EmailFilterService.RejectFilteredMessage is not implemented"))
}
