// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: panmail/v1/inbound_service.proto

package panmailv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/gsoultan/panmail/api/panmail/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// InboundServiceName is the fully-qualified name of the InboundService service.
	InboundServiceName = "panmail.v1.InboundService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// InboundServiceListInboundEmailsProcedure is the fully-qualified name of the InboundService's
	// ListInboundEmails RPC.
	InboundServiceListInboundEmailsProcedure = "/panmail.v1.InboundService/ListInboundEmails"
	// InboundServiceGetInboundEmailProcedure is the fully-qualified name of the InboundService's
	// GetInboundEmail RPC.
	InboundServiceGetInboundEmailProcedure = "/panmail.v1.InboundService/GetInboundEmail"
)

// InboundServiceClient is a client for the panmail.v1.InboundService service.
type InboundServiceClient interface {
	ListInboundEmails(context.Context, *connect.Request[v1.ListInboundEmailsRequest]) (*connect.Response[v1.ListInboundEmailsResponse], error)
	GetInboundEmail(context.Context, *connect.Request[v1.GetInboundEmailRequest]) (*connect.Response[v1.GetInboundEmailResponse], error)
}

// NewInboundServiceClient constructs a client for the panmail.v1.InboundService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewInboundServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) InboundServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	inboundServiceMethods := v1.File_panmail_v1_inbound_service_proto.Services().ByName("InboundService").Methods()
	return &inboundServiceClient{
		listInboundEmails: connect.NewClient[v1.ListInboundEmailsRequest, v1.ListInboundEmailsResponse](
			httpClient,
			baseURL+InboundServiceListInboundEmailsProcedure,
			connect.WithSchema(inboundServiceMethods.ByName("ListInboundEmails")),
			connect.WithClientOptions(opts...),
		),
		getInboundEmail: connect.NewClient[v1.GetInboundEmailRequest, v1.GetInboundEmailResponse](
			httpClient,
			baseURL+InboundServiceGetInboundEmailProcedure,
			connect.WithSchema(inboundServiceMethods.ByName("GetInboundEmail")),
			connect.WithClientOptions(opts...),
		),
	}
}

// inboundServiceClient implements InboundServiceClient.
type inboundServiceClient struct {
	listInboundEmails *connect.Client[v1.ListInboundEmailsRequest, v1.ListInboundEmailsResponse]
	getInboundEmail   *connect.Client[v1.GetInboundEmailRequest, v1.GetInboundEmailResponse]
}

// ListInboundEmails calls panmail.v1.InboundService.ListInboundEmails.
func (c *inboundServiceClient) ListInboundEmails(ctx context.Context, req *connect.Request[v1.ListInboundEmailsRequest]) (*connect.Response[v1.ListInboundEmailsResponse], error) {
	return c.listInboundEmails.CallUnary(ctx, req)
}

// GetInboundEmail calls panmail.v1.InboundService.GetInboundEmail.
func (c *inboundServiceClient) GetInboundEmail(ctx context.Context, req *connect.Request[v1.GetInboundEmailRequest]) (*connect.Response[v1.GetInboundEmailResponse], error) {
	return c.getInboundEmail.CallUnary(ctx, req)
}

// InboundServiceHandler is an implementation of the panmail.v1.InboundService service.
type InboundServiceHandler interface {
	ListInboundEmails(context.Context, *connect.Request[v1.ListInboundEmailsRequest]) (*connect.Response[v1.ListInboundEmailsResponse], error)
	GetInboundEmail(context.Context, *connect.Request[v1.GetInboundEmailRequest]) (*connect.Response[v1.GetInboundEmailResponse], error)
}

// NewInboundServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewInboundServiceHandler(svc InboundServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	inboundServiceMethods := v1.File_panmail_v1_inbound_service_proto.Services().ByName("InboundService").Methods()
	inboundServiceListInboundEmailsHandler := connect.NewUnaryHandler(
		InboundServiceListInboundEmailsProcedure,
		svc.ListInboundEmails,
		connect.WithSchema(inboundServiceMethods.ByName("ListInboundEmails")),
		connect.WithHandlerOptions(opts...),
	)
	inboundServiceGetInboundEmailHandler := connect.NewUnaryHandler(
		InboundServiceGetInboundEmailProcedure,
		svc.GetInboundEmail,
		connect.WithSchema(inboundServiceMethods.ByName("GetInboundEmail")),
		connect.WithHandlerOptions(opts...),
	)
	return "/panmail.v1.InboundService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case InboundServiceListInboundEmailsProcedure:
			inboundServiceListInboundEmailsHandler.ServeHTTP(w, r)
		case InboundServiceGetInboundEmailProcedure:
			inboundServiceGetInboundEmailHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedInboundServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedInboundServiceHandler struct{}

func (UnimplementedInboundServiceHandler) ListInboundEmails(context.Context, *connect.Request[v1.ListInboundEmailsRequest]) (*connect.Response[v1.ListInboundEmailsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("panmail.v1.InboundService.ListInboundEmails is not implemented"))
}

func (UnimplementedInboundServiceHandler) GetInboundEmail(context.Context, *connect.Request[v1.GetInboundEmailRequest]) (*connect.Response[v1.GetInboundEmailResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("panmail.v1.InboundService.GetInboundEmail is not implemented"))
}
