// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: panmail/v1/system_settings.proto

package panmailv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/gsoultan/panmail/api/panmail/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// SystemSettingsServiceName is the fully-qualified name of the SystemSettingsService service.
	SystemSettingsServiceName = "panmail.v1.SystemSettingsService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// SystemSettingsServiceGetSettingsProcedure is the fully-qualified name of the
	// SystemSettingsService's GetSettings RPC.
	SystemSettingsServiceGetSettingsProcedure = "/panmail.v1.SystemSettingsService/GetSettings"
	// SystemSettingsServiceUpdateSettingsProcedure is the fully-qualified name of the
	// SystemSettingsService's UpdateSettings RPC.
	SystemSettingsServiceUpdateSettingsProcedure = "/panmail.v1.SystemSettingsService/UpdateSettings"
)

// SystemSettingsServiceClient is a client for the panmail.v1.SystemSettingsService service.
type SystemSettingsServiceClient interface {
	GetSettings(context.Context, *connect.Request[v1.GetSettingsRequest]) (*connect.Response[v1.GetSettingsResponse], error)
	UpdateSettings(context.Context, *connect.Request[v1.UpdateSettingsRequest]) (*connect.Response[v1.UpdateSettingsResponse], error)
}

// NewSystemSettingsServiceClient constructs a client for the panmail.v1.SystemSettingsService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSystemSettingsServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SystemSettingsServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	systemSettingsServiceMethods := v1.File_panmail_v1_system_settings_proto.Services().ByName("SystemSettingsService").Methods()
	return &systemSettingsServiceClient{
		getSettings: connect.NewClient[v1.GetSettingsRequest, v1.GetSettingsResponse](
			httpClient,
			baseURL+SystemSettingsServiceGetSettingsProcedure,
			connect.WithSchema(systemSettingsServiceMethods.ByName("GetSettings")),
			connect.WithClientOptions(opts...),
		),
		updateSettings: connect.NewClient[v1.UpdateSettingsRequest, v1.UpdateSettingsResponse](
			httpClient,
			baseURL+SystemSettingsServiceUpdateSettingsProcedure,
			connect.WithSchema(systemSettingsServiceMethods.ByName("UpdateSettings")),
			connect.WithClientOptions(opts...),
		),
	}
}

// systemSettingsServiceClient implements SystemSettingsServiceClient.
type systemSettingsServiceClient struct {
	getSettings    *connect.Client[v1.GetSettingsRequest, v1.GetSettingsResponse]
	updateSettings *connect.Client[v1.UpdateSettingsRequest, v1.UpdateSettingsResponse]
}

// GetSettings calls panmail.v1.SystemSettingsService.GetSettings.
func (c *systemSettingsServiceClient) GetSettings(ctx context.Context, req *connect.Request[v1.GetSettingsRequest]) (*connect.Response[v1.GetSettingsResponse], error) {
	return c.getSettings.CallUnary(ctx, req)
}

// UpdateSettings calls panmail.v1.SystemSettingsService.UpdateSettings.
func (c *systemSettingsServiceClient) UpdateSettings(ctx context.Context, req *connect.Request[v1.UpdateSettingsRequest]) (*connect.Response[v1.UpdateSettingsResponse], error) {
	return c.updateSettings.CallUnary(ctx, req)
}

// SystemSettingsServiceHandler is an implementation of the panmail.v1.SystemSettingsService
// service.
type SystemSettingsServiceHandler interface {
	GetSettings(context.Context, *connect.Request[v1.GetSettingsRequest]) (*connect.Response[v1.GetSettingsResponse], error)
	UpdateSettings(context.Context, *connect.Request[v1.UpdateSettingsRequest]) (*connect.Response[v1.UpdateSettingsResponse], error)
}

// NewSystemSettingsServiceHandler builds an HTTP handler from the service implementation. It
// returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSystemSettingsServiceHandler(svc SystemSettingsServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	systemSettingsServiceMethods := v1.File_panmail_v1_system_settings_proto.Services().ByName("SystemSettingsService").Methods()
	systemSettingsServiceGetSettingsHandler := connect.NewUnaryHandler(
		SystemSettingsServiceGetSettingsProcedure,
		svc.GetSettings,
		connect.WithSchema(systemSettingsServiceMethods.ByName("GetSettings")),
		connect.WithHandlerOptions(opts...),
	)
	systemSettingsServiceUpdateSettingsHandler := connect.NewUnaryHandler(
		SystemSettingsServiceUpdateSettingsProcedure,
		svc.UpdateSettings,
		connect.WithSchema(systemSettingsServiceMethods.ByName("UpdateSettings")),
		connect.WithHandlerOptions(opts...),
	)
	return "/panmail.v1.SystemSettingsService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SystemSettingsServiceGetSettingsProcedure:
			systemSettingsServiceGetSettingsHandler.ServeHTTP(w, r)
		case SystemSettingsServiceUpdateSettingsProcedure:
			systemSettingsServiceUpdateSettingsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSystemSettingsServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedSystemSettingsServiceHandler struct{}

func (UnimplementedSystemSettingsServiceHandler) GetSettings(context.Context, *connect.Request[v1.GetSettingsRequest]) (*connect.Response[v1.GetSettingsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("panmail.v1.SystemSettingsService.GetSettings is not implemented"))
}

func (UnimplementedSystemSettingsServiceHandler) UpdateSettings(context.Context, *connect.Request[v1.UpdateSettingsRequest]) (*connect.Response[v1.UpdateSettingsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("panmail.v1.SystemSettingsService.UpdateSettings is not implemented"))
}
