// @generated by protoc-gen-es v2.14.0 with parameter "target=ts,import_extension=none"
// @generated from file panmail/v1/email_service.proto (package panmail.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { EmailEventType } from "./event_pb";
import { file_panmail_v1_event } from "./event_pb";
import type { Attachment } from "./common_pb";
import { file_panmail_v1_common } from "./common_pb";
import { file_google_protobuf_struct } from "@bufbuild/protobuf/wkt";
import type { JsonObject, Message } from "@bufbuild/protobuf";

/**
 * Describes the file panmail/v1/email_service.proto.
 */
export const file_panmail_v1_email_service: GenFile = /*@__PURE__*/
  fileDesc("Ch5wYW5tYWlsL3YxL2VtYWlsX3NlcnZpY2UucHJvdG8SCnBhbm1haWwudjEiqgIKEFNlbmRFbWFpbFJlcXVlc3QSEwoLcHJvdmlkZXJfaWQYASABKAkSDAoEZnJvbRgCIAEoCRIKCgJ0bxgDIAMoCRIKCgJjYxgMIAMoCRILCgNiY2MYDSADKAkSDwoHc3ViamVjdBgEIAEoCRIQCgRib2R5GAUgASgJQgIYARITCgdpc19odG1sGAYgASgIQgIYARIRCglib2R5X2h0bWwYCSABKAkSEQoJYm9keV90ZXh0GAogASgJEhMKC3RlbXBsYXRlX2lkGAcgASgJEi4KDXRlbXBsYXRlX2RhdGEYCCABKAsyFy5nb29nbGUucHJvdG9idWYuU3RydWN0EisKC2F0dGFjaG1lbnRzGAsgAygLMhYucGFubWFpbC52MS5BdHRhY2htZW50ImIKEVNlbmRFbWFpbFJlc3BvbnNlEhIKCm1lc3NhZ2VfaWQYASABKAkSKgoGc3RhdHVzGAIgASgOMhoucGFubWFpbC52MS5FbWFpbEV2ZW50VHlwZRINCgVlcnJvchgDIAEoCTJYCgxFbWFpbFNlcnZpY2USSAoJU2VuZEVtYWlsEhwucGFubWFpbC52MS5TZW5kRW1haWxSZXF1ZXN0Gh0ucGFubWFpbC52MS5TZW5kRW1haWxSZXNwb25zZUKiAQoOY29tLnBhbm1haWwudjFCEUVtYWlsU2VydmljZVByb3RvUAFaNGdpdGh1Yi5jb20vZ3NvdWx0YW4vcGFubWFpbC9hcGkvcGFubWFpbC92MTtwYW5tYWlsdjGiAgNQWFiqAgpQYW5tYWlsLlYxygIKUGFubWFpbFxWMeICFlBhbm1haWxcVjFcR1BCTWV0YWRhdGHqAgtQYW5tYWlsOjpWMWIGcHJvdG8z", [file_panmail_v1_event, file_panmail_v1_common, file_google_protobuf_struct]);

/**
 * @generated from message panmail.v1.SendEmailRequest
 */
export type SendEmailRequest = Message<"panmail.v1.SendEmailRequest"> & {
  /**
   * @generated from field: string provider_id = 1;
   */
  providerId: string;

  /**
   * @generated from field: string from = 2;
   */
  from: string;

  /**
   * @generated from field: repeated string to = 3;
   */
  to: string[];

  /**
   * @generated from field: repeated string cc = 12;
   */
  cc: string[];

  /**
   * @generated from field: repeated string bcc = 13;
   */
  bcc: string[];

  /**
   * @generated from field: string subject = 4;
   */
  subject: string;

  /**
   * @generated from field: string body = 5 [deprecated = true];
   * @deprecated
   */
  body: string;

  /**
   * @generated from field: bool is_html = 6 [deprecated = true];
   * @deprecated
   */
  isHtml: boolean;

  /**
   * @generated from field: string body_html = 9;
   */
  bodyHtml: string;

  /**
   * @generated from field: string body_text = 10;
   */
  bodyText: string;

  /**
   * @generated from field: string template_id = 7;
   */
  templateId: string;

  /**
   * @generated from field: google.protobuf.Struct template_data = 8;
   */
  templateData?: JsonObject | undefined;

  /**
   * @generated from field: repeated panmail.v1.Attachment attachments = 11;
   */
  attachments: Attachment[];
};

/**
 * Describes the message panmail.v1.SendEmailRequest.
 * Use `create(SendEmailRequestSchema)` to create a new message.
 */
export const SendEmailRequestSchema: GenMessage<SendEmailRequest> = /*@__PURE__*/
  messageDesc(file_panmail_v1_email_service, 0);

/**
 * @generated from message panmail.v1.SendEmailResponse
 */
export type SendEmailResponse = Message<"panmail.v1.SendEmailResponse"> & {
  /**
   * @generated from field: string message_id = 1;
   */
  messageId: string;

  /**
   * @generated from field: panmail.v1.EmailEventType status = 2;
   */
  status: EmailEventType;

  /**
   * @generated from field: string error = 3;
   */
  error: string;
};

/**
 * Describes the message panmail.v1.SendEmailResponse.
 * Use `create(SendEmailResponseSchema)` to create a new message.
 */
export const SendEmailResponseSchema: GenMessage<SendEmailResponse> = /*@__PURE__*/
  messageDesc(file_panmail_v1_email_service, 1);

/**
 * @generated from service panmail.v1.EmailService
 */
export const EmailService: GenService<{
  /**
   * @generated from rpc panmail.v1.EmailService.SendEmail
   */
  sendEmail: {
    methodKind: "unary";
    input: typeof SendEmailRequestSchema;
    output: typeof SendEmailResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_panmail_v1_email_service, 0);

