// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file panmail/v1/event_service.proto (package panmail.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64, Timestamp } from "@bufbuild/protobuf";
import { EmailEvent, EmailEventType, EmailMessage } from "./event_pb.js";

/**
 * @generated from message panmail.v1.ListArchivesRequest
 */
export class ListArchivesRequest extends Message<ListArchivesRequest> {
  /**
   * @generated from field: int32 page_size = 1;
   */
  pageSize = 0;

  /**
   * @generated from field: string page_token = 2;
   */
  pageToken = "";

  constructor(data?: PartialMessage<ListArchivesRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "panmail.v1.ListArchivesRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "page_size", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "page_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListArchivesRequest {
    return new ListArchivesRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListArchivesRequest {
    return new ListArchivesRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListArchivesRequest {
    return new ListArchivesRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ListArchivesRequest | PlainMessage<ListArchivesRequest> | undefined, b: ListArchivesRequest | PlainMessage<ListArchivesRequest> | undefined): boolean {
    return proto3.util.equals(ListArchivesRequest, a, b);
  }
}

/**
 * @generated from message panmail.v1.ArchiveInfo
 */
export class ArchiveInfo extends Message<ArchiveInfo> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * @generated from field: string filename = 2;
   */
  filename = "";

  /**
   * @generated from field: int64 size = 3;
   */
  size = protoInt64.zero;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 4;
   */
  createdAt?: Timestamp;

  constructor(data?: PartialMessage<ArchiveInfo>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "panmail.v1.ArchiveInfo";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "filename", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "size", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 4, name: "created_at", kind: "message", T: Timestamp },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ArchiveInfo {
    return new ArchiveInfo().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ArchiveInfo {
    return new ArchiveInfo().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ArchiveInfo {
    return new ArchiveInfo().fromJsonString(jsonString, options);
  }

  static equals(a: ArchiveInfo | PlainMessage<ArchiveInfo> | undefined, b: ArchiveInfo | PlainMessage<ArchiveInfo> | undefined): boolean {
    return proto3.util.equals(ArchiveInfo, a, b);
  }
}

/**
 * @generated from message panmail.v1.ListArchivesResponse
 */
export class ListArchivesResponse extends Message<ListArchivesResponse> {
  /**
   * @generated from field: repeated panmail.v1.ArchiveInfo archives = 1;
   */
  archives: ArchiveInfo[] = [];

  /**
   * @generated from field: string next_page_token = 2;
   */
  nextPageToken = "";

  constructor(data?: PartialMessage<ListArchivesResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "panmail.v1.ListArchivesResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "archives", kind: "message", T: ArchiveInfo, repeated: true },
    { no: 2, name: "next_page_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListArchivesResponse {
    return new ListArchivesResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListArchivesResponse {
    return new ListArchivesResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListArchivesResponse {
    return new ListArchivesResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ListArchivesResponse | PlainMessage<ListArchivesResponse> | undefined, b: ListArchivesResponse | PlainMessage<ListArchivesResponse> | undefined): boolean {
    return proto3.util.equals(ListArchivesResponse, a, b);
  }
}

/**
 * @generated from message panmail.v1.DownloadArchiveRequest
 */
export class DownloadArchiveRequest extends Message<DownloadArchiveRequest> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  constructor(data?: PartialMessage<DownloadArchiveRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "panmail.v1.DownloadArchiveRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DownloadArchiveRequest {
    return new DownloadArchiveRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DownloadArchiveRequest {
    return new DownloadArchiveRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DownloadArchiveRequest {
    return new DownloadArchiveRequest().fromJsonString(jsonString, options);
  }

  static equals(a: DownloadArchiveRequest | PlainMessage<DownloadArchiveRequest> | undefined, b: DownloadArchiveRequest | PlainMessage<DownloadArchiveRequest> | undefined): boolean {
    return proto3.util.equals(DownloadArchiveRequest, a, b);
  }
}

/**
 * @generated from message panmail.v1.DownloadArchiveResponse
 */
export class DownloadArchiveResponse extends Message<DownloadArchiveResponse> {
  /**
   * @generated from field: bytes content = 1;
   */
  content = new Uint8Array(0);

  /**
   * @generated from field: string filename = 2;
   */
  filename = "";

  constructor(data?: PartialMessage<DownloadArchiveResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "panmail.v1.DownloadArchiveResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "content", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 2, name: "filename", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DownloadArchiveResponse {
    return new DownloadArchiveResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DownloadArchiveResponse {
    return new DownloadArchiveResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DownloadArchiveResponse {
    return new DownloadArchiveResponse().fromJsonString(jsonString, options);
  }

  static equals(a: DownloadArchiveResponse | PlainMessage<DownloadArchiveResponse> | undefined, b: DownloadArchiveResponse | PlainMessage<DownloadArchiveResponse> | undefined): boolean {
    return proto3.util.equals(DownloadArchiveResponse, a, b);
  }
}

/**
 * @generated from message panmail.v1.GetPerformanceMetricsRequest
 */
export class GetPerformanceMetricsRequest extends Message<GetPerformanceMetricsRequest> {
  constructor(data?: PartialMessage<GetPerformanceMetricsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "panmail.v1.GetPerformanceMetricsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetPerformanceMetricsRequest {
    return new GetPerformanceMetricsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetPerformanceMetricsRequest {
    return new GetPerformanceMetricsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetPerformanceMetricsRequest {
    return new GetPerformanceMetricsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetPerformanceMetricsRequest | PlainMessage<GetPerformanceMetricsRequest> | undefined, b: GetPerformanceMetricsRequest | PlainMessage<GetPerformanceMetricsRequest> | undefined): boolean {
    return proto3.util.equals(GetPerformanceMetricsRequest, a, b);
  }
}

/**
 * @generated from message panmail.v1.ResourcePoint
 */
export class ResourcePoint extends Message<ResourcePoint> {
  /**
   * @generated from field: google.protobuf.Timestamp timestamp = 1;
   */
  timestamp?: Timestamp;

  /**
   * @generated from field: double cpu_usage = 2;
   */
  cpuUsage = 0;

  /**
   * @generated from field: uint64 memory_usage = 3;
   */
  memoryUsage = protoInt64.zero;

  /**
   * @generated from field: double system_load_15 = 4;
   */
  systemLoad15 = 0;

  constructor(data?: PartialMessage<ResourcePoint>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "panmail.v1.ResourcePoint";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "timestamp", kind: "message", T: Timestamp },
    { no: 2, name: "cpu_usage", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 3, name: "memory_usage", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 4, name: "system_load_15", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ResourcePoint {
    return new ResourcePoint().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ResourcePoint {
    return new ResourcePoint().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ResourcePoint {
    return new ResourcePoint().fromJsonString(jsonString, options);
  }

  static equals(a: ResourcePoint | PlainMessage<ResourcePoint> | undefined, b: ResourcePoint | PlainMessage<ResourcePoint> | undefined): boolean {
    return proto3.util.equals(ResourcePoint, a, b);
  }
}

/**
 * @generated from message panmail.v1.GetPerformanceMetricsResponse
 */
export class GetPerformanceMetricsResponse extends Message<GetPerformanceMetricsResponse> {
  /**
   * @generated from field: double sent_per_second = 1;
   */
  sentPerSecond = 0;

  /**
   * @generated from field: double cpu_usage = 2;
   */
  cpuUsage = 0;

  /**
   * @generated from field: uint64 memory_usage = 3;
   */
  memoryUsage = protoInt64.zero;

  /**
   * @generated from field: uint64 uptime_seconds = 4;
   */
  uptimeSeconds = protoInt64.zero;

  /**
   * @generated from field: uint32 goroutines = 5;
   */
  goroutines = 0;

  /**
   * @generated from field: uint64 disk_usage = 6;
   */
  diskUsage = protoInt64.zero;

  /**
   * @generated from field: uint32 open_files = 7;
   */
  openFiles = 0;

  /**
   * @generated from field: uint32 cpu_cores = 8;
   */
  cpuCores = 0;

  /**
   * @generated from field: uint64 total_memory = 9;
   */
  totalMemory = protoInt64.zero;

  /**
   * @generated from field: double system_load_15 = 10;
   */
  systemLoad15 = 0;

  /**
   * @generated from field: repeated panmail.v1.ResourcePoint resource_history = 11;
   */
  resourceHistory: ResourcePoint[] = [];

  constructor(data?: PartialMessage<GetPerformanceMetricsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "panmail.v1.GetPerformanceMetricsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "sent_per_second", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 2, name: "cpu_usage", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 3, name: "memory_usage", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 4, name: "uptime_seconds", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 5, name: "goroutines", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 6, name: "disk_usage", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 7, name: "open_files", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 8, name: "cpu_cores", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 9, name: "total_memory", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 10, name: "system_load_15", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 11, name: "resource_history", kind: "message", T: ResourcePoint, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetPerformanceMetricsResponse {
    return new GetPerformanceMetricsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetPerformanceMetricsResponse {
    return new GetPerformanceMetricsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetPerformanceMetricsResponse {
    return new GetPerformanceMetricsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetPerformanceMetricsResponse | PlainMessage<GetPerformanceMetricsResponse> | undefined, b: GetPerformanceMetricsResponse | PlainMessage<GetPerformanceMetricsResponse> | undefined): boolean {
    return proto3.util.equals(GetPerformanceMetricsResponse, a, b);
  }
}

/**
 * @generated from message panmail.v1.GetEventRequest
 */
export class GetEventRequest extends Message<GetEventRequest> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  constructor(data?: PartialMessage<GetEventRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "panmail.v1.GetEventRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetEventRequest {
    return new GetEventRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetEventRequest {
    return new GetEventRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetEventRequest {
    return new GetEventRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetEventRequest | PlainMessage<GetEventRequest> | undefined, b: GetEventRequest | PlainMessage<GetEventRequest> | undefined): boolean {
    return proto3.util.equals(GetEventRequest, a, b);
  }
}

/**
 * @generated from message panmail.v1.GetEventResponse
 */
export class GetEventResponse extends Message<GetEventResponse> {
  /**
   * @generated from field: panmail.v1.EmailEvent event = 1;
   */
  event?: EmailEvent;

  /**
   * @generated from field: panmail.v1.EmailMessage message = 2;
   */
  message?: EmailMessage;

  constructor(data?: PartialMessage<GetEventResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "panmail.v1.GetEventResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "event", kind: "message", T: EmailEvent },
    { no: 2, name: "message", kind: "message", T: EmailMessage },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetEventResponse {
    return new GetEventResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetEventResponse {
    return new GetEventResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetEventResponse {
    return new GetEventResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetEventResponse | PlainMessage<GetEventResponse> | undefined, b: GetEventResponse | PlainMessage<GetEventResponse> | undefined): boolean {
    return proto3.util.equals(GetEventResponse, a, b);
  }
}

/**
 * @generated from message panmail.v1.GetMetricsRequest
 */
export class GetMetricsRequest extends Message<GetMetricsRequest> {
  /**
   * @generated from field: google.protobuf.Timestamp start_time = 1;
   */
  startTime?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp end_time = 2;
   */
  endTime?: Timestamp;

  constructor(data?: PartialMessage<GetMetricsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "panmail.v1.GetMetricsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "start_time", kind: "message", T: Timestamp },
    { no: 2, name: "end_time", kind: "message", T: Timestamp },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetMetricsRequest {
    return new GetMetricsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetMetricsRequest {
    return new GetMetricsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetMetricsRequest {
    return new GetMetricsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetMetricsRequest | PlainMessage<GetMetricsRequest> | undefined, b: GetMetricsRequest | PlainMessage<GetMetricsRequest> | undefined): boolean {
    return proto3.util.equals(GetMetricsRequest, a, b);
  }
}

/**
 * @generated from message panmail.v1.MetricInfo
 */
export class MetricInfo extends Message<MetricInfo> {
  /**
   * @generated from field: string key = 1;
   */
  key = "";

  /**
   * @generated from field: string label = 2;
   */
  label = "";

  /**
   * @generated from field: string description = 3;
   */
  description = "";

  /**
   * @generated from field: int64 value = 4;
   */
  value = protoInt64.zero;

  /**
   * "outbound", "inbound", "performance", "system"
   *
   * @generated from field: string category = 5;
   */
  category = "";

  constructor(data?: PartialMessage<MetricInfo>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "panmail.v1.MetricInfo";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "label", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "value", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 5, name: "category", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MetricInfo {
    return new MetricInfo().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MetricInfo {
    return new MetricInfo().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MetricInfo {
    return new MetricInfo().fromJsonString(jsonString, options);
  }

  static equals(a: MetricInfo | PlainMessage<MetricInfo> | undefined, b: MetricInfo | PlainMessage<MetricInfo> | undefined): boolean {
    return proto3.util.equals(MetricInfo, a, b);
  }
}

/**
 * @generated from message panmail.v1.GetMetricsResponse
 */
export class GetMetricsResponse extends Message<GetMetricsResponse> {
  /**
   * @generated from field: map<string, int64> metrics = 1;
   */
  metrics: { [key: string]: bigint } = {};

  /**
   * @generated from field: repeated panmail.v1.MetricInfo extended_metrics = 2;
   */
  extendedMetrics: MetricInfo[] = [];

  constructor(data?: PartialMessage<GetMetricsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "panmail.v1.GetMetricsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "metrics", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "scalar", T: 3 /* ScalarType.INT64 */} },
    { no: 2, name: "extended_metrics", kind: "message", T: MetricInfo, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetMetricsResponse {
    return new GetMetricsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetMetricsResponse {
    return new GetMetricsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetMetricsResponse {
    return new GetMetricsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetMetricsResponse | PlainMessage<GetMetricsResponse> | undefined, b: GetMetricsResponse | PlainMessage<GetMetricsResponse> | undefined): boolean {
    return proto3.util.equals(GetMetricsResponse, a, b);
  }
}

/**
 * @generated from message panmail.v1.GetTimeSeriesMetricsRequest
 */
export class GetTimeSeriesMetricsRequest extends Message<GetTimeSeriesMetricsRequest> {
  /**
   * @generated from field: google.protobuf.Timestamp start_time = 1;
   */
  startTime?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp end_time = 2;
   */
  endTime?: Timestamp;

  /**
   * "minute", "hour", "day"
   *
   * @generated from field: string granularity = 3;
   */
  granularity = "";

  constructor(data?: PartialMessage<GetTimeSeriesMetricsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "panmail.v1.GetTimeSeriesMetricsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "start_time", kind: "message", T: Timestamp },
    { no: 2, name: "end_time", kind: "message", T: Timestamp },
    { no: 3, name: "granularity", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetTimeSeriesMetricsRequest {
    return new GetTimeSeriesMetricsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetTimeSeriesMetricsRequest {
    return new GetTimeSeriesMetricsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetTimeSeriesMetricsRequest {
    return new GetTimeSeriesMetricsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetTimeSeriesMetricsRequest | PlainMessage<GetTimeSeriesMetricsRequest> | undefined, b: GetTimeSeriesMetricsRequest | PlainMessage<GetTimeSeriesMetricsRequest> | undefined): boolean {
    return proto3.util.equals(GetTimeSeriesMetricsRequest, a, b);
  }
}

/**
 * @generated from message panmail.v1.TimeSeriesData
 */
export class TimeSeriesData extends Message<TimeSeriesData> {
  /**
   * @generated from field: map<string, int64> metrics = 1;
   */
  metrics: { [key: string]: bigint } = {};

  constructor(data?: PartialMessage<TimeSeriesData>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "panmail.v1.TimeSeriesData";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "metrics", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "scalar", T: 3 /* ScalarType.INT64 */} },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TimeSeriesData {
    return new TimeSeriesData().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TimeSeriesData {
    return new TimeSeriesData().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TimeSeriesData {
    return new TimeSeriesData().fromJsonString(jsonString, options);
  }

  static equals(a: TimeSeriesData | PlainMessage<TimeSeriesData> | undefined, b: TimeSeriesData | PlainMessage<TimeSeriesData> | undefined): boolean {
    return proto3.util.equals(TimeSeriesData, a, b);
  }
}

/**
 * @generated from message panmail.v1.GetTimeSeriesMetricsResponse
 */
export class GetTimeSeriesMetricsResponse extends Message<GetTimeSeriesMetricsResponse> {
  /**
   * @generated from field: map<string, panmail.v1.TimeSeriesData> data = 1;
   */
  data: { [key: string]: TimeSeriesData } = {};

  constructor(data?: PartialMessage<GetTimeSeriesMetricsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "panmail.v1.GetTimeSeriesMetricsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "data", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "message", T: TimeSeriesData} },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetTimeSeriesMetricsResponse {
    return new GetTimeSeriesMetricsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetTimeSeriesMetricsResponse {
    return new GetTimeSeriesMetricsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetTimeSeriesMetricsResponse {
    return new GetTimeSeriesMetricsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetTimeSeriesMetricsResponse | PlainMessage<GetTimeSeriesMetricsResponse> | undefined, b: GetTimeSeriesMetricsResponse | PlainMessage<GetTimeSeriesMetricsResponse> | undefined): boolean {
    return proto3.util.equals(GetTimeSeriesMetricsResponse, a, b);
  }
}

/**
 * @generated from message panmail.v1.ListEventsRequest
 */
export class ListEventsRequest extends Message<ListEventsRequest> {
  /**
   * @generated from field: int32 page_size = 1;
   */
  pageSize = 0;

  /**
   * @generated from field: string page_token = 2;
   */
  pageToken = "";

  /**
   * @generated from field: string recipient = 3;
   */
  recipient = "";

  /**
   * @generated from field: panmail.v1.EmailEventType event_type = 4;
   */
  eventType = EmailEventType.UNSPECIFIED;

  /**
   * @generated from field: google.protobuf.Timestamp start_time = 5;
   */
  startTime?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp end_time = 6;
   */
  endTime?: Timestamp;

  /**
   * @generated from field: string message_id = 7;
   */
  messageId = "";

  constructor(data?: PartialMessage<ListEventsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "panmail.v1.ListEventsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "page_size", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "page_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "recipient", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "event_type", kind: "enum", T: proto3.getEnumType(EmailEventType) },
    { no: 5, name: "start_time", kind: "message", T: Timestamp },
    { no: 6, name: "end_time", kind: "message", T: Timestamp },
    { no: 7, name: "message_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListEventsRequest {
    return new ListEventsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListEventsRequest {
    return new ListEventsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListEventsRequest {
    return new ListEventsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ListEventsRequest | PlainMessage<ListEventsRequest> | undefined, b: ListEventsRequest | PlainMessage<ListEventsRequest> | undefined): boolean {
    return proto3.util.equals(ListEventsRequest, a, b);
  }
}

/**
 * @generated from message panmail.v1.ListEventsResponse
 */
export class ListEventsResponse extends Message<ListEventsResponse> {
  /**
   * @generated from field: repeated panmail.v1.EmailEvent events = 1;
   */
  events: EmailEvent[] = [];

  /**
   * @generated from field: string next_page_token = 2;
   */
  nextPageToken = "";

  constructor(data?: PartialMessage<ListEventsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "panmail.v1.ListEventsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "events", kind: "message", T: EmailEvent, repeated: true },
    { no: 2, name: "next_page_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListEventsResponse {
    return new ListEventsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListEventsResponse {
    return new ListEventsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListEventsResponse {
    return new ListEventsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ListEventsResponse | PlainMessage<ListEventsResponse> | undefined, b: ListEventsResponse | PlainMessage<ListEventsResponse> | undefined): boolean {
    return proto3.util.equals(ListEventsResponse, a, b);
  }
}

