// @generated by protoc-gen-es v2.14.0 with parameter "target=ts,import_extension=none"
// @generated from file panmail/v1/inbound.proto (package panmail.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file panmail/v1/inbound.proto.
 */
export const file_panmail_v1_inbound: GenFile = /*@__PURE__*/
  fileDesc("ChhwYW5tYWlsL3YxL2luYm91bmQucHJvdG8SCnBhbm1haWwudjEilQIKDEluYm91bmRFbWFpbBIKCgJpZBgBIAEoCRIRCgl0ZW5hbnRfaWQYAiABKAkSDAoEZnJvbRgDIAEoCRIKCgJ0bxgEIAMoCRIPCgdzdWJqZWN0GAUgASgJEhEKCWJvZHlfaHRtbBgGIAEoCRIRCglib2R5X3RleHQYByABKAkSLQoJdGltZXN0YW1wGAggASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBI2CgdoZWFkZXJzGAkgAygLMiUucGFubWFpbC52MS5JbmJvdW5kRW1haWwuSGVhZGVyc0VudHJ5Gi4KDEhlYWRlcnNFbnRyeRILCgNrZXkYASABKAkSDQoFdmFsdWUYAiABKAk6AjgBQp0BCg5jb20ucGFubWFpbC52MUIMSW5ib3VuZFByb3RvUAFaNGdpdGh1Yi5jb20vZ3NvdWx0YW4vcGFubWFpbC9hcGkvcGFubWFpbC92MTtwYW5tYWlsdjGiAgNQWFiqAgpQYW5tYWlsLlYxygIKUGFubWFpbFxWMeICFlBhbm1haWxcVjFcR1BCTWV0YWRhdGHqAgtQYW5tYWlsOjpWMWIGcHJvdG8z", [file_google_protobuf_timestamp]);

/**
 * @generated from message panmail.v1.InboundEmail
 */
export type InboundEmail = Message<"panmail.v1.InboundEmail"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string tenant_id = 2;
   */
  tenantId: string;

  /**
   * @generated from field: string from = 3;
   */
  from: string;

  /**
   * @generated from field: repeated string to = 4;
   */
  to: string[];

  /**
   * @generated from field: string subject = 5;
   */
  subject: string;

  /**
   * @generated from field: string body_html = 6;
   */
  bodyHtml: string;

  /**
   * @generated from field: string body_text = 7;
   */
  bodyText: string;

  /**
   * @generated from field: google.protobuf.Timestamp timestamp = 8;
   */
  timestamp?: Timestamp | undefined;

  /**
   * @generated from field: map<string, string> headers = 9;
   */
  headers: { [key: string]: string };
};

/**
 * Describes the message panmail.v1.InboundEmail.
 * Use `create(InboundEmailSchema)` to create a new message.
 */
export const InboundEmailSchema: GenMessage<InboundEmail> = /*@__PURE__*/
  messageDesc(file_panmail_v1_inbound, 0);

