// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file panmail/v1/inbound_service.proto (package panmail.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetInboundEmailRequest, GetInboundEmailResponse, ListInboundEmailsRequest, ListInboundEmailsResponse } from "./inbound_service_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service panmail.v1.InboundService
 */
export const InboundService = {
  typeName: "panmail.v1.InboundService",
  methods: {
    /**
     * @generated from rpc panmail.v1.InboundService.ListInboundEmails
     */
    listInboundEmails: {
      name: "ListInboundEmails",
      I: ListInboundEmailsRequest,
      O: ListInboundEmailsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc panmail.v1.InboundService.GetInboundEmail
     */
    getInboundEmail: {
      name: "GetInboundEmail",
      I: GetInboundEmailRequest,
      O: GetInboundEmailResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

