// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file panmail/v1/setup.proto (package panmail.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetSetupStatusRequest, GetSetupStatusResponse, SetupRequest, SetupResponse, TestDatabaseConnectionRequest, TestDatabaseConnectionResponse } from "./setup_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service panmail.v1.SetupService
 */
export const SetupService = {
  typeName: "panmail.v1.SetupService",
  methods: {
    /**
     * @generated from rpc panmail.v1.SetupService.GetSetupStatus
     */
    getSetupStatus: {
      name: "GetSetupStatus",
      I: GetSetupStatusRequest,
      O: GetSetupStatusResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc panmail.v1.SetupService.Setup
     */
    setup: {
      name: "Setup",
      I: SetupRequest,
      O: SetupResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc panmail.v1.SetupService.TestDatabaseConnection
     */
    testDatabaseConnection: {
      name: "TestDatabaseConnection",
      I: TestDatabaseConnectionRequest,
      O: TestDatabaseConnectionResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

