// @generated by protoc-gen-es v2.14.0 with parameter "target=ts,import_extension=none"
// @generated from file panmail/v1/suppression.proto (package panmail.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file panmail/v1/suppression.proto.
 */
export const file_panmail_v1_suppression: GenFile = /*@__PURE__*/
  fileDesc("ChxwYW5tYWlsL3YxL3N1cHByZXNzaW9uLnByb3RvEgpwYW5tYWlsLnYxInwKC1N1cHByZXNzaW9uEgoKAmlkGAEgASgJEhEKCXRlbmFudF9pZBgCIAEoCRINCgVlbWFpbBgDIAEoCRIOCgZyZWFzb24YBCABKAkSLwoLY3JlYXRlX3RpbWUYBSABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wQqEBCg5jb20ucGFubWFpbC52MUIQU3VwcHJlc3Npb25Qcm90b1ABWjRnaXRodWIuY29tL2dzb3VsdGFuL3Bhbm1haWwvYXBpL3Bhbm1haWwvdjE7cGFubWFpbHYxogIDUFhYqgIKUGFubWFpbC5WMcoCClBhbm1haWxcVjHiAhZQYW5tYWlsXFYxXEdQQk1ldGFkYXRh6gILUGFubWFpbDo6VjFiBnByb3RvMw", [file_google_protobuf_timestamp]);

/**
 * @generated from message panmail.v1.Suppression
 */
export type Suppression = Message<"panmail.v1.Suppression"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string tenant_id = 2;
   */
  tenantId: string;

  /**
   * @generated from field: string email = 3;
   */
  email: string;

  /**
   * @generated from field: string reason = 4;
   */
  reason: string;

  /**
   * @generated from field: google.protobuf.Timestamp create_time = 5;
   */
  createTime?: Timestamp | undefined;
};

/**
 * Describes the message panmail.v1.Suppression.
 * Use `create(SuppressionSchema)` to create a new message.
 */
export const SuppressionSchema: GenMessage<Suppression> = /*@__PURE__*/
  messageDesc(file_panmail_v1_suppression, 0);

