// @generated by protoc-gen-es v2.14.0 with parameter "target=ts,import_extension=none"
// @generated from file panmail/v1/system_settings.proto (package panmail.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file panmail/v1/system_settings.proto.
 */
export const file_panmail_v1_system_settings: GenFile = /*@__PURE__*/
  fileDesc("CiBwYW5tYWlsL3YxL3N5c3RlbV9zZXR0aW5ncy5wcm90bxIKcGFubWFpbC52MSIUChJHZXRTZXR0aW5nc1JlcXVlc3QieAoTR2V0U2V0dGluZ3NSZXNwb25zZRIsCghzZXR0aW5ncxgBIAEoCzIaLnBhbm1haWwudjEuU3lzdGVtU2V0dGluZ3MSMwoPc210cF9zdWJtaXNzaW9uGAIgASgLMhoucGFubWFpbC52MS5TbXRwU3VibWlzc2lvbiJFChVVcGRhdGVTZXR0aW5nc1JlcXVlc3QSLAoIc2V0dGluZ3MYASABKAsyGi5wYW5tYWlsLnYxLlN5c3RlbVNldHRpbmdzIkYKFlVwZGF0ZVNldHRpbmdzUmVzcG9uc2USLAoIc2V0dGluZ3MYASABKAsyGi5wYW5tYWlsLnYxLlN5c3RlbVNldHRpbmdzIm4KDlNtdHBTdWJtaXNzaW9uEg8KB2VuYWJsZWQYASABKAgSDAoEaG9zdBgCIAEoCRIMCgRwb3J0GAMgASgFEhAKCHN0YXJ0dGxzGAQgASgIEh0KFWluc2VjdXJlX2F1dGhfYWxsb3dlZBgFIAEoCCLwAgoOU3lzdGVtU2V0dGluZ3MSEAoIYmFzZV91cmwYASABKAkSGgoSbG9nX3JldGVudGlvbl9kYXlzGAIgASgFEhUKDXJldHJ5X3BhdHRlcm4YAyADKAkSHgoWbWVzc2FnZV9yZXRlbnRpb25fZGF5cxgEIAEoBRIdChVvdXRib3hfcmV0ZW50aW9uX2RheXMYBSABKAUSHgoWd2ViaG9va19yZXRlbnRpb25fZGF5cxgGIAEoBRIeChZhcHBfbG9nX3JldGVudGlvbl9kYXlzGAcgASgFEh4KFmluYm91bmRfcmV0ZW50aW9uX2RheXMYCCABKAUSHgoWYXJjaGl2ZV9yZXRlbnRpb25fZGF5cxgJIAEoBRIhChlxdWFyYW50aW5lX3JldGVudGlvbl9kYXlzGAogASgFEjcKEWNvbnRlbnRfcmVkYWN0aW9uGAsgASgOMhwucGFubWFpbC52MS5Db250ZW50UmVkYWN0aW9uKq0BChBDb250ZW50UmVkYWN0aW9uEiEKHUNPTlRFTlRfUkVEQUNUSU9OX1VOU1BFQ0lGSUVEEAASGQoVQ09OVEVOVF9SRURBQ1RJT05fT0ZGEAESHwobQ09OVEVOVF9SRURBQ1RJT05fUEFTU1dPUkRTEAISGwoXQ09OVEVOVF9SRURBQ1RJT05fQ09ERVMQAxIdChlDT05URU5UX1JFREFDVElPTl9TRUNSRVRTEAQywAEKFVN5c3RlbVNldHRpbmdzU2VydmljZRJOCgtHZXRTZXR0aW5ncxIeLnBhbm1haWwudjEuR2V0U2V0dGluZ3NSZXF1ZXN0Gh8ucGFubWFpbC52MS5HZXRTZXR0aW5nc1Jlc3BvbnNlElcKDlVwZGF0ZVNldHRpbmdzEiEucGFubWFpbC52MS5VcGRhdGVTZXR0aW5nc1JlcXVlc3QaIi5wYW5tYWlsLnYxLlVwZGF0ZVNldHRpbmdzUmVzcG9uc2VCpAEKDmNvbS5wYW5tYWlsLnYxQhNTeXN0ZW1TZXR0aW5nc1Byb3RvUAFaNGdpdGh1Yi5jb20vZ3NvdWx0YW4vcGFubWFpbC9hcGkvcGFubWFpbC92MTtwYW5tYWlsdjGiAgNQWFiqAgpQYW5tYWlsLlYxygIKUGFubWFpbFxWMeICFlBhbm1haWxcVjFcR1BCTWV0YWRhdGHqAgtQYW5tYWlsOjpWMWIGcHJvdG8z");

/**
 * @generated from message panmail.v1.GetSettingsRequest
 */
export type GetSettingsRequest = Message<"panmail.v1.GetSettingsRequest"> & {
};

/**
 * Describes the message panmail.v1.GetSettingsRequest.
 * Use `create(GetSettingsRequestSchema)` to create a new message.
 */
export const GetSettingsRequestSchema: GenMessage<GetSettingsRequest> = /*@__PURE__*/
  messageDesc(file_panmail_v1_system_settings, 0);

/**
 * @generated from message panmail.v1.GetSettingsResponse
 */
export type GetSettingsResponse = Message<"panmail.v1.GetSettingsResponse"> & {
  /**
   * @generated from field: panmail.v1.SystemSettings settings = 1;
   */
  settings?: SystemSettings | undefined;

  /**
   * How this process is accepting SMTP submissions. Read-only: it reports
   * process state, not configuration, and UpdateSettings does not accept it.
   *
   * @generated from field: panmail.v1.SmtpSubmission smtp_submission = 2;
   */
  smtpSubmission?: SmtpSubmission | undefined;
};

/**
 * Describes the message panmail.v1.GetSettingsResponse.
 * Use `create(GetSettingsResponseSchema)` to create a new message.
 */
export const GetSettingsResponseSchema: GenMessage<GetSettingsResponse> = /*@__PURE__*/
  messageDesc(file_panmail_v1_system_settings, 1);

/**
 * @generated from message panmail.v1.UpdateSettingsRequest
 */
export type UpdateSettingsRequest = Message<"panmail.v1.UpdateSettingsRequest"> & {
  /**
   * @generated from field: panmail.v1.SystemSettings settings = 1;
   */
  settings?: SystemSettings | undefined;
};

/**
 * Describes the message panmail.v1.UpdateSettingsRequest.
 * Use `create(UpdateSettingsRequestSchema)` to create a new message.
 */
export const UpdateSettingsRequestSchema: GenMessage<UpdateSettingsRequest> = /*@__PURE__*/
  messageDesc(file_panmail_v1_system_settings, 2);

/**
 * @generated from message panmail.v1.UpdateSettingsResponse
 */
export type UpdateSettingsResponse = Message<"panmail.v1.UpdateSettingsResponse"> & {
  /**
   * @generated from field: panmail.v1.SystemSettings settings = 1;
   */
  settings?: SystemSettings | undefined;
};

/**
 * Describes the message panmail.v1.UpdateSettingsResponse.
 * Use `create(UpdateSettingsResponseSchema)` to create a new message.
 */
export const UpdateSettingsResponseSchema: GenMessage<UpdateSettingsResponse> = /*@__PURE__*/
  messageDesc(file_panmail_v1_system_settings, 3);

/**
 * SmtpSubmission reports the SMTP submission listener, so the dashboard can
 * show an integrator real connection details instead of guessing at them.
 *
 * It is deliberately not part of SystemSettings. The listener is configured by
 * process flags and cannot be changed by an administrator at runtime, and a
 * field that appears in an editable form but silently ignores edits is worse
 * than one that is absent.
 *
 * @generated from message panmail.v1.SmtpSubmission
 */
export type SmtpSubmission = Message<"panmail.v1.SmtpSubmission"> & {
  /**
   * Whether this process is listening for submissions at all.
   *
   * @generated from field: bool enabled = 1;
   */
  enabled: boolean;

  /**
   * The hostname clients should connect to, empty when the listener binds
   * every interface. A wildcard bind gives no hostname worth reporting, and
   * inventing one would send integrators somewhere that does not answer; the
   * dashboard falls back to the host in base_url and says what it did.
   *
   * @generated from field: string host = 2;
   */
  host: string;

  /**
   * @generated from field: int32 port = 3;
   */
  port: number;

  /**
   * Whether the listener offers STARTTLS.
   *
   * @generated from field: bool starttls = 4;
   */
  starttls: boolean;

  /**
   * Whether AUTH is accepted on an unencrypted connection. True means an API
   * key can cross the network in the clear, which is a deployment decision
   * worth showing rather than burying in a log line at startup.
   *
   * @generated from field: bool insecure_auth_allowed = 5;
   */
  insecureAuthAllowed: boolean;
};

/**
 * Describes the message panmail.v1.SmtpSubmission.
 * Use `create(SmtpSubmissionSchema)` to create a new message.
 */
export const SmtpSubmissionSchema: GenMessage<SmtpSubmission> = /*@__PURE__*/
  messageDesc(file_panmail_v1_system_settings, 4);

/**
 * SystemSettings holds the global, admin-editable configuration.
 *
 * Every *_retention_days field is a whole number of days, and zero always
 * means "keep forever" — a retention nobody has configured must never delete
 * anything. The UI says so on each field; do not add a field whose zero value
 * means something else.
 *
 * @generated from message panmail.v1.SystemSettings
 */
export type SystemSettings = Message<"panmail.v1.SystemSettings"> & {
  /**
   * @generated from field: string base_url = 1;
   */
  baseUrl: string;

  /**
   * @generated from field: int32 log_retention_days = 2;
   */
  logRetentionDays: number;

  /**
   * @generated from field: repeated string retry_pattern = 3;
   */
  retryPattern: string[];

  /**
   * Message bodies and attachments, deleted outright rather than archived:
   * an archive of the content is the content, so archiving it would defeat
   * the retention it is meant to enforce.
   *
   * @generated from field: int32 message_retention_days = 4;
   */
  messageRetentionDays: number;

  /**
   * Permanently failed outbox rows. Only FAILED qualifies — pending,
   * deferred and claimed rows are live work.
   *
   * @generated from field: int32 outbox_retention_days = 5;
   */
  outboxRetentionDays: number;

  /**
   * Delivered and permanently failed webhook notifications.
   *
   * @generated from field: int32 webhook_retention_days = 6;
   */
  webhookRetentionDays: number;

  /**
   * Application logs from the Pebble log store.
   *
   * @generated from field: int32 app_log_retention_days = 7;
   */
  appLogRetentionDays: number;

  /**
   * Received mail. Deleting inbound mail destroys the only copy panmail
   * holds, so this defaults to keeping it forever.
   *
   * @generated from field: int32 inbound_retention_days = 8;
   */
  inboundRetentionDays: number;

  /**
   * The JSONL archives written when delivery events expire. This is the
   * escape hatch for log_retention_days, so it also defaults to forever.
   *
   * @generated from field: int32 archive_retention_days = 9;
   */
  archiveRetentionDays: number;

  /**
   * How long a message a filter rule held waits for a reviewer.
   *
   * Applies to messages held from now on, not to ones already waiting. Their
   * deadline was stamped when they were held and sent to webhook subscribers
   * in the mail.held event; moving it afterwards would break a date this
   * gateway already promised.
   *
   * @generated from field: int32 quarantine_retention_days = 10;
   */
  quarantineRetentionDays: number;

  /**
   * How much of a stored message body the delivery-details view is allowed to
   * show. Transactional mail carries the things it carries — a password reset
   * sends a password — and anyone who can open the dashboard can read it back
   * months later.
   *
   * Redaction happens in the gateway, not the browser: the body is served over
   * the API, so masking it in the UI would leave the secret in the response for
   * anyone who opens the network tab. Stored mail is never rewritten; only what
   * leaves through the API is masked.
   *
   * @generated from field: panmail.v1.ContentRedaction content_redaction = 11;
   */
  contentRedaction: ContentRedaction;
};

/**
 * Describes the message panmail.v1.SystemSettings.
 * Use `create(SystemSettingsSchema)` to create a new message.
 */
export const SystemSettingsSchema: GenMessage<SystemSettings> = /*@__PURE__*/
  messageDesc(file_panmail_v1_system_settings, 5);

/**
 * ContentRedaction is how hard the gateway looks for secrets in a message body
 * before showing it back.
 *
 * UNSPECIFIED is distinct from OFF on purpose, and it is the same distinction
 * the two nullable retention columns exist for: "nobody has chosen" has to be
 * tellable from "somebody chose none", or an operator who deliberately turned
 * redaction off gets it switched back on by the next default change.
 *
 * @generated from enum panmail.v1.ContentRedaction
 */
export enum ContentRedaction {
  /**
   * @generated from enum value: CONTENT_REDACTION_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Show the body as stored. A deliberate choice, and the only value that
   * shows a password in the dashboard.
   *
   * @generated from enum value: CONTENT_REDACTION_OFF = 1;
   */
  OFF = 1,

  /**
   * The default. Masks the value after a password-like label — password, pwd,
   * passcode, passphrase — and nothing else. Narrow so that a message which
   * merely discusses passwords survives intact.
   *
   * @generated from enum value: CONTENT_REDACTION_PASSWORDS = 2;
   */
  PASSWORDS = 2,

  /**
   * Adds one-time codes: OTP, PIN, verification and security codes. Worth as
   * much as a password for as long as they are valid, which is usually longer
   * than the message takes to reach the dashboard.
   *
   * @generated from enum value: CONTENT_REDACTION_CODES = 3;
   */
  CODES = 3,

  /**
   * Adds bearer tokens and API keys. The widest setting and the most likely to
   * mask something that was not a secret.
   *
   * @generated from enum value: CONTENT_REDACTION_SECRETS = 4;
   */
  SECRETS = 4,
}

/**
 * Describes the enum panmail.v1.ContentRedaction.
 */
export const ContentRedactionSchema: GenEnum<ContentRedaction> = /*@__PURE__*/
  enumDesc(file_panmail_v1_system_settings, 0);

/**
 * @generated from service panmail.v1.SystemSettingsService
 */
export const SystemSettingsService: GenService<{
  /**
   * @generated from rpc panmail.v1.SystemSettingsService.GetSettings
   */
  getSettings: {
    methodKind: "unary";
    input: typeof GetSettingsRequestSchema;
    output: typeof GetSettingsResponseSchema;
  },
  /**
   * @generated from rpc panmail.v1.SystemSettingsService.UpdateSettings
   */
  updateSettings: {
    methodKind: "unary";
    input: typeof UpdateSettingsRequestSchema;
    output: typeof UpdateSettingsResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_panmail_v1_system_settings, 0);

