// @generated by protoc-gen-es v2.14.0 with parameter "target=ts,import_extension=none"
// @generated from file panmail/v1/system_settings.proto (package panmail.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file panmail/v1/system_settings.proto.
 */
export const file_panmail_v1_system_settings: GenFile = /*@__PURE__*/
  fileDesc("CiBwYW5tYWlsL3YxL3N5c3RlbV9zZXR0aW5ncy5wcm90bxIKcGFubWFpbC52MSIUChJHZXRTZXR0aW5nc1JlcXVlc3QiQwoTR2V0U2V0dGluZ3NSZXNwb25zZRIsCghzZXR0aW5ncxgBIAEoCzIaLnBhbm1haWwudjEuU3lzdGVtU2V0dGluZ3MiRQoVVXBkYXRlU2V0dGluZ3NSZXF1ZXN0EiwKCHNldHRpbmdzGAEgASgLMhoucGFubWFpbC52MS5TeXN0ZW1TZXR0aW5ncyJGChZVcGRhdGVTZXR0aW5nc1Jlc3BvbnNlEiwKCHNldHRpbmdzGAEgASgLMhoucGFubWFpbC52MS5TeXN0ZW1TZXR0aW5ncyKUAgoOU3lzdGVtU2V0dGluZ3MSEAoIYmFzZV91cmwYASABKAkSGgoSbG9nX3JldGVudGlvbl9kYXlzGAIgASgFEhUKDXJldHJ5X3BhdHRlcm4YAyADKAkSHgoWbWVzc2FnZV9yZXRlbnRpb25fZGF5cxgEIAEoBRIdChVvdXRib3hfcmV0ZW50aW9uX2RheXMYBSABKAUSHgoWd2ViaG9va19yZXRlbnRpb25fZGF5cxgGIAEoBRIeChZhcHBfbG9nX3JldGVudGlvbl9kYXlzGAcgASgFEh4KFmluYm91bmRfcmV0ZW50aW9uX2RheXMYCCABKAUSHgoWYXJjaGl2ZV9yZXRlbnRpb25fZGF5cxgJIAEoBTLAAQoVU3lzdGVtU2V0dGluZ3NTZXJ2aWNlEk4KC0dldFNldHRpbmdzEh4ucGFubWFpbC52MS5HZXRTZXR0aW5nc1JlcXVlc3QaHy5wYW5tYWlsLnYxLkdldFNldHRpbmdzUmVzcG9uc2USVwoOVXBkYXRlU2V0dGluZ3MSIS5wYW5tYWlsLnYxLlVwZGF0ZVNldHRpbmdzUmVxdWVzdBoiLnBhbm1haWwudjEuVXBkYXRlU2V0dGluZ3NSZXNwb25zZUKkAQoOY29tLnBhbm1haWwudjFCE1N5c3RlbVNldHRpbmdzUHJvdG9QAVo0Z2l0aHViLmNvbS9nc291bHRhbi9wYW5tYWlsL2FwaS9wYW5tYWlsL3YxO3Bhbm1haWx2MaICA1BYWKoCClBhbm1haWwuVjHKAgpQYW5tYWlsXFYx4gIWUGFubWFpbFxWMVxHUEJNZXRhZGF0YeoCC1Bhbm1haWw6OlYxYgZwcm90bzM");

/**
 * @generated from message panmail.v1.GetSettingsRequest
 */
export type GetSettingsRequest = Message<"panmail.v1.GetSettingsRequest"> & {
};

/**
 * Describes the message panmail.v1.GetSettingsRequest.
 * Use `create(GetSettingsRequestSchema)` to create a new message.
 */
export const GetSettingsRequestSchema: GenMessage<GetSettingsRequest> = /*@__PURE__*/
  messageDesc(file_panmail_v1_system_settings, 0);

/**
 * @generated from message panmail.v1.GetSettingsResponse
 */
export type GetSettingsResponse = Message<"panmail.v1.GetSettingsResponse"> & {
  /**
   * @generated from field: panmail.v1.SystemSettings settings = 1;
   */
  settings?: SystemSettings | undefined;
};

/**
 * Describes the message panmail.v1.GetSettingsResponse.
 * Use `create(GetSettingsResponseSchema)` to create a new message.
 */
export const GetSettingsResponseSchema: GenMessage<GetSettingsResponse> = /*@__PURE__*/
  messageDesc(file_panmail_v1_system_settings, 1);

/**
 * @generated from message panmail.v1.UpdateSettingsRequest
 */
export type UpdateSettingsRequest = Message<"panmail.v1.UpdateSettingsRequest"> & {
  /**
   * @generated from field: panmail.v1.SystemSettings settings = 1;
   */
  settings?: SystemSettings | undefined;
};

/**
 * Describes the message panmail.v1.UpdateSettingsRequest.
 * Use `create(UpdateSettingsRequestSchema)` to create a new message.
 */
export const UpdateSettingsRequestSchema: GenMessage<UpdateSettingsRequest> = /*@__PURE__*/
  messageDesc(file_panmail_v1_system_settings, 2);

/**
 * @generated from message panmail.v1.UpdateSettingsResponse
 */
export type UpdateSettingsResponse = Message<"panmail.v1.UpdateSettingsResponse"> & {
  /**
   * @generated from field: panmail.v1.SystemSettings settings = 1;
   */
  settings?: SystemSettings | undefined;
};

/**
 * Describes the message panmail.v1.UpdateSettingsResponse.
 * Use `create(UpdateSettingsResponseSchema)` to create a new message.
 */
export const UpdateSettingsResponseSchema: GenMessage<UpdateSettingsResponse> = /*@__PURE__*/
  messageDesc(file_panmail_v1_system_settings, 3);

/**
 * SystemSettings holds the global, admin-editable configuration.
 *
 * Every *_retention_days field is a whole number of days, and zero always
 * means "keep forever" — a retention nobody has configured must never delete
 * anything. The UI says so on each field; do not add a field whose zero value
 * means something else.
 *
 * @generated from message panmail.v1.SystemSettings
 */
export type SystemSettings = Message<"panmail.v1.SystemSettings"> & {
  /**
   * @generated from field: string base_url = 1;
   */
  baseUrl: string;

  /**
   * @generated from field: int32 log_retention_days = 2;
   */
  logRetentionDays: number;

  /**
   * @generated from field: repeated string retry_pattern = 3;
   */
  retryPattern: string[];

  /**
   * Message bodies and attachments, deleted outright rather than archived:
   * an archive of the content is the content, so archiving it would defeat
   * the retention it is meant to enforce.
   *
   * @generated from field: int32 message_retention_days = 4;
   */
  messageRetentionDays: number;

  /**
   * Permanently failed outbox rows. Only FAILED qualifies — pending,
   * deferred and claimed rows are live work.
   *
   * @generated from field: int32 outbox_retention_days = 5;
   */
  outboxRetentionDays: number;

  /**
   * Delivered and permanently failed webhook notifications.
   *
   * @generated from field: int32 webhook_retention_days = 6;
   */
  webhookRetentionDays: number;

  /**
   * Application logs from the Pebble log store.
   *
   * @generated from field: int32 app_log_retention_days = 7;
   */
  appLogRetentionDays: number;

  /**
   * Received mail. Deleting inbound mail destroys the only copy panmail
   * holds, so this defaults to keeping it forever.
   *
   * @generated from field: int32 inbound_retention_days = 8;
   */
  inboundRetentionDays: number;

  /**
   * The JSONL archives written when delivery events expire. This is the
   * escape hatch for log_retention_days, so it also defaults to forever.
   *
   * @generated from field: int32 archive_retention_days = 9;
   */
  archiveRetentionDays: number;
};

/**
 * Describes the message panmail.v1.SystemSettings.
 * Use `create(SystemSettingsSchema)` to create a new message.
 */
export const SystemSettingsSchema: GenMessage<SystemSettings> = /*@__PURE__*/
  messageDesc(file_panmail_v1_system_settings, 4);

/**
 * @generated from service panmail.v1.SystemSettingsService
 */
export const SystemSettingsService: GenService<{
  /**
   * @generated from rpc panmail.v1.SystemSettingsService.GetSettings
   */
  getSettings: {
    methodKind: "unary";
    input: typeof GetSettingsRequestSchema;
    output: typeof GetSettingsResponseSchema;
  },
  /**
   * @generated from rpc panmail.v1.SystemSettingsService.UpdateSettings
   */
  updateSettings: {
    methodKind: "unary";
    input: typeof UpdateSettingsRequestSchema;
    output: typeof UpdateSettingsResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_panmail_v1_system_settings, 0);

