// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file panmail/v1/system_settings.proto (package panmail.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetSettingsRequest, GetSettingsResponse, UpdateSettingsRequest, UpdateSettingsResponse } from "./system_settings_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service panmail.v1.SystemSettingsService
 */
export const SystemSettingsService = {
  typeName: "panmail.v1.SystemSettingsService",
  methods: {
    /**
     * @generated from rpc panmail.v1.SystemSettingsService.GetSettings
     */
    getSettings: {
      name: "GetSettings",
      I: GetSettingsRequest,
      O: GetSettingsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc panmail.v1.SystemSettingsService.UpdateSettings
     */
    updateSettings: {
      name: "UpdateSettings",
      I: UpdateSettingsRequest,
      O: UpdateSettingsResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

