// @generated by protoc-gen-es v2.14.0 with parameter "target=ts,import_extension=none"
// @generated from file panmail/v1/template.proto (package panmail.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file panmail/v1/template.proto.
 */
export const file_panmail_v1_template: GenFile = /*@__PURE__*/
  fileDesc("ChlwYW5tYWlsL3YxL3RlbXBsYXRlLnByb3RvEgpwYW5tYWlsLnYxIuABCghUZW1wbGF0ZRIKCgJpZBgBIAEoCRIRCgl0ZW5hbnRfaWQYAiABKAkSDAoEbmFtZRgDIAEoCRIPCgdzdWJqZWN0GAQgASgJEhEKCWJvZHlfaHRtbBgFIAEoCRIRCglib2R5X3RleHQYBiABKAkSDgoGZGVzaWduGAkgASgJEi8KC2NyZWF0ZV90aW1lGAcgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIvCgt1cGRhdGVfdGltZRgIIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXBCngEKDmNvbS5wYW5tYWlsLnYxQg1UZW1wbGF0ZVByb3RvUAFaNGdpdGh1Yi5jb20vZ3NvdWx0YW4vcGFubWFpbC9hcGkvcGFubWFpbC92MTtwYW5tYWlsdjGiAgNQWFiqAgpQYW5tYWlsLlYxygIKUGFubWFpbFxWMeICFlBhbm1haWxcVjFcR1BCTWV0YWRhdGHqAgtQYW5tYWlsOjpWMWIGcHJvdG8z", [file_google_protobuf_timestamp]);

/**
 * @generated from message panmail.v1.Template
 */
export type Template = Message<"panmail.v1.Template"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string tenant_id = 2;
   */
  tenantId: string;

  /**
   * @generated from field: string name = 3;
   */
  name: string;

  /**
   * @generated from field: string subject = 4;
   */
  subject: string;

  /**
   * @generated from field: string body_html = 5;
   */
  bodyHtml: string;

  /**
   * @generated from field: string body_text = 6;
   */
  bodyText: string;

  /**
   * @generated from field: string design = 9;
   */
  design: string;

  /**
   * @generated from field: google.protobuf.Timestamp create_time = 7;
   */
  createTime?: Timestamp | undefined;

  /**
   * @generated from field: google.protobuf.Timestamp update_time = 8;
   */
  updateTime?: Timestamp | undefined;
};

/**
 * Describes the message panmail.v1.Template.
 * Use `create(TemplateSchema)` to create a new message.
 */
export const TemplateSchema: GenMessage<Template> = /*@__PURE__*/
  messageDesc(file_panmail_v1_template, 0);

