// @generated by protoc-gen-es v2.14.0 with parameter "target=ts,import_extension=none"
// @generated from file panmail/v1/template_service.proto (package panmail.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Template } from "./template_pb";
import { file_panmail_v1_template } from "./template_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file panmail/v1/template_service.proto.
 */
export const file_panmail_v1_template_service: GenFile = /*@__PURE__*/
  fileDesc("CiFwYW5tYWlsL3YxL3RlbXBsYXRlX3NlcnZpY2UucHJvdG8SCnBhbm1haWwudjEibAoVQ3JlYXRlVGVtcGxhdGVSZXF1ZXN0EgwKBG5hbWUYASABKAkSDwoHc3ViamVjdBgCIAEoCRIRCglib2R5X2h0bWwYAyABKAkSEQoJYm9keV90ZXh0GAQgASgJEg4KBmRlc2lnbhgFIAEoCSJAChZDcmVhdGVUZW1wbGF0ZVJlc3BvbnNlEiYKCHRlbXBsYXRlGAEgASgLMhQucGFubWFpbC52MS5UZW1wbGF0ZSIgChJHZXRUZW1wbGF0ZVJlcXVlc3QSCgoCaWQYASABKAkiPQoTR2V0VGVtcGxhdGVSZXNwb25zZRImCgh0ZW1wbGF0ZRgBIAEoCzIULnBhbm1haWwudjEuVGVtcGxhdGUiPQoUTGlzdFRlbXBsYXRlc1JlcXVlc3QSEQoJcGFnZV9zaXplGAEgASgFEhIKCnBhZ2VfdG9rZW4YAiABKAkiWQoVTGlzdFRlbXBsYXRlc1Jlc3BvbnNlEicKCXRlbXBsYXRlcxgBIAMoCzIULnBhbm1haWwudjEuVGVtcGxhdGUSFwoPbmV4dF9wYWdlX3Rva2VuGAIgASgJIngKFVVwZGF0ZVRlbXBsYXRlUmVxdWVzdBIKCgJpZBgBIAEoCRIMCgRuYW1lGAIgASgJEg8KB3N1YmplY3QYAyABKAkSEQoJYm9keV9odG1sGAQgASgJEhEKCWJvZHlfdGV4dBgFIAEoCRIOCgZkZXNpZ24YBiABKAkiQAoWVXBkYXRlVGVtcGxhdGVSZXNwb25zZRImCgh0ZW1wbGF0ZRgBIAEoCzIULnBhbm1haWwudjEuVGVtcGxhdGUiIwoVRGVsZXRlVGVtcGxhdGVSZXF1ZXN0EgoKAmlkGAEgASgJIhgKFkRlbGV0ZVRlbXBsYXRlUmVzcG9uc2UywgMKD1RlbXBsYXRlU2VydmljZRJXCg5DcmVhdGVUZW1wbGF0ZRIhLnBhbm1haWwudjEuQ3JlYXRlVGVtcGxhdGVSZXF1ZXN0GiIucGFubWFpbC52MS5DcmVhdGVUZW1wbGF0ZVJlc3BvbnNlEk4KC0dldFRlbXBsYXRlEh4ucGFubWFpbC52MS5HZXRUZW1wbGF0ZVJlcXVlc3QaHy5wYW5tYWlsLnYxLkdldFRlbXBsYXRlUmVzcG9uc2USVAoNTGlzdFRlbXBsYXRlcxIgLnBhbm1haWwudjEuTGlzdFRlbXBsYXRlc1JlcXVlc3QaIS5wYW5tYWlsLnYxLkxpc3RUZW1wbGF0ZXNSZXNwb25zZRJXCg5VcGRhdGVUZW1wbGF0ZRIhLnBhbm1haWwudjEuVXBkYXRlVGVtcGxhdGVSZXF1ZXN0GiIucGFubWFpbC52MS5VcGRhdGVUZW1wbGF0ZVJlc3BvbnNlElcKDkRlbGV0ZVRlbXBsYXRlEiEucGFubWFpbC52MS5EZWxldGVUZW1wbGF0ZVJlcXVlc3QaIi5wYW5tYWlsLnYxLkRlbGV0ZVRlbXBsYXRlUmVzcG9uc2VCpQEKDmNvbS5wYW5tYWlsLnYxQhRUZW1wbGF0ZVNlcnZpY2VQcm90b1ABWjRnaXRodWIuY29tL2dzb3VsdGFuL3Bhbm1haWwvYXBpL3Bhbm1haWwvdjE7cGFubWFpbHYxogIDUFhYqgIKUGFubWFpbC5WMcoCClBhbm1haWxcVjHiAhZQYW5tYWlsXFYxXEdQQk1ldGFkYXRh6gILUGFubWFpbDo6VjFiBnByb3RvMw", [file_panmail_v1_template]);

/**
 * @generated from message panmail.v1.CreateTemplateRequest
 */
export type CreateTemplateRequest = Message<"panmail.v1.CreateTemplateRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string subject = 2;
   */
  subject: string;

  /**
   * @generated from field: string body_html = 3;
   */
  bodyHtml: string;

  /**
   * @generated from field: string body_text = 4;
   */
  bodyText: string;

  /**
   * @generated from field: string design = 5;
   */
  design: string;
};

/**
 * Describes the message panmail.v1.CreateTemplateRequest.
 * Use `create(CreateTemplateRequestSchema)` to create a new message.
 */
export const CreateTemplateRequestSchema: GenMessage<CreateTemplateRequest> = /*@__PURE__*/
  messageDesc(file_panmail_v1_template_service, 0);

/**
 * @generated from message panmail.v1.CreateTemplateResponse
 */
export type CreateTemplateResponse = Message<"panmail.v1.CreateTemplateResponse"> & {
  /**
   * @generated from field: panmail.v1.Template template = 1;
   */
  template?: Template | undefined;
};

/**
 * Describes the message panmail.v1.CreateTemplateResponse.
 * Use `create(CreateTemplateResponseSchema)` to create a new message.
 */
export const CreateTemplateResponseSchema: GenMessage<CreateTemplateResponse> = /*@__PURE__*/
  messageDesc(file_panmail_v1_template_service, 1);

/**
 * @generated from message panmail.v1.GetTemplateRequest
 */
export type GetTemplateRequest = Message<"panmail.v1.GetTemplateRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message panmail.v1.GetTemplateRequest.
 * Use `create(GetTemplateRequestSchema)` to create a new message.
 */
export const GetTemplateRequestSchema: GenMessage<GetTemplateRequest> = /*@__PURE__*/
  messageDesc(file_panmail_v1_template_service, 2);

/**
 * @generated from message panmail.v1.GetTemplateResponse
 */
export type GetTemplateResponse = Message<"panmail.v1.GetTemplateResponse"> & {
  /**
   * @generated from field: panmail.v1.Template template = 1;
   */
  template?: Template | undefined;
};

/**
 * Describes the message panmail.v1.GetTemplateResponse.
 * Use `create(GetTemplateResponseSchema)` to create a new message.
 */
export const GetTemplateResponseSchema: GenMessage<GetTemplateResponse> = /*@__PURE__*/
  messageDesc(file_panmail_v1_template_service, 3);

/**
 * @generated from message panmail.v1.ListTemplatesRequest
 */
export type ListTemplatesRequest = Message<"panmail.v1.ListTemplatesRequest"> & {
  /**
   * @generated from field: int32 page_size = 1;
   */
  pageSize: number;

  /**
   * @generated from field: string page_token = 2;
   */
  pageToken: string;
};

/**
 * Describes the message panmail.v1.ListTemplatesRequest.
 * Use `create(ListTemplatesRequestSchema)` to create a new message.
 */
export const ListTemplatesRequestSchema: GenMessage<ListTemplatesRequest> = /*@__PURE__*/
  messageDesc(file_panmail_v1_template_service, 4);

/**
 * @generated from message panmail.v1.ListTemplatesResponse
 */
export type ListTemplatesResponse = Message<"panmail.v1.ListTemplatesResponse"> & {
  /**
   * @generated from field: repeated panmail.v1.Template templates = 1;
   */
  templates: Template[];

  /**
   * @generated from field: string next_page_token = 2;
   */
  nextPageToken: string;
};

/**
 * Describes the message panmail.v1.ListTemplatesResponse.
 * Use `create(ListTemplatesResponseSchema)` to create a new message.
 */
export const ListTemplatesResponseSchema: GenMessage<ListTemplatesResponse> = /*@__PURE__*/
  messageDesc(file_panmail_v1_template_service, 5);

/**
 * @generated from message panmail.v1.UpdateTemplateRequest
 */
export type UpdateTemplateRequest = Message<"panmail.v1.UpdateTemplateRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string subject = 3;
   */
  subject: string;

  /**
   * @generated from field: string body_html = 4;
   */
  bodyHtml: string;

  /**
   * @generated from field: string body_text = 5;
   */
  bodyText: string;

  /**
   * @generated from field: string design = 6;
   */
  design: string;
};

/**
 * Describes the message panmail.v1.UpdateTemplateRequest.
 * Use `create(UpdateTemplateRequestSchema)` to create a new message.
 */
export const UpdateTemplateRequestSchema: GenMessage<UpdateTemplateRequest> = /*@__PURE__*/
  messageDesc(file_panmail_v1_template_service, 6);

/**
 * @generated from message panmail.v1.UpdateTemplateResponse
 */
export type UpdateTemplateResponse = Message<"panmail.v1.UpdateTemplateResponse"> & {
  /**
   * @generated from field: panmail.v1.Template template = 1;
   */
  template?: Template | undefined;
};

/**
 * Describes the message panmail.v1.UpdateTemplateResponse.
 * Use `create(UpdateTemplateResponseSchema)` to create a new message.
 */
export const UpdateTemplateResponseSchema: GenMessage<UpdateTemplateResponse> = /*@__PURE__*/
  messageDesc(file_panmail_v1_template_service, 7);

/**
 * @generated from message panmail.v1.DeleteTemplateRequest
 */
export type DeleteTemplateRequest = Message<"panmail.v1.DeleteTemplateRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message panmail.v1.DeleteTemplateRequest.
 * Use `create(DeleteTemplateRequestSchema)` to create a new message.
 */
export const DeleteTemplateRequestSchema: GenMessage<DeleteTemplateRequest> = /*@__PURE__*/
  messageDesc(file_panmail_v1_template_service, 8);

/**
 * @generated from message panmail.v1.DeleteTemplateResponse
 */
export type DeleteTemplateResponse = Message<"panmail.v1.DeleteTemplateResponse"> & {
};

/**
 * Describes the message panmail.v1.DeleteTemplateResponse.
 * Use `create(DeleteTemplateResponseSchema)` to create a new message.
 */
export const DeleteTemplateResponseSchema: GenMessage<DeleteTemplateResponse> = /*@__PURE__*/
  messageDesc(file_panmail_v1_template_service, 9);

/**
 * @generated from service panmail.v1.TemplateService
 */
export const TemplateService: GenService<{
  /**
   * @generated from rpc panmail.v1.TemplateService.CreateTemplate
   */
  createTemplate: {
    methodKind: "unary";
    input: typeof CreateTemplateRequestSchema;
    output: typeof CreateTemplateResponseSchema;
  },
  /**
   * @generated from rpc panmail.v1.TemplateService.GetTemplate
   */
  getTemplate: {
    methodKind: "unary";
    input: typeof GetTemplateRequestSchema;
    output: typeof GetTemplateResponseSchema;
  },
  /**
   * @generated from rpc panmail.v1.TemplateService.ListTemplates
   */
  listTemplates: {
    methodKind: "unary";
    input: typeof ListTemplatesRequestSchema;
    output: typeof ListTemplatesResponseSchema;
  },
  /**
   * @generated from rpc panmail.v1.TemplateService.UpdateTemplate
   */
  updateTemplate: {
    methodKind: "unary";
    input: typeof UpdateTemplateRequestSchema;
    output: typeof UpdateTemplateResponseSchema;
  },
  /**
   * @generated from rpc panmail.v1.TemplateService.DeleteTemplate
   */
  deleteTemplate: {
    methodKind: "unary";
    input: typeof DeleteTemplateRequestSchema;
    output: typeof DeleteTemplateResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_panmail_v1_template_service, 0);

