// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file panmail/v1/template_service.proto (package panmail.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateTemplateRequest, CreateTemplateResponse, DeleteTemplateRequest, DeleteTemplateResponse, GetTemplateRequest, GetTemplateResponse, ListTemplatesRequest, ListTemplatesResponse, UpdateTemplateRequest, UpdateTemplateResponse } from "./template_service_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service panmail.v1.TemplateService
 */
export const TemplateService = {
  typeName: "panmail.v1.TemplateService",
  methods: {
    /**
     * @generated from rpc panmail.v1.TemplateService.CreateTemplate
     */
    createTemplate: {
      name: "CreateTemplate",
      I: CreateTemplateRequest,
      O: CreateTemplateResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc panmail.v1.TemplateService.GetTemplate
     */
    getTemplate: {
      name: "GetTemplate",
      I: GetTemplateRequest,
      O: GetTemplateResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc panmail.v1.TemplateService.ListTemplates
     */
    listTemplates: {
      name: "ListTemplates",
      I: ListTemplatesRequest,
      O: ListTemplatesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc panmail.v1.TemplateService.UpdateTemplate
     */
    updateTemplate: {
      name: "UpdateTemplate",
      I: UpdateTemplateRequest,
      O: UpdateTemplateResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc panmail.v1.TemplateService.DeleteTemplate
     */
    deleteTemplate: {
      name: "DeleteTemplate",
      I: DeleteTemplateRequest,
      O: DeleteTemplateResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

