// @generated by protoc-gen-es v2.14.0 with parameter "target=ts,import_extension=none"
// @generated from file panmail/v1/webhook_service.proto (package panmail.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Webhook, WebhookTriggerEvent } from "./webhook_pb";
import { file_panmail_v1_webhook } from "./webhook_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file panmail/v1/webhook_service.proto.
 */
export const file_panmail_v1_webhook_service: GenFile = /*@__PURE__*/
  fileDesc("CiBwYW5tYWlsL3YxL3dlYmhvb2tfc2VydmljZS5wcm90bxIKcGFubWFpbC52MSJiChRDcmVhdGVXZWJob29rUmVxdWVzdBIMCgRuYW1lGAEgASgJEgsKA3VybBgCIAEoCRIvCgZldmVudHMYAyADKA4yHy5wYW5tYWlsLnYxLldlYmhvb2tUcmlnZ2VyRXZlbnQiPQoVQ3JlYXRlV2ViaG9va1Jlc3BvbnNlEiQKB3dlYmhvb2sYASABKAsyEy5wYW5tYWlsLnYxLldlYmhvb2siPAoTTGlzdFdlYmhvb2tzUmVxdWVzdBIRCglwYWdlX3NpemUYASABKAUSEgoKcGFnZV90b2tlbhgCIAEoCSJWChRMaXN0V2ViaG9va3NSZXNwb25zZRIlCgh3ZWJob29rcxgBIAMoCzITLnBhbm1haWwudjEuV2ViaG9vaxIXCg9uZXh0X3BhZ2VfdG9rZW4YAiABKAkiIgoURGVsZXRlV2ViaG9va1JlcXVlc3QSCgoCaWQYASABKAkiFwoVRGVsZXRlV2ViaG9va1Jlc3BvbnNlIn4KFFVwZGF0ZVdlYmhvb2tSZXF1ZXN0EgoKAmlkGAEgASgJEgwKBG5hbWUYAiABKAkSCwoDdXJsGAMgASgJEi8KBmV2ZW50cxgEIAMoDjIfLnBhbm1haWwudjEuV2ViaG9va1RyaWdnZXJFdmVudBIOCgZhY3RpdmUYBSABKAgiPQoVVXBkYXRlV2ViaG9va1Jlc3BvbnNlEiQKB3dlYmhvb2sYASABKAsyEy5wYW5tYWlsLnYxLldlYmhvb2sy5QIKDldlYmhvb2tTZXJ2aWNlElQKDUNyZWF0ZVdlYmhvb2sSIC5wYW5tYWlsLnYxLkNyZWF0ZVdlYmhvb2tSZXF1ZXN0GiEucGFubWFpbC52MS5DcmVhdGVXZWJob29rUmVzcG9uc2USUQoMTGlzdFdlYmhvb2tzEh8ucGFubWFpbC52MS5MaXN0V2ViaG9va3NSZXF1ZXN0GiAucGFubWFpbC52MS5MaXN0V2ViaG9va3NSZXNwb25zZRJUCg1EZWxldGVXZWJob29rEiAucGFubWFpbC52MS5EZWxldGVXZWJob29rUmVxdWVzdBohLnBhbm1haWwudjEuRGVsZXRlV2ViaG9va1Jlc3BvbnNlElQKDVVwZGF0ZVdlYmhvb2sSIC5wYW5tYWlsLnYxLlVwZGF0ZVdlYmhvb2tSZXF1ZXN0GiEucGFubWFpbC52MS5VcGRhdGVXZWJob29rUmVzcG9uc2VCpAEKDmNvbS5wYW5tYWlsLnYxQhNXZWJob29rU2VydmljZVByb3RvUAFaNGdpdGh1Yi5jb20vZ3NvdWx0YW4vcGFubWFpbC9hcGkvcGFubWFpbC92MTtwYW5tYWlsdjGiAgNQWFiqAgpQYW5tYWlsLlYxygIKUGFubWFpbFxWMeICFlBhbm1haWxcVjFcR1BCTWV0YWRhdGHqAgtQYW5tYWlsOjpWMWIGcHJvdG8z", [file_panmail_v1_webhook]);

/**
 * @generated from message panmail.v1.CreateWebhookRequest
 */
export type CreateWebhookRequest = Message<"panmail.v1.CreateWebhookRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string url = 2;
   */
  url: string;

  /**
   * @generated from field: repeated panmail.v1.WebhookTriggerEvent events = 3;
   */
  events: WebhookTriggerEvent[];
};

/**
 * Describes the message panmail.v1.CreateWebhookRequest.
 * Use `create(CreateWebhookRequestSchema)` to create a new message.
 */
export const CreateWebhookRequestSchema: GenMessage<CreateWebhookRequest> = /*@__PURE__*/
  messageDesc(file_panmail_v1_webhook_service, 0);

/**
 * @generated from message panmail.v1.CreateWebhookResponse
 */
export type CreateWebhookResponse = Message<"panmail.v1.CreateWebhookResponse"> & {
  /**
   * @generated from field: panmail.v1.Webhook webhook = 1;
   */
  webhook?: Webhook | undefined;
};

/**
 * Describes the message panmail.v1.CreateWebhookResponse.
 * Use `create(CreateWebhookResponseSchema)` to create a new message.
 */
export const CreateWebhookResponseSchema: GenMessage<CreateWebhookResponse> = /*@__PURE__*/
  messageDesc(file_panmail_v1_webhook_service, 1);

/**
 * @generated from message panmail.v1.ListWebhooksRequest
 */
export type ListWebhooksRequest = Message<"panmail.v1.ListWebhooksRequest"> & {
  /**
   * @generated from field: int32 page_size = 1;
   */
  pageSize: number;

  /**
   * @generated from field: string page_token = 2;
   */
  pageToken: string;
};

/**
 * Describes the message panmail.v1.ListWebhooksRequest.
 * Use `create(ListWebhooksRequestSchema)` to create a new message.
 */
export const ListWebhooksRequestSchema: GenMessage<ListWebhooksRequest> = /*@__PURE__*/
  messageDesc(file_panmail_v1_webhook_service, 2);

/**
 * @generated from message panmail.v1.ListWebhooksResponse
 */
export type ListWebhooksResponse = Message<"panmail.v1.ListWebhooksResponse"> & {
  /**
   * @generated from field: repeated panmail.v1.Webhook webhooks = 1;
   */
  webhooks: Webhook[];

  /**
   * @generated from field: string next_page_token = 2;
   */
  nextPageToken: string;
};

/**
 * Describes the message panmail.v1.ListWebhooksResponse.
 * Use `create(ListWebhooksResponseSchema)` to create a new message.
 */
export const ListWebhooksResponseSchema: GenMessage<ListWebhooksResponse> = /*@__PURE__*/
  messageDesc(file_panmail_v1_webhook_service, 3);

/**
 * @generated from message panmail.v1.DeleteWebhookRequest
 */
export type DeleteWebhookRequest = Message<"panmail.v1.DeleteWebhookRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message panmail.v1.DeleteWebhookRequest.
 * Use `create(DeleteWebhookRequestSchema)` to create a new message.
 */
export const DeleteWebhookRequestSchema: GenMessage<DeleteWebhookRequest> = /*@__PURE__*/
  messageDesc(file_panmail_v1_webhook_service, 4);

/**
 * @generated from message panmail.v1.DeleteWebhookResponse
 */
export type DeleteWebhookResponse = Message<"panmail.v1.DeleteWebhookResponse"> & {
};

/**
 * Describes the message panmail.v1.DeleteWebhookResponse.
 * Use `create(DeleteWebhookResponseSchema)` to create a new message.
 */
export const DeleteWebhookResponseSchema: GenMessage<DeleteWebhookResponse> = /*@__PURE__*/
  messageDesc(file_panmail_v1_webhook_service, 5);

/**
 * @generated from message panmail.v1.UpdateWebhookRequest
 */
export type UpdateWebhookRequest = Message<"panmail.v1.UpdateWebhookRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string url = 3;
   */
  url: string;

  /**
   * @generated from field: repeated panmail.v1.WebhookTriggerEvent events = 4;
   */
  events: WebhookTriggerEvent[];

  /**
   * @generated from field: bool active = 5;
   */
  active: boolean;
};

/**
 * Describes the message panmail.v1.UpdateWebhookRequest.
 * Use `create(UpdateWebhookRequestSchema)` to create a new message.
 */
export const UpdateWebhookRequestSchema: GenMessage<UpdateWebhookRequest> = /*@__PURE__*/
  messageDesc(file_panmail_v1_webhook_service, 6);

/**
 * @generated from message panmail.v1.UpdateWebhookResponse
 */
export type UpdateWebhookResponse = Message<"panmail.v1.UpdateWebhookResponse"> & {
  /**
   * @generated from field: panmail.v1.Webhook webhook = 1;
   */
  webhook?: Webhook | undefined;
};

/**
 * Describes the message panmail.v1.UpdateWebhookResponse.
 * Use `create(UpdateWebhookResponseSchema)` to create a new message.
 */
export const UpdateWebhookResponseSchema: GenMessage<UpdateWebhookResponse> = /*@__PURE__*/
  messageDesc(file_panmail_v1_webhook_service, 7);

/**
 * @generated from service panmail.v1.WebhookService
 */
export const WebhookService: GenService<{
  /**
   * @generated from rpc panmail.v1.WebhookService.CreateWebhook
   */
  createWebhook: {
    methodKind: "unary";
    input: typeof CreateWebhookRequestSchema;
    output: typeof CreateWebhookResponseSchema;
  },
  /**
   * @generated from rpc panmail.v1.WebhookService.ListWebhooks
   */
  listWebhooks: {
    methodKind: "unary";
    input: typeof ListWebhooksRequestSchema;
    output: typeof ListWebhooksResponseSchema;
  },
  /**
   * @generated from rpc panmail.v1.WebhookService.DeleteWebhook
   */
  deleteWebhook: {
    methodKind: "unary";
    input: typeof DeleteWebhookRequestSchema;
    output: typeof DeleteWebhookResponseSchema;
  },
  /**
   * @generated from rpc panmail.v1.WebhookService.UpdateWebhook
   */
  updateWebhook: {
    methodKind: "unary";
    input: typeof UpdateWebhookRequestSchema;
    output: typeof UpdateWebhookResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_panmail_v1_webhook_service, 0);

