// @generated by protoc-gen-es v2.14.0 with parameter "target=ts,import_extension=none"
// @generated from file panmail/v1/webhook.proto (package panmail.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file panmail/v1/webhook.proto.
 */
export const file_panmail_v1_webhook: GenFile = /*@__PURE__*/
  fileDesc("ChhwYW5tYWlsL3YxL3dlYmhvb2sucHJvdG8SCnBhbm1haWwudjEixAEKB1dlYmhvb2sSCgoCaWQYASABKAkSEQoJdGVuYW50X2lkGAIgASgJEgwKBG5hbWUYAyABKAkSCwoDdXJsGAQgASgJEi8KBmV2ZW50cxgFIAMoDjIfLnBhbm1haWwudjEuV2ViaG9va1RyaWdnZXJFdmVudBIOCgZhY3RpdmUYBiABKAgSLgoKY3JlYXRlZF9hdBgHIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASDgoGc2VjcmV0GAggASgJKtMCChNXZWJob29rVHJpZ2dlckV2ZW50EiUKIVdFQkhPT0tfVFJJR0dFUl9FVkVOVF9VTlNQRUNJRklFRBAAEiMKH1dFQkhPT0tfVFJJR0dFUl9FVkVOVF9NQUlMX1NFTlQQARIoCiRXRUJIT09LX1RSSUdHRVJfRVZFTlRfTUFJTF9ERUxJVkVSRUQQAhIlCiFXRUJIT09LX1RSSUdHRVJfRVZFTlRfTUFJTF9PUEVORUQQAxImCiJXRUJIT09LX1RSSUdHRVJfRVZFTlRfTUFJTF9DTElDS0VEEAQSJgoiV0VCSE9PS19UUklHR0VSX0VWRU5UX01BSUxfQk9VTkNFRBAFEicKI1dFQkhPT0tfVFJJR0dFUl9FVkVOVF9NQUlMX1JFSkVDVEVEEAYSJgoiV0VCSE9PS19UUklHR0VSX0VWRU5UX01BSUxfSU5CT1VORBAHQp0BCg5jb20ucGFubWFpbC52MUIMV2ViaG9va1Byb3RvUAFaNGdpdGh1Yi5jb20vZ3NvdWx0YW4vcGFubWFpbC9hcGkvcGFubWFpbC92MTtwYW5tYWlsdjGiAgNQWFiqAgpQYW5tYWlsLlYxygIKUGFubWFpbFxWMeICFlBhbm1haWxcVjFcR1BCTWV0YWRhdGHqAgtQYW5tYWlsOjpWMWIGcHJvdG8z", [file_google_protobuf_timestamp]);

/**
 * @generated from message panmail.v1.Webhook
 */
export type Webhook = Message<"panmail.v1.Webhook"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string tenant_id = 2;
   */
  tenantId: string;

  /**
   * @generated from field: string name = 3;
   */
  name: string;

  /**
   * @generated from field: string url = 4;
   */
  url: string;

  /**
   * @generated from field: repeated panmail.v1.WebhookTriggerEvent events = 5;
   */
  events: WebhookTriggerEvent[];

  /**
   * @generated from field: bool active = 6;
   */
  active: boolean;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 7;
   */
  createdAt?: Timestamp | undefined;

  /**
   * The signing secret, returned only by CreateWebhook and empty on every
   * other read.
   *
   * Panmail signs the notifications it sends so a receiver can tell a real one
   * from a forged one — it verifies the webhooks it receives from SendGrid and
   * Mailgun, and left the same threat open in the other direction. Shown once
   * because storing it in a form that can be read back turns every list
   * response into a way to obtain it.
   *
   * @generated from field: string secret = 8;
   */
  secret: string;
};

/**
 * Describes the message panmail.v1.Webhook.
 * Use `create(WebhookSchema)` to create a new message.
 */
export const WebhookSchema: GenMessage<Webhook> = /*@__PURE__*/
  messageDesc(file_panmail_v1_webhook, 0);

/**
 * @generated from enum panmail.v1.WebhookTriggerEvent
 */
export enum WebhookTriggerEvent {
  /**
   * @generated from enum value: WEBHOOK_TRIGGER_EVENT_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: WEBHOOK_TRIGGER_EVENT_MAIL_SENT = 1;
   */
  MAIL_SENT = 1,

  /**
   * @generated from enum value: WEBHOOK_TRIGGER_EVENT_MAIL_DELIVERED = 2;
   */
  MAIL_DELIVERED = 2,

  /**
   * @generated from enum value: WEBHOOK_TRIGGER_EVENT_MAIL_OPENED = 3;
   */
  MAIL_OPENED = 3,

  /**
   * @generated from enum value: WEBHOOK_TRIGGER_EVENT_MAIL_CLICKED = 4;
   */
  MAIL_CLICKED = 4,

  /**
   * @generated from enum value: WEBHOOK_TRIGGER_EVENT_MAIL_BOUNCED = 5;
   */
  MAIL_BOUNCED = 5,

  /**
   * @generated from enum value: WEBHOOK_TRIGGER_EVENT_MAIL_REJECTED = 6;
   */
  MAIL_REJECTED = 6,

  /**
   * @generated from enum value: WEBHOOK_TRIGGER_EVENT_MAIL_INBOUND = 7;
   */
  MAIL_INBOUND = 7,
}

/**
 * Describes the enum panmail.v1.WebhookTriggerEvent.
 */
export const WebhookTriggerEventSchema: GenEnum<WebhookTriggerEvent> = /*@__PURE__*/
  enumDesc(file_panmail_v1_webhook, 0);

