// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file panmail/v1/webhook_service.proto (package panmail.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateWebhookRequest, CreateWebhookResponse, DeleteWebhookRequest, DeleteWebhookResponse, ListWebhooksRequest, ListWebhooksResponse, UpdateWebhookRequest, UpdateWebhookResponse } from "./webhook_service_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service panmail.v1.WebhookService
 */
export const WebhookService = {
  typeName: "panmail.v1.WebhookService",
  methods: {
    /**
     * @generated from rpc panmail.v1.WebhookService.CreateWebhook
     */
    createWebhook: {
      name: "CreateWebhook",
      I: CreateWebhookRequest,
      O: CreateWebhookResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc panmail.v1.WebhookService.ListWebhooks
     */
    listWebhooks: {
      name: "ListWebhooks",
      I: ListWebhooksRequest,
      O: ListWebhooksResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc panmail.v1.WebhookService.DeleteWebhook
     */
    deleteWebhook: {
      name: "DeleteWebhook",
      I: DeleteWebhookRequest,
      O: DeleteWebhookResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc panmail.v1.WebhookService.UpdateWebhook
     */
    updateWebhook: {
      name: "UpdateWebhook",
      I: UpdateWebhookRequest,
      O: UpdateWebhookResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

